### ISSUE TITLE
Running test fixtures manually one by one is much faster than running them in a suite

### ISSUE THREAD

**Issue by itaibh** [nunit/nunit3-vs-adapter#1000]
* NUnit 3.13.2 
* NUnit3TestAdapter 3.17.0
* Microsoft Visual Studio Enterprise 2019 Version 16.11.7
* .net framework 4.6.1

Also asked here: https://stackoverflow.com/questions/73049030/nunit-when-running-test-fixtures-one-by-one-they-run-faster-than-when-i-run-the

I have several NUnit suites in a solution, each tests a project.

Some of the suites are very big (800 tests, 500 tests, etc.)

I run them inside VS2019 (no extensions like ReSharper, just clean VS2019).

When I run each `TestFixture` in a suite (about 30 fixtures in each suite) one by one (manually, going one by one, right-clicking on the fixture and then clicking "run") the time it takes to finish was much lower then running the entire suite, which is crazy.

I made sure there is no parallelization that can interfere.

A suite with 483 tests spread across 27 fixtures took total duration of 5.9 minutes running fixtures one by one the way I described above (total duration as reported on Visual Studio Test Explorer)

Running the same tests just by running the suite took total duration of 31.2 minutes.

I noticed some tests that took less than a second in manual run (sometimes even as low as 50 ms) took up to 13 seconds and more when running the suite.

**Comment by OsirisTerje** [comment]
First, congratulations on creating issue #1000 !  😄 

The adapter runs only one project at a time.  It is the Visual Studio Testhost executable that orchestrates the test run, and send each test project to the adapter, one at a time.  If the testhost is set up to run in parallel then it will fire up multiple test adapters each running a single test project.  
You can turn on tracing for the testhost to see if you get any more clues from that.   See https://github.com/microsoft/vstest-docs/blob/main/docs/diagnose.md for more information. 
If a test that runs "alone" takes <1 s goes up to 13 seconds, then it sounds like something is blocking it.  Is there anything in the tested code that relies on the same resource(s) ?  

It could also be wise to run the tests from the command line using **dotnet test**. Then you eliminate one layer (Visual Studio itself).  From what you write you should see the same pattern there. 

You say you have turned off parallelization.  I assume you then have turned off both NUnit parallelization (which should not affect anything here) and the testhost parallelization, which is controlled by the runsettings MaxCpuCount property.  See https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2022#runconfiguration-element  

Also, ensure you have turned off all datacollections, including code coverage, so that you narrow down the possibilities. You do that also in the runsettings file, and it could be wise to disable code coverage packages if you're using any of the those.

**Comment by itaibh** [comment]
Thanks, I'll try.
