### ISSUE TITLE
Exception while loading tests; tests don't run. Since 4.3.1

### ISSUE THREAD

**Issue by vdheuvel** [nunit/nunit3-vs-adapter#1039]
* NUnit and NUnit3TestAdapter versions: NUnit 3.13.3, NUnit3TestAdapter 4.3.1
* Visual Studio edition and full version number (see Help About): Enterprise 2022 64 bit, version 17.3.6
* A short repro, preferably attached or pointing to a git repo or gist
* What .net platform and version is being targeted: test project is .NET Core 3.0, testing a library that is .Net Standard 2.0 (xamarin forms shared project)
* If TFS/VSTS issue, what version, hosted or on-premises, and what build task you see this in: none, running locally

Issue

All tests are visible in test explorer, but they don't run. When looking at the output, an exception seems to be causing it. Version 4.3.0 does not have this problem for me.

From the vs Tests output:

========== Starting test discovery ==========
NUnit Adapter 4.3.1.0: Test discovery starting
An exception occurred while test discoverer 'NUnit3TestDiscoverer' was loading tests. Exception: Could not load type 'System.Runtime.Remoting.Channels.IChannel' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
No test is available in C:\[redacted].dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
========== Test discovery finished: 0 Tests found in 1 sec ==========

I have another project in the same solution that does work with 4.3.1. This one targets .Net 6, and tests a .Net 6 console application (website project).

**Comment by OsirisTerje** [comment]
Can you please upload a repro project?

You can a) Add it as a PR to https://github.com/nunit/nunit3-vs-adapter.issues, add it as a separate folder named IssueXXX where the XXX is the issue number, or b) Add it as a zipped attachment here , or c) Add it to your own repo and just post the link. 

Make it as small as you can, it should compile "as is".

**Comment by vdheuvel** [comment]
[NUnitBug.zip](https://github.com/nunit/nunit3-vs-adapter/files/10193412/NUnitBug.zip)

Like I mentioned, version 4.3.0 does not have this problem for me.

**Comment by OsirisTerje** [comment]
@vdheuvel  Thanks for the repro!  

In 4.3.1 we dropped support for net core 2.1, which was LTS, but ended Aug 21, 2021, and then jumped to the next LTS, which is .Net core 3.1.  That means that the in-between net core versions were also dropped, that is 2.2 and 3.0.   I'll update the documentation on this at https://docs.nunit.org/articles/vs-test-adapter/Supported-Frameworks.html to be more precise, so thanks for raising the awareness of that. 

PS:  What happens here is that msbuild tries to load the next lower target, which is .net framework, and in the adapter there is a slightly different codebase for that, and that doesnt work well when actually being loaded in a net core environment.  
There should be a way to detect this, but I am not sure if the adapter can do that, since it actually doesn't really load.  We might perhaps catch the exception and give a better error message.

I'll leave the issue open for some time while looking into if that is possible.

**Comment by vdheuvel** [comment]
Got it working by choosing .Net Core 3.1 + NUnit3TestAdapter 4.3.1, like you suggested!
If you could give a better error message that would be helpful indeed.

Thanks for looking into it so quickly!
