### ISSUE TITLE
Explicit tests appear as warnings in NUnit 3.0

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit3-vs-adapter#106]
(Moved from https://github.com/nunit/nunit-vs-adapter/issues/94)
This issue comes from this other one for reference:
[nunit/nunit#50](https://github.com/nunit/nunit/issues/50)

Originally filed by @isaacllopisaracil

According to the definition of the [Explicit](https://github.com/nunit/nunit/wiki/Explicit-Attribute) tests in NUnit:

If a test or fixture with the Explicit attribute is encountered in the course of running tests, it is skipped unless it has been specifically selected by one of the above means. The test does not affect the outcome of the run at all: it is not considered as ignored and is not even counted in the total number of tests. In the gui, the tree node for the test remains gray and the status bar color is not affected.

However, after upgrading my NUnit tests to 3.0 and the VS Adapter, the tests marked as Explicit show as Warnings instead, marking my tests list with a yellow-orange warning error color.

**Comment by CharliePoole** [comment]
@isaacllopisaracil The text above from the documentation has been changed to correctly describe how the Explicit attribute works. You should bear in mind that the documentation of NUnit itself says nothing about how the test appears under the adapter, which we try to treat as an entirely separate product. I tried to reword the docs so that is clear.

The test window supports many fewer kinds of results than NUnit and it sometimes requires a compromise in how we report the results to VS. However, I agree that it is confusing to see explicit tests listed as warnings.

**Comment by CharliePoole** [comment]
Reopening this because the explicit test cases  were only being shown as expected (not run) on VS2015. But this was due to some other problems we are continuing to have. Now that I'm back to testing on VS2013, I see that these tests are reported as skipped and shown with a warning symbol.

The problem is that "Skipped" is always a warning for VS while it's usually more of a neutral thing for NUnit. We need to figure out (and document) the best way to translate our outcomes into the VS outcomes, retaining the proper level of error/warning/pass/neutral icon in the display.

**Comment by CharliePoole** [comment]
Although not reported as a bug here, the same issue appears for other skipped tests, such as those skipped because the platform is excluded.
