### ISSUE TITLE
Parsing error when namespace contains 0

### ISSUE THREAD

**Issue by evoAttilaK** [nunit/nunit3-vs-adapter#1096]
If the namespace where the test class is contains 0(Zero) than the following will happen:
<test-suite type="TestFixture" name="UnknownType" fullname="UnknownNamespace.UnknownType" ...>

namespace example: IT_MotorEngine.S0

And the message from the console:
Test Logger: Unable to parse one or more test names provided by your test runner. These will be logged using Namespace='UnknownNamespace', Type='UnknownType'. The entire test name will be used as the Method name. Please open a ticket so we can review this issue

**Comment by OsirisTerje** [comment]
Thanks for reporting this.

Which versions are you using?  NUnit, Adapter, dotnet framework ?


Can you please upload a small repro project?

You can a) Add it as a PR to https://github.com/nunit/nunit3-vs-adapter.issues, add it as a separate folder named IssueXXX where the XXX is the issue number, or b) Add it as a zipped attachment here, or c) Add it to your own repo and just post the link. 

Make it as small as you can, it should compile "as is".

**Comment by evoAttilaK** [comment]
Framework: net6.0-windows
TestAdapter: 4.3.0 but it comes with 4.4.2 as well
NUnit: 3.13.3

**Comment by evoAttilaK** [comment]
[NUnitParseIssue.zip](https://github.com/nunit/nunit3-vs-adapter/files/11543247/NUnitParseIssue.zip)
The repro project

**Comment by OsirisTerje** [comment]
Sorry for the delay here. Added this repro to the adapter issues repo at https://github.com/nunit/nunit3-vs-adapter.issues/tree/master/Issue1096 
and I can repro the issue,
<img width="474" alt="image" src="https://github.com/nunit/nunit3-vs-adapter/assets/203432/e5fa0c61-96ed-4558-83f2-3b0b5dadbe37">

But, this issue is in the Testlogger, not in NUnit.
So I suggest you raise this issue there, at https://github.com/spekt/nunit.testlogger
