### ISSUE TITLE
Executable name

### ISSUE THREAD

**Issue by shytikov** [nunit/nunit3-vs-adapter#115]
Hi, 

Apart the fact that `nunit3-vs-adapter` didn't worked for me in VS 2015 Community (I'm still investigating to provide you some details), I have another more important question.

Why `nunit3-vs-adapter` is not following naming convention used in the rest of the framework? Why it's library is called `NUnit3.VisualStudio.TestAdapter` but not `nunit.runner.visualstudio` for example?

**Comment by CharliePoole** [comment]
Both adapters use Microsoftish names because of their original. The earlier prototype for VS 2010 was written by a MS PM.

Is this only curiosity or does the naming cause some problem?

**Comment by shytikov** [comment]
It's only curiosity... Adapter name stands out of the line in references list, hence the question.

Definitely it would be nice to have consistent naming, but I don't know what it will give community except nice warm feeling that we're living in ideal world from now on.

**Comment by shytikov** [comment]
I dont' agree with issue resolution.

Let  me rephrase the topic:could we please eliminate one of the most obvious visual inconsistencies that was introduces in early prototype and still not fixed in version 3? 

While all other parts of `NUnit` was rewritten to keep solution up to date with modern requirements and we paid it with a huge price — all previous test are failing, all previous extensions are not working, we still keeping one of the earliest inconsistencies that should be easy to fix. And it it won't be fixed now, it will not be fixed until new version, that could take years of waiting.

**Comment by OsirisTerje** [comment]
I frankly don't understand the issue here.  There are no failing tests.  The extensions are working.  Which inconsistencies do you really see here ?  

Further, the adapter dll MUST end its name with TestAdapter.dll, that is a Microsoft requirement - needed for the VSTest to be able to pick it up.  
I think it is nice when the project, namespace and file names are equally named, making these different will just create confusion.  
And, imho the adapter is not really a runner, it is an adapter that sits between VSTest and the NUnit engine.

**Comment by CharliePoole** [comment]
@OsirisTerje I didn't realize that was a requirement although I did know about the restrictions on the Type name of the adapter. I don't suppose they document it anywhere. :-) Maybe we should document it.

@shytikov Well I asked you if it was just a question or a problem before I closed it!!! Frankly, aside from any MS restrictions, I don't see the issue. It's not an assembly you reference or use but is just installed where Visual Studio knows how to find it. That's why I was willing to leave it as named rather than calling it nunit-vs-adapter.dll or nunit.vs.adapter.dll, which would match our usual standard.

**Comment by OsirisTerje** [comment]
That is what I was told by the Microsoft PG people, and it is the same for XUnit, where the dll is named xunit.runner.visualstudio.testadapter.dll 
We have done fixes on this earlier, see https://github.com/nunit/nunit3-vs-adapter/pull/15 and https://github.com/nunit/nunit3-vs-adapter/issues/13.  We had issues at this time, and I asked the MS PG about it, and got a definite answer from them. We haven't documented it properly, so that should be done.  
We do have some Prosess tests which checks a few things like this, and we could add it there too.  However, any of the existing ones will fail if it is renamed, since we look for that specific name in those tests.

**Comment by CharliePoole** [comment]
Guess I forgot about that! What a kluge!
