### ISSUE TITLE
Corrupted ignore.addins file in installation

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit3-vs-adapter#118]
This was noted in #117 at https://github.com/nunit/nunit3-vs-adapter/issues/117#issuecomment-178706413

I'm making this a separate issue for ease of fixing it.

**Comment by ChrisMaddock** [comment]
I had a quick dig in to this, but I'm unable to replicate a package with a corrupt ignore.addins file.

Using NAnt 0.92 and NuGet 2.8.6 everything seems to be fine. @CharliePoole - are you aware of anything that could be different with the last packaging, which may have caused this?

**Comment by CharliePoole** [comment]
@ChrisMaddock Since the packaging is still done manually on my local machine, I tend to grab most things that have to do with it. No problem to keep chiming in, however. In fact, it's helpful.

**Comment by ChrisMaddock** [comment]
Cheers Charlie. Just to follow up, I downloaded NuGet.exe v2.8.0, and still produced a valid package - so I'm not sure what could have happened - bit of a dead end from me I'm afraid!

**Comment by CharliePoole** [comment]
Most likely something I did when creating the package!

**Comment by elangovana** [comment]
Hi, If you download the latest package from Nuget exe NuGet Version: 3.3.0.212 and execute the following, it adds a special character to ignore.addins file. 

###Nuget exe NuGet Version: 3.3.0.212 
.\.nuget\NuGet.exe  install NUnit3TestAdapter -version 3.0.8-ctp-8.

When you attempt to run tests with this corrupt version , you end up with error
 Exception System.ArgumentException, Exception thrown executing tests 
 Illegal characters in path. 



Ps. This problem does not occur with nuget.exe 2.x (version prior to 3.3.0.XX )

**Comment by rprouse** [comment]
@elangovana, thanks for the info, that should really help getting this fixed.

**Comment by CharliePoole** [comment]
@elangovana Is it only a problem with a zero-length file? Do our other .addins files (nunit.console for example) get corrupted with this version?

If it's only a zero-length file, I can just add a comment line in it.

**Comment by elangovana** [comment]
It is an issue with nunit.console  as well. 
However when I tested my own package with an empty file packed with Nuget.exe  2.8.60717.93,  installed with nuget.exe (v3.3) it seems fine.. Note: Test env - pack and  uninstall done on 64 bit  hosts...

**Comment by rprouse** [comment]
We should probably look at variations in encoding and line endings for the
files. Can you give us a binary representation of the file? I am wondering
if we have an empty UTF-8 w/ BOM file and the BOM is getting converted.

On 22 March 2016 at 22:27, elangovana <notifications@github.com> wrote:

> It is an issue with nunit.console as well.
> However when I tested my own package with an empty file packed with
> Nuget.exe 2.8.60717.93, installed with nuget.exe (v3.3) it seems fine..
> Note: Test env - pack and uninstall done on 64 bit hosts...
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/nunit/nunit3-vs-adapter/issues/118#issuecomment-200136126>
>



-- 

Rob Prouse



I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by rprouse** [comment]
I mean a binary (HEX) representation of the corrupted file :smile:

On 22 March 2016 at 23:04, Rob Prouse <rob@prouse.org> wrote:

> We should probably look at variations in encoding and line endings for the
> files. Can you give us a binary representation of the file? I am wondering
> if we have an empty UTF-8 w/ BOM file and the BOM is getting converted.
>
> On 22 March 2016 at 22:27, elangovana <notifications@github.com> wrote:
>
>> It is an issue with nunit.console as well.
>> However when I tested my own package with an empty file packed with
>> Nuget.exe 2.8.60717.93, installed with nuget.exe (v3.3) it seems fine..
>> Note: Test env - pack and uninstall done on 64 bit hosts...
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/nunit/nunit3-vs-adapter/issues/118#issuecomment-200136126>
>>
>
>
>
> --
>
> Rob Prouse
>
>
>
> I welcome VSRE emails. Learn more at http://vsre.info/
>



-- 

Rob Prouse



I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by elangovana** [comment]
Oops.. nunit.console doesn't have this issue  I think.. I saw the 1 in the file size  and assumed it has the special character expecting it to  be empty

**Comment by elangovana** [comment]
03 00 - Hex in the empty addins

**Comment by rprouse** [comment]
Well, I don't see how that relates to a UTF-8 byte order mark, `0xEF,0xBB,0xBF` :-1: 

I looked at all of our addin files, they are all a mix of UTF-8 and UTF-8-BOM. Ignore.Addins in our repo is definitely empty. Since this file is empty to start with, I assume that it was saved as plain UTF-8 w/o BOM, so it is showing up as ASCII. I wonder if adding the BOM would help?

Another interesting observation, whenever I try to open the package from the feed using NuGet Package Explorer, it crashes the program. Every other package I load works, so there is something corrupt.

**Comment by CharliePoole** [comment]
Ideally, our own code that reads the addins file should work for whatever encoding is there, since users may edit these files or create their own. We should probably be testing this.

**Comment by rprouse** [comment]
I agree that we should work with whatever encoding the files are in and probably do. I am pretty sure that the issue here is that the file is getting corrupted either creating or extracting the NuGet package and we need to figure out what is causing that.

Beyond that, we should also have some error handling reading the files so that bad data does not cause a crash. Ideally we handle the error at each line and move to the next.

**Comment by RobertK66** [comment]
@CharliePoole: In your Pull request #141 (https://github.com/nunit/nunit3-vs-adapter/pull/141) you asked for some other improvements on that issue. Here is mine: 
  I would suggest to move the Exception Handling Block in the method NUnit3TestDiscoverer.DiscoverTests() "one level higher". (Attaching to "try {" in line 46/47 instead of the one in line 49/50)
Other than the current behaviour (silently fail) this would give some Exception indication in the VS output folder if the call to GetRunnerFor(...) does not succeed.( At Least this was how I found the problem on my side – going the hard way to compile and debug this method….)

**Comment by CharliePoole** [comment]
This is fine... It's a good idea.
