### ISSUE TITLE
Test Explorer is Just One Big Flat List of Test Names With No Heirarchy or Groups

### ISSUE THREAD

**Issue by novaterata** [nunit/nunit3-vs-adapter#125]
Test Explorer is just a flat list of Test names with no TestFixture names / Namespaces / Categories of any kind. Do you have to put the Namespace as a string in Category on every single Test?

**Comment by novaterata** [comment]
OK, I found the Group By menu, so I can at least group by Class, but without Namespace it's still too vague to be practical.

**Comment by rprouse** [comment]
@novaterata we all agree that the Visual Studio Test Explorer is really hard to use for large test suites. Grouping helps, but even then it is a pain. Unfortunately, the NUnit team has no control over that. The NUnit Adapter provides the raw information to Visual Studio and runs the tests, but the test window itself is part of Visual Studio and we cannot change it.

I can't find anything appropriate after a quick search of the [Visual Studio UserVoice](https://visualstudio.uservoice.com/forums/121579-visual-studio-2015), so feel free to post your suggestions there. If you do, post back here so we can vote on it :smile: 

Unfortunately, I have to close this as wontfix since we can't change it.
