### ISSUE TITLE
Test execution status after systems time change not updated.

### ISSUE THREAD

**Issue by StarWars999123** [nunit/nunit3-vs-adapter#165]
Hello, 

in some of my tests its necessary to change the system time. Due to that, the test execution status icon was not updated correctly after test execution. I can see that the test was successful in the head execution status bar and by clicking on the test, but thats quite a lot of work...
It would be great, if the status icons would also be updated after the test run, eventhough the system time was changed during execution.

**Comment by rprouse** [comment]
Sorry, but changing the system date and time for your tests is a pretty serious code smell and highly not recommended. It can break software licensing and makes it impossible for NUnit to accurately time test runs. Because of this, it is not something we will put the effort in to get working.

What you should be doing is wrapping the DateTime.Now type calls in an interface and using dependency injection to inject that interface into the classes that need to access the current time. Then in your tests, you can inject a mock object that has the DateTime set to the value you need in your tests.

It is likely a large refactor in your code base, but a much cleaner design with fewer couplings. Often when you have to jump through hoops to test your code, it is a good indication that you should be taking a look at your architecture.
