### ISSUE TITLE
Difference when starting Processes from the test adapter vs from the console

### ISSUE THREAD

**Issue by Roemer** [nunit/nunit3-vs-adapter#167]
Hello
I'm facing some issues when using the NUnit3 Test Adapter in combination with UIA.
If I start, for example, mspaint in the unittest, paint something and close it so that the save/don't save/cancel dialog appears, those buttons are not recognized in UIA (for example with inspect). If I run the unittest with the nunit-console, those buttons are correctly recognized by UIA.
Is there a difference when starting processes from the Test Adapter than from the console?
Thanks for your help
Roman

**Comment by CharliePoole** [comment]
I think any difference will lie in how VS starts the process that runs the tests. One could examine the process settings in each case.

**Comment by Roemer** [comment]
I guess this is some kind of a bitness issue. In some cases, mspaint 64 bit is started and sometimes the 32 bit. There seems to be a problem with the 32 bit version. When I manually start the 32 bit version, I also get the problems in Inspect. Is there any way to configure the nunit-console or the NUnit3 Test Adapter if it should run in 32 or 64 bit?

**Comment by rprouse** [comment]
NUnit Console (actually the agent) will run x64 on a 64 bit system unless it detects that your test assembly is compiled x86 or you pass in the `--x86` flag.

Visual Studio defaults to x86 because it is 32 bit itself. You can switch to 64 bit in the test menu.

![image](https://cloud.githubusercontent.com/assets/493828/15185027/8667f7e2-1765-11e6-848b-796adc069212.png)

If you are launching mspaint yourself, if you want the 64 bit version, can't you just launch it using the full path to that version? `C:\Windows\SysWOW64\mspaint.exe` for the 32 bit version and `C:\Windows\system32\mspaint.exe` for the 64 bit.

@Roemer, It sounds like this is not an NUnit issue. Can we close this issue?

**Comment by Roemer** [comment]
Thanks for the information how to change the bitness of the tests. That solves this problem (at least from nunit side). So I'll close it.
