### ISSUE TITLE
NUnit v2 tests are not discovered by v3 adapter

### ISSUE THREAD

**Issue by xperiandri** [nunit/nunit3-vs-adapter#174]
Must NUnit Adapter v3 discover v2 tests?

**Comment by rprouse** [comment]
No, the v3 adapter does not currently discover v2 tests, you need the old adapter for that. You can install both adapters. They work fine together.

I am going to leave this issue open to start a discussion. Should we deprecate the v2 adapter and add the v2 driver to the engine with the adapter? Can we? We get a lot of questions here and on StackOverflow from confused users. @CharliePoole and @OsirisTerje, thoughts?

**Comment by CharliePoole** [comment]
That would be a rather big reversal of an earlier decision to continue to support two adapters. What would be the pros of that other than stopping the confusion? Are there alternative ways to stop the confusion? For example, can we just rename the old adapter to "NUnit 2 VS Adapter?"

It's not that I'm against the idea entirely, but it's a fair bit of work for which I'd like to see an equivalent amount of benefit.

**Comment by xperiandri** [comment]
Just write a proper description in Visual Studio gallery and in ReadMe of repositories.

**Comment by CharliePoole** [comment]
@xperiandri Just to be clear... in case Rob's use of the word "currently" may be confusing... the NUnit 3 adapter was never designed to support NUnit 2 tests. Our plan was that there would continue to be two adapters in the future and that you can install one or both of them as you like.

As you see above, Rob has raised the question about possibly changing direction. If we do, then there will be a major project effort for creating a combined adapter. As a guess, I would say that will be more like a 4.0 than a 3.x release.

**Comment by rprouse** [comment]
If it is a major effort, then it probably isn't worth it. I guess I was hoping it was as simple as adding the NUnit 2 driver to the engine, but it isn't ever that simple is it :smile: 

I also thought it would allow us to make fixes in one extension rather than two.

But if it is as much work as you say, shall we close this @CharliePoole?

**Comment by CharliePoole** [comment]
@xperiandri As you can imagine, those who wrote the descriptions think they are clear. :-) But as a user, you can help us by pointing out where improvements are needed.

In the gallery, each description lists the range of NUnit versions for which the adapter is used. Do you think we should say more?

I'm surprised to see that neither repository has a readme. We'll fix that.

**Comment by xperiandri** [comment]
I think that current approach is OK as long as everybody can quickly understand current approach.

**Comment by CharliePoole** [comment]
@rprouse It may indeed be that simple. :-) Unfortunately, it's not so simple to add extensions into the engine used by VS right now. We could probably cobble something together, but it would not be the ultimate solution, which requires resolving a few engine and extension issues first. Right now, the use of the engine by the NUnit 3 adapter is a lot more adhoc than I would like. For example, to upgrade the engine package, I have to make a number of manual changes to the solution.

It's not an impossible task, but it seems to be lower in priority than a lot of other things going on... Also, I'm still the one working on the NUnit 3 adapter right now and I'm involved in many of those other things as well.

Let's keep this issue for now with at least the goal of reducing confusion. I'll add readme files. What do you think of the idea of a name change?

**Comment by rprouse** [comment]
@CharliePoole I think the name change would help along with updating the description. I don't think most users go to the gallery to install extensions, they probably do it through Visual Studio, so I think this view is what we need to optimize.

![image](https://cloud.githubusercontent.com/assets/493828/15720011/862c6a50-2800-11e6-818d-c4f0a2d715d4.png)

Maybe change the titles to be `NUnit 3 Test Adapter` and `NUnit 2 Test Adapter`? Then under the descriptions, drop the supported versions of Visual Studio to give us more room. That info can be on the Gallery page since Visual Studio will only show supported versions.

The descriptions can then be something like;

```
NUnit 3 adapter for running tests in Visual Studio.
Works with NUnit 3.x, use the NUnit 2 adapter for 2.x tests.
```

and

```
NUnit 2 adapter for running tests in Visual Studio.
Works with NUnit 2.x, use the NUnit 3 adapter for 3.x tests.
```

**Comment by CharliePoole** [comment]
@rprouse We should look at the NuGet package text as well

@xperiandri I guess by main you mean the NUnit repo? It doesn't currently say anything about the adapters, because we treat them as separate software products. But maybe we should list related products like the gui, the project editor and the two adapters.

**Comment by CharliePoole** [comment]
I added issues to the other two repos to match this one. Discussion can continue here if needed.

**Comment by CharliePoole** [comment]
Steps to complete this issue:
1. Add readme to V3 adapter repo
2. Modify description as described by @rprouse above.
3. Change the title to NUnit 3 Test Adapter

One comment... in the VS gallery, the above title is clear. In other venues, the title needs to include VS or Visual Studio in order to tell people what we are adapting to.

I'll take care of this issue in the 3.2 release.
