### ISSUE TITLE
VSTest reporting Inconclusive as Error

### ISSUE THREAD

**Issue by phatcher** [nunit/nunit3-vs-adapter#219]
I'm trying to run some SpecFlow tests integrated with NUnit on Visual Studio Team Services.

However, for any partially implemented scenarios, the tests fails causing the build to break - NUnit seems to be reporting Inconclusive so is this a handoff issue between SpecFlow/NUnit or NUnit/VSTest ?

2016-08-11T12:58:10.5008013Z Information: TestMethod: AddTwoNumbers in MyFeature -> Failed on thread #0
2016-08-11T12:58:10.5018014Z ##[error]      at TechTalk.SpecRun.Framework.TestAssemblyExecutor.ExecuteTestNodeTask(TestNode testNode, ITaskExecutor task, TraceEventType eventType)Error: 	[ERROR] No matching step definition found for one or more steps.
2016-08-11T12:58:10.5018014Z ##[error]using System;
2016-08-11T12:58:10.5018014Z ##[error]using TechTalk.SpecFlow;
....
2016-08-11T12:58:11.2898008Z ##[error]   at NUnit.Framework.Assert.Inconclusive(String message, Object[] args)
2016-08-11T12:58:11.2908014Z ##[error]   at lambda_method(Closure , String , Object[] )
2016-08-11T12:58:11.2908014Z ##[error]   at TechTalk.SpecFlow.UnitTestProvider.NUnitRuntimeProvider.TestInconclusive(String message)
2016-08-11T12:58:11.2918009Z ##[error]   at TechTalk.SpecFlow.ErrorHandling.ErrorProvider.ThrowPendingError(TestStatus testStatus, String message)
2016-08-11T12:58:11.2918009Z ##[error]   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
2016-08-11T12:58:11.2918009Z ##[error]   at TechTalk.SpecFlow.TestRunner.CollectScenarioErrors()
2016-08-11T12:58:11.2928003Z ##[error]   at Gul.Trunk.Test.Bdd.Sensors.SensorSecurityFeature.ScenarioCleanup()
2016-08-11T12:58:11.2928003Z ##[error]   at Gul.Trunk.Test.Bdd.Sensors.SensorSecurityFeature.AddTwoNumbers() in C:\a\1\s\Code\Gul.Trunk.Domain.Test\Bdd\Sensors\SensorSecurity.feature:line 10
2016-08-11T12:58:11.2938007Z ##[error]   at TechTalk.SpecRun.Framework.TaskExecutors.StaticOrInstanceMethodExecutor.ExecuteInternal(ITestThreadExecutionContext testThreadExecutionContext)
2016-08-11T12:58:11.2938007Z ##[error]   at TechTalk.SpecRun.Framework.TaskExecutors.StaticOrInstanceMethodExecutor.Execute(ITestThreadExecutionContext testThreadExecutionContext)
2016-08-11T12:58:11.2948012Z ##[error]   at TechTalk.SpecRun.Framework.TestAssemblyExecutor.ExecuteTestNodeTask(TestNode testNode, ITaskExecutor task, TraceEventType eventType)Standard Error Messages:
2016-08-11T12:58:11.2948012Z ##[error]   No matching step definition found for one or more steps.
....
2016-08-11T12:58:12.7308003Z ##[error]      at TechTalk.SpecRun.Framework.TestAssemblyExecutor.ExecuteTestNodeTask(TestNode testNode, ITaskExecutor task, TraceEventType eventType)Test Run Failed.
....
2016-08-11T12:58:13.1867996Z ##[error]System.Exception: VSTest Test Run failed with exit code: 1

**Comment by CharliePoole** [comment]
I can see that NUnit's Assert.Inconclusive is being called but I don't see NUnit actually handling the exception. It appears that your code (SpecFlow code?) is handling it and reporting a failure. Since SpecFlow generates the NUnit tests and apparently (from your post) runs them and handles the exceptions, it seems that this is something to be reported to SpecFlow.

**Comment by CharliePoole** [comment]
Closing this as not a bug (meaning not our bug) but we can re-open if the SpecFlow folks give you some information that indicates NUnit is doing something wrong here or if you have more information.

**Comment by phatcher** [comment]
Thanks Charlie - I'll report it there and also do some investigation e.g. create a test project to see if all the statuses bubble up correctly in VSTS from NUnit

**Comment by CharliePoole** [comment]
It's a well-known problem that Visual Studio does not recognize the Inconclusive result. However, it should be reported as not run rather than as an error.

**Comment by OsirisTerje** [comment]
MSTest is reporting Inconclusive as Skipped.  It seems that the Outcome None will be converted to Failed.

**Comment by CharliePoole** [comment]
@OsirisTerje MSTest doesn't appear to have an Inconclusive result, which is why the Test Explorer doesn't have it. They do have Assert.Inconclusive, which is used for generating tests. It throws a separate exception and is reported as skipped.

NUnit has had a separate Inconclusive result for a long time, from before we had a test adapter. It has always been shown as skipped. If there is some changed configuration that reports it as a failure, somebody has to show up with a reproducible test case. Our own tests report it as expected when I run them.

**Comment by OsirisTerje** [comment]
If I run the following code:
` public class Class1
    {
        [Test]
        public void InconclusiveTest()
        {
            Assert.Inconclusive();
        }

        [Test]
        public void Failing()
        {
            Assert.Fail("Not working test");
        }

        [Test]
        public void Passing()
        {
            Assert.Pass();
        }

        [Ignore("Dont run this now")]
        [Test]
        public void Ignored()
        {
            Assert.Pass();
        }

    }`

I get the results in Test Explorer
![image](https://cloud.githubusercontent.com/assets/203432/21150305/d6f9c426-c15e-11e6-9e86-d01198dbec0f.png)

which is as expected, given that the Inconclusive is marked as Outcome.None in the adapter, but if I run it through the vstest-console, and generates a trx file, I get this:
![image](https://cloud.githubusercontent.com/assets/203432/21150357/032374a2-c15f-11e6-9485-18650794fb8f.png)

The NUNit console runner however, report is as Inconclusive, not as Skipped.
![image](https://cloud.githubusercontent.com/assets/203432/21150435/3b8c8cfc-c15f-11e6-858b-be78c5324f12.png)

**Comment by CharliePoole** [comment]
@OsirisTerje Exactly. That's what was reported WRT TFS by @phatcher, leading me to close it as "not our bug." Are you suggesting otherwise?

**Comment by OsirisTerje** [comment]
It is not our bug, but if we set the outcome to Skipped, not None, it would be reported correctly in the trx file, and equal to what mstest does, and would not affect anything else.   The adapter is an adapter.
I however would prefer that Microsoft fixed the testexplorer and vstest-console with trx so that both Inconclusive and Ignored tests are reported correctly as what they are, and not converted to something else, which always will be sort of wrong, one way or another.   It would be nice if someone from MS could chime in and have a say.

**Comment by CharliePoole** [comment]
@OsirisTerje I first reported the problem in 2011. I'm not optimistic. 😞

**Comment by CharliePoole** [comment]
@OsirisTerje As far as our reporting Skipped, it will then show up in the IDE with a warning symbol. NUnit's Inconclusive is not intended to be a warning of any kind - although MsTest's probably is. In particular, A Theory with some data points that don't meet it's assumptions would show those cases as warnings, which would be completely misleading since Theories are supposed to be able to handle data that fails the assumptions.

Essentially, there's no really good solution to this without VS supporting an additional fundamental result. Up to now "None" has seemed like the closest we can achieve while "adapting" our four fundamental results to a model that really only supports three. Of course, we have now added a fifth fundamental result, which will probably confuse matters even more.

**Comment by pvlakshm** [comment]
In this particular case NUnit are reporting the outcome of the inconclusive test as “None”, and vstest’s trx logger is translating that to “Failed” in the trx.
That would explain the inconsistency in the states between the trx file and the memory model.

There are a couple of options to consider to get to a consistent state:
(1) NUnit adapter makes a change: Instead of reporting the outcome as “None”, NUnit should report the outcomes as “Skipped” (note that this would change the way the tests show up in the IDE).
(2) vstest makes a change: instead of translating “None” to failed in the trx file, vstest translates it to “Skipped”.
In both of the above cases, the test will show up as skipped in both the IDE and in the trx file.

I will see if (2) is possible.

**Comment by CharliePoole** [comment]
As you probably know, the adapter was developed using the IDE as the primary target. I selected "None" because that's what Inconclusive actually means in NUnit: no meaningful result can be  determined from the test because some pre-conditions are not met. An NUnit Skipped result, OTOH, is one that has not been run at all, which could be for various reasons. It was also significant to us that the IDE uses a warning icon for skipped tests, which would be completely wrong for our Inconclusive tests, which are expected to fade into the background and are not even listed in the NUnit V2 gui when they form part of a Theory.

Btw, we already overload VS "Skipped" to mean both Skipped and Ignored, which are different things to NUnit. So adding an additional interpretation to VS "Skipped" is probably not a good idea.

So, for all of the above reasons, I'd rather not implement (1). I'm wondering, however, why you can't just report "None" in the same way that the IDE does.

An even better approach, I would think, would be for you to allow for more outcomes in the first place. Of the three major 3rd party unit test frameworks (NUnit, xUnit.net, mbunit), two support use extension of outcomes. NUnit borrowed the mbunit approach of having a fixed set of statuses, extended by a user-defined string label. NUnit IIRC added Inconclusive to the three that were supported by mbunit 3 and gallio. We recently added a fifth fundamental status: Warning. The current built-in outcomes that are used in NUnit are:
 * Passed
 * Failed
 * Failed:Error
 * Failed:Invalid
 * Failed:Cancelled
 * Warning
 * Warning:NoTests (assembly level only)
 * Skipped
 * Skipped:Ignored
 * Inconclusive
User extensions are able to define any number of outcomes by adding a distinguishing label to one of the five fundamental statuses.

If VS doesn't want to add more fundamental result types - which I can understand - can you provide for subtypes in some way? Without them, I"m not sure how we will translate our Warning results to VS at all - most likely, they will be reported as failures.

**Comment by tomkerkhove** [comment]
What's the status here?

**Comment by zelenp** [comment]
+1 What is the conclusion?

**Comment by CharliePoole** [comment]
I closed the issue back in August because there it's not an NUnit issue. The Microsoft issue is referenced above. 

On January 8, @prawalagarwal noted on that issue that it was being discussed here. As you can see, that's not the case. There has been no further discussion since I outlined the problem as we see it on January 6. 

About two hours ago, somebody at Microsoft closed their issue.

That's all I know at the moment. 😞
