### ISSUE TITLE
Still requiring 32bit process despite removal and update of Nunit 3.2 to 3.4

### ISSUE THREAD

**Issue by SoulFireMage** [nunit/nunit3-vs-adapter#230]
Hi again

Steps followed: 
1) Removed all of Nunit 3.2.0.0 and Nunit Adapter 3.2.0.0  packages and references.
2) Manually clearing out all packages/files from any folders in the solution.
3) Reinstalled from Nuget package manager the latest version as of today of the Test adapter and Nunit framework (3.4.1)
4) Rebuilt solution - its in x86 mode. 

I still get this perplexing, puzzling problem:

------ Discover test started ------
NUnit Adapter 3.2.0.0: Test discovery starting
Exception NUnit.Engine.NUnitEngineException, Exception thrown discovering tests in C:\Project Folder\Debug\TMS.exe
Cannot run tests in process - a 32 bit process is required.
NUnit Adapter 3.2.0.0: Test discovery complete

Why and how? I'd be very grateful to understand what I can do to get rid of the issue as I believe I tried everything reasonable :)

**Comment by rprouse** [comment]
Can you try removing the NuGet version of the adapter and try the VSIX version of the adapter and report back the results?

**Comment by CharliePoole** [comment]
Like @rprouse my guess is that you still have 3.2 installed as a VSIX extension. What happens when you have the adapter installed both as an extension and as a NuGet package is out of our control. In fact, it does different things under different versions of VS. Best approach is to use one type of install for the adapter or the other - don't mix them.

**Comment by SoulFireMage** [comment]
Hi @CharliePoole 

I've not got the VSIX version installed at all - I manually checked through the folders in case there was a rogue dll. It doesn't appear in my extensions list either. 

I've only ever used the nuget package versions - I didn't know about a VSIX version tbh.

I've not yet had chance to try it @rprouse , bit reluctant now that I read mixing them causes this issue!

**Comment by CharliePoole** [comment]
Just to add some clarity to this issue, which is an old one for which you may not have seen the discussions, I'll outline the problem in 3.2, which is resolved in 3.4.

1. Neither NUnit nor the adapter require that your assemblies be 32-bit.
2. Whether your tests require 32-bit or not to be loaded in the adapter process depends on two things:
   2.1 The nature of your tests - only you know if they target 32-bit.
   2.2 The nature of the process created by Visual Studio. If the tests require 32-bits, then VS needs to know that to create a process in which it can be loaded.
3. The message from NUnit 3.2 is spurious and arises from two factors:
   3.1 The adapter always runs tests in-process.
   3.2 The engine assumes that 32-bit tests can never be run in process, without checking the process.
4. The invalid assumption (3.2) is what was fixed in 3.4.

As a result of the above, you should have no problem at all if your tests do __not__ require 32 bits. In that case, you should not try to solve the problem based on the wording of the spurious message, by making everything 32-bits. That will never work. In fact, if they __do__ require it, you simply can't run them under the 3.2 adapter.

It's really clear from your messages that you are running the 3.2 adapter. If you were running the 3.4.1 adapter, the message would carry that version number. I don't know why you have not been able to completely upgrade, but that's definitely the case. As one suggestion, check under Tools | Extensions to see if you have the VSIX installed and remove it if it is.

**Comment by CharliePoole** [comment]
@SoulFireMage My suggestion and Rob's amount to the same result. Whether you upgrade to the new VSIX and remove the NuGet packages or upgrade the NuGet packages and remove the VSIX, you will only be using one type of install for the adapter. What's clear is that you are running the 3.2 adapter, so it must be installed somewhere.

**Comment by SoulFireMage** [comment]
I'll try it later today when I can take some time to reexamine it again then. Can the TestAdapter be installed such that it may never be in the solution but be on the system itself?

**Comment by rprouse** [comment]
Yes, the test adapter can be installed as an Extension so that is available for all projects. I prefer doing it that way, but some people prefer the NuGet as it automatically installs it for all developers working on a project. I would like to narrow your problem down a bit, so trying to the extension might show that it is a problem with the NuGet or possibly with the MEF cache of a previously installed version of the NuGet package. As @CharliePoole says, this was fixed in 3.4, so we are trying to figure out why it is happening to you even though you believe you have 3.4.1 installed. As you can see from the output you entered, it is saying that you have 3.2 installed.

**Comment by anttirt** [comment]
Had a similar problem after upgrading from NUnit 2.6 to 3.4, where tests were discovered but trying to run them produced the exception about requiring a 32-bit process.

Unchecking "prefer 32-bit" here fixed it:

![projectsettings](https://cloud.githubusercontent.com/assets/281067/19030739/75f1c4aa-8958-11e6-8cad-bb701ec6c1ef.png)

**Comment by rprouse** [comment]
@anttirt were you also using the 3.4.1 version of the NUnit Visual Studio adapter? This issue was fixed in that version. @SoulFireMage was using 3.2 according to the output in the issue.

**Comment by anttirt** [comment]
I'm using version 3.4.1 of the adapter.

However after spending an hour and a half trying to reduce a test case, I thought to try not just Rebuild All but to get a clean checkout of our project from version control.

Old checkout: Exception thrown when project is built with "Prefer 32-bit".
Old checkout after rebuild all: Exception thrown when project is built with "Prefer 32-bit".
Disk copy of project: Exception thrown when project is built with "Prefer 32-bit".
Clean checkout: No exception regardless of "Prefer 32-bit" setting.

So my conclusion is that some mysterious Visual Studio temporary file with stale data from before the NUnit upgrade caused the issue. :)

**Comment by rprouse** [comment]
Visual Studio caches extensions that are NuGet packages, it could have been a cached version of the 3.2 adapter.

**Comment by SoulFireMage** [comment]
It has fixed itself in between my doing a bunch of other work, including tearing out six figures worth of code to go into a separate data access DLL. Something in all that work may have refreshed the stale extension catch rprouse mentions? 

What I do know, it's now very nice to actually just write a test in the dll project and it just works instead of recompiling everything and relying on my memory of what sequence of events I need to go through. It's a huge winforms project :).

It's probably not fair to keep this open as I don't know what the fix was but the problem has gone away!

Thank you folks for commenting and helping me!
