### ISSUE TITLE
URL for "More information" should point to correct landing page

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit3-vs-adapter#272]
It now points to an older page. 
It should point to https://github.com/nunit/docs/wiki/Visual-Studio-Test-Adapter

**Comment by CharliePoole** [comment]
@OsirisTerje As far as I can tell, you made the fix and merged it yourself. Is that right? If so, please close this. 

I'm worndering, is there some reason you didn't want to use the normal PR process? I ask because I'd like to understand what your thinking is on this sort of thing. The rest of us are pretty rigorous in going through the process of review, even for small things, on production products.

**Comment by CharliePoole** [comment]
@OsirisTerje I haven't heard back from you so I'm going ahead and closing this. It looks like you fixed it using PR #279, which was merged by @rprouse.

**Comment by OsirisTerje** [comment]
HI Charlie!  I missed your question....,  so I am re-organising my mail notifications, to try avoid drowning and missing them, ... But this one was added to a PR, which Rob merged as you said, I didn't do that myself, so even if small it did follow the standard procedure.  
One thing, shoudl we always delete the issues branches?  Sometimes they can be good to back and have a look on what was done, and being in a branch makes it easier to see them.  For longer time, they should go ofc.

**Comment by CharliePoole** [comment]
@OsirisTerje The point is that somebody (me) had to spend time looking at this issue and reading code because you didn't mark the issue done and close it.

While I don't want to make a big deal about it, I did have to do a half hour or so of work over two weeks because you didn't do 30 seconds worth. The bigger burden is that I had to stay mindful of this small issue for a few weeks, rather than just getting it into the release notes right away.

None of us like administrative detail. But if it's properly spread around and nobody puts extra work on others then we can function well as a team. 

Aside from your idea of reorganizing notices, which sounds good, can you also look at the issue status in GitHub regularly? I find the Zenhub board the most useful. This is how.             other people know what is done and  I guess you would notice if you had finished some work and it shows up as still in process.
