### ISSUE TITLE
Test with FsCheck attribute not found in cache, NullReferenceException

### ISSUE THREAD

**Issue by marklam** [nunit/nunit3-vs-adapter#293]
I don't know enough about extending NUnit3's test attributes to know how much of this is a problem with the VS Adapter, and how much with [FsCheck's implementation of PropertyAttribute](https://github.com/fscheck/FsCheck/blob/nunit3/src/FsCheck.NUnit/FsCheckPropertyAttribute.fs#L46) - but the example I'm providing works OK under the console runner.

I've provided a [VS2015 repro repo ](https://github.com/marklam/UsingFsCheckWithNUnit3TestAdapter)using paket to pick up the NuGet packages for the FsCheck.NUnit NUnit3 branch build on Appveyor. But if a ready-built test assembly is preferable, then one is [available here](https://github.com/marklam/UsingFsCheckWithNUnit3TestAdapter/releases/tag/v1)

The VS Test adapter picks up the test, but running it produces an error of the form:
```
NUnit3TestExecutor converted 1 of 1 NUnit test cases
Test 0-1004 not found in cache
Error processing test-case event for UsingFsCheckWithNUnitTestAdapter.Fixture.MultiplyingByZeroIsZero
System.NullReferenceException: Object reference not set to an instance of an object.
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.TestFinished(XmlNode resultNode)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report)
NUnit Adapter 3.6.0.0: Test execution complete
```

**Comment by CharliePoole** [comment]
I've only just scanned through this on my phone, but it looks like you are creating a PropertyAttribute based on TestAttribute. That's not likely to coexist well with NUnit's own PropertyAttribute. Have I missed something?

**Comment by CharliePoole** [comment]
I'll examine this more closely when I get to my computer.

**Comment by CharliePoole** [comment]
It's worthwhile to first figure out if it's an NUnit problem rather than an adapter problem. Does the test succeed if you run it via the nunit console runner?

**Comment by marklam** [comment]
Yes, it runs OK under the console runner.

**Comment by CharliePoole** [comment]
If I understand correctly, the test in your repro is intended to work with any int x and the PropertyAttribute is supplying the x. Is this a random value?

Because VS calls the adapter to perform discovery in one process and again to run the tests in a different process, a random value will be generated twice. Since the value of X is part of the name we create for the test, one test name is reported to the IDE at discovery time and a different name is used at execution time. It would seem to VS that the original test was never executed and some unknown test was run instead. However, the result never gets to VS because the adapter finds it isn't in its cache. That's a minor error beside the main one - we should actually send the result to VS even if the test is not cached.

The main problem, however is with (if my assumption is correct) a value that is not generated in a repeatable fashion. NUnit had exactly the same problem, which we resolved for random values generated via the NUnit random methods. We save the random seed used for discovery in a file and re-use it when re-creating the tests in the execution process.

Of course, all of this is based on my guess as to what the PropertyAttribute is doing. If it's not random, but is generating values in some other non-repeatable way the same problem will occur.

**Comment by marklam** [comment]
From my understanding of the implementation of FsCheck.PropertyAttribute, which is shown at https://github.com/fscheck/FsCheck/blob/nunit3/src/FsCheck.NUnit/FsCheckPropertyAttribute.fs#L46
A single 'dynamic' test is created, which calls the attributed method with auto-generated values.
Running the test under the NUnit console runner shows that 1 test ran, and that it passed. The console output from the test run indicates that FsCheck tried 100 different values for x, and that the method always returned true.

**Comment by CharliePoole** [comment]
So what has happened here is that it generated 100 different values in the discovery process, which were given to VS as test cases. Then it generated a different set of values in the execution process. The tests seen at discovery time are not the same tests executed. This is a fundamental problem with the way that the Test Window calls the adapter.

I gather that you are a user of this attribute, not it's author. You should provide the info to the author about how it needs to work. If the attribute were to use NUnit to provide random values, then NUnit would make sure to provide the same 100 values in both stages.

BTW, I have to say that the attribute name is rather strange, considering what it does!

I'm going to close this as a "won't fix" - actually can't fix - but we can continue to discuss here if you have more questions.

**Comment by marklam** [comment]
Thanks for the help. I dug into the code and found where the FsCheck NUnit support was failing. 

The ``ISimpleTestBuilder.BuildFrom`` implementation was creating a single ``TestMethod``-derived object for the ``FsCheck.NUnit.Property``-annotated method, but it wasn't passing on the parent suite.

More importantly, though, the ``IWrapTestMethod.Wrap`` override created a ``TestCommand`` whose ``Execute`` method created a new ``TestMethod`` rather than executing the one supplied.

I fixed those, and now the console runner, VS Adapter and new GUI runner all run the test correctly, so I've sent the FsCheck team a pull request.

Thanks again for investigating this and giving me an idea of where I should look.
