### ISSUE TITLE
Directory.GetCurrentDirectory is C:\WINDOWS\system32 for NUnit3TestAdapter

### ISSUE THREAD

**Issue by smadala** [nunit/nunit3-vs-adapter#303]
## Discription ##
> Test Passing in NUnitTestAdapter is Failing in NUnit3TestAdapter.
> Run a test which depends on file in output directory.
> Failed with IO Exception.

##  Steps to Repro ##
> Download [NUnitTestProject1.zip](https://github.com/Microsoft/vstest/files/787950/NUnitTestProject1.zip)
> Run tests

**Comment by CharliePoole** [comment]
This actually has nothing to do with the adapters but is a difference between NUnit V2 and NUnit 3. In V2 we guaranteed that the current directory would match the location of the test assembly. In NUnit 3, due to parallelism, this is no longer possible. Use TestDirectory property from TextContext instead.

**Comment by OsirisTerje** [comment]
This will be fixed, see https://github.com/nunit/nunit3-vs-adapter/issues/609
