### ISSUE TITLE
How to filter Nunit test using VStest console and Nunit 3 adapter for VS?

### ISSUE THREAD

**Issue by bootrider** [nunit/nunit3-vs-adapter#306]
I develop the following unit test using Nunit 3.6:

    using System;
    using NUnit.Framework;
    
    namespace UnitTest.Test
    {
        [TestFixture]
        public class UnitTest1
        {
            [Test]
            public void Test_MarkedAsTest()
            {
                Assert.IsTrue(true);
            }
    
            [Test]
            [Explicit]
            public void Test_MarkedAsTestExplicit()
            {
                Assert.IsTrue(true);
            }
    
            [Test]
            [Category("Manual")]
            public void Test_MarkedAsTestManual()
            {
                Assert.IsTrue(true);
            }
    
            [Test]
            [Category("ShortRunning")]
            public void Test_MarkedAsTestShortRunning()
            {
                Assert.IsTrue(true);
            }
        }
    }

I want to be able to filter the test upon its category. I am using VSTest to execute the test and following the [documentation][1]  

When the command is executed without exclusions, 3 test ran (Explicit does not ran):
[![enter image description here][2]][2]

If test filter parameter is introduced, then "Explicit" test are executed:

[![enter image description here][3]][3]

If I try to filter, in order to execute the test NOT in the Manual or Explicit category, VSTest runs all the test
[![enter image description here][4]][4]

How to filter a category and the Explicit tests?

  [1]: https://msdn.microsoft.com/en-us/library/jj155796.aspx
  [2]: https://i.stack.imgur.com/Iyf2m.jpg
  [3]: https://i.stack.imgur.com/WTUJu.jpg
  [4]: https://i.stack.imgur.com/ueMBN.jpg

**Comment by CharliePoole** [comment]
Test filters in VS, as you know, use VS syntax. The NUnit adapter does its best to present tests to VS so that NUnit Categories are recognized as VS TestCategories, but there is still a bit of a gap between the two different ways of looking at tests.

I'll comment on each of your three examples:

1. This one is running exactly as it should. An Explicit test in NUnit is not intended to run unless it has been explicitly selected by name or category.

2. This is a well-known bug, documented as issue #47

**Comment by bvijaybhargav** [comment]
Hi, I am able to execute all the tests (specflow feature files) . However, can you please Help me how to execute a individual feature file?

Commands I tried :
B:\Koshervscode>nunit3-console.exe C:\Users\.\.\.\.\.\bin\Debug\test.dll  --where "name=Regression.Feature"

B:\Koshervscode>nunit3-console.exe C:\Users\.\.\.\.\.\bin\Debug\test.dll  --test "name=Regression.Feature"

**Comment by OsirisTerje** [comment]
@bvijaybhargav You're asking on a closed issue, and you're asking a console question on the adapter repo.  I would suggest you use the forum at https://gitter.im/nunit/nunit for usage related questions, which gives you a much better chance to get answers.

About the syntax for NConsole and the --where option, please see https://github.com/nunit/docs/wiki/Test-Selection-Language

**Comment by CharliePoole** [comment]
As @OsirisTerje says, you're asking in the wrong place. But as one final hint: you need to use the names that __Specflow__ creates for your features, because that's all NUnit can see. I'm not a user of Specflow, but from other comments I have seen I believe it creates a test fixture class for each fixture, giving that class some name. You'll have to check their documentation to see what those names are.
