### ISSUE TITLE
Better support of second pane in Test Explorer

### ISSUE THREAD

**Issue by JVimes** [nunit/nunit3-vs-adapter#319]
In MSTest, each parameterized test appears only once in the top pane, and cases for the selected test appear in the bottom. NUnit3TestAdapter essentially shows a flat list of all testcases for all tests. I suggest following MSTest's example because it's easier to browse and read.

![image](https://cloud.githubusercontent.com/assets/6148201/25541362/99a4ea52-2c0b-11e7-9348-ae59472a1cb2.png)

**Comment by rprouse** [comment]
I marked this as an idea for discussion as i think some people would prefer the existing format.

The existing NUnit format allows you to easily see which tests pass and fail, allows you to debug individual test cases and will highlight if individual test cases take much longer to run. 

The advantage of the MSTest format is that it cleans up the test list and as you say is easier to browse/read.

**Comment by rprouse** [comment]
Personally, what I would really like is for Visual Studio to provide a better test window. They haven't improved it in years 😄

**Comment by CharliePoole** [comment]
Actually, it's not really just a format change. What you see in the IDE in each case is an outcome of what each test framework defines to be a "test" and passes to VS as such. The designers of the Test Explorer window took the status quo of MSTest as the "standard" and designed accordingly. Both NUnit and xUnit have different underlying concepts and have had to adapt to the design as best we could. That's what happens when devs try to generalize from a single case!

MSTest and VS consider each method group a test. Args are treated as separate executions of the same test, giving separate results. I believe (not certain) that xUnit treats each method overload as a test. NUnit has always treated each case (method plus arguments) as a test. With NUnit, each "test" has a single result.

This difference (between NUnit and VS) leads to two different problems. The first is an old one: whenever VS mistakes two tests for one, it shows multiple results for a single NUnit test, where NUnit thinks it has two tests with one result each. This happens because the display name of a test in NUnit is not necessarily unique, whereas the Test Explorer wants it to be so.

The second is a new one to me - the problem you are describing. You would prefer to see multiple results for each "test" as you view them, having been infected by the VS view of things :smile: and because it seems easier to deal with in your usage.

In some ways, the second problem is easier to deal with than the first - and also makes the first go away! The nunit adapter __is__ after all an adapter, so we could make anything we want appear to be a test for VS. We could make each method be a test for example and present them to VS that way. The hesitancy I have is the same as @rprouse - whether it would be best for all users. I would prefer not to have it as a user option, since it would complicate the code and also because what we mean by a "test" is rather fundamental for both VS and NUnit.

Imagine we have a test with a lot of individual cases. The question is whether it's better to clutter the test list or the result list. Obviously, some panel will be cluttered in either case. Personally, provided the test list will correctly show that there are some failures, I think I would prefer your suggested approach. I also like the fact that it completely eliminates the long-term problem we have had with test identities in VS.

It remains to be seen how this will work with the location of failure points in the source code.

So count me as a qualified 👍

**Comment by JVimes** [comment]
Good point, this suggestion should be contingent upon being able to click items in the bottom pane and go to the test, debug test, etc. That would be the sweet spot for the UI, I think. Not sure how flexible the test explorer api is.

**Comment by CharliePoole** [comment]
@JVimes Actually, all that stuff is out of our hands, so whatever the IDE does for MSTest's individual results is what it will do for us. Some questions...

* If some of the individual results fail and some pass (in MSTest) do you see an indication of the failure in the test list, or do you only see it when you select the test?

* If memory serves, I think you can right-click on a result and go to the failure point in the source. Is that what you see?

You can easily simulate how VS will handle this situation for NUnit by giving several tests the same name. Just define a few test cases on a method and use the TestName named property to call them all the same thing. You will probably get an error message, but you should see the results.

**Comment by JVimes** [comment]
@CharliePoole Ah, okay. That's too bad. The above suggestion probably isn't good until Test Explorer gets a right click menu for results in the lower pane, with the needed entries. Even for MSTest, there isn't one. For the other question: with MSTest, if one result fails (lower pane) then its test fails in the upper pane.

Not sure if we want to leave this issue open, waiting for Test Explorer to change. Your call ;) I submitted a [suggestion ](https://github.com/Microsoft/testfx/issues/171) to the MSTest repo about adding a right-click menu to the lower pane. I'm not sure where it'll land.

**Comment by CharliePoole** [comment]
Actually, I performed the simulation myself, giving all the test cases in a set the name "Duplicate" and changing one so it failed. The (single) test in the test list shows as a duplicate. In the bottom pain, the failing test has a link to the point of failure.

That part is positive. However, I don't think your right click request can possibly work - at least not if your intention is to run or debug the failing test result only.

The only way we can have this kind of display is if we __do not__ identify each set of arguments as a separate test for VS. On it's side, VS can only instruct us to run __tests that it knows about__. All it can do is pass us the name of the test we told it about ("Duplicate" in my experiment), which will cause us to rerun all of those tests.

IOW, it's the current NUnit display of tests that makes possible the individual selection and running of test cases.

I'll keep this issue for discussion. I think it would be a good idea for the team to re-review this option and expressly decide whether it's something we want to consider further or not.

**Comment by CharliePoole** [comment]
BTW, what is the information that MSTest is showing in parentheses after the method name? It's clipped in the image. How do you express them in defining your tests?

**Comment by JVimes** [comment]
This request is blocked by Test Explorer's lack of right-click/debug in the lower pane. Hopefully they'll implement that, someday.

This request doesn't cover right-click (which is out of NUnit's hands). Right-click is a prereq for this request, for the reason you said: we can't afford to lose the ability to debug specific TestCases.

In the MSTest screenshot, the parenthesis show the parameter values for each result. Values are defined in `[DataRow(...)]` attributes, which are pretty much exactly like NUnit's `[TestCase(...)]` attribute.
