### ISSUE TITLE
Rebuilds before running tests

### ISSUE THREAD

**Issue by grokky1** [nunit/nunit3-vs-adapter#340]
I'm using VS2017. Every time I run a test, it first compiles the solution. Even if I don't change a thing, and just re-run a test, it first recompiles.

Is this normal? Is it a VS thing or a nunit-adapter thing?

**Comment by CharliePoole** [comment]
It's a VS thing. NUnit is not involved at all until the adapter is called.

**Comment by grokky1** [comment]
Slows down my workflow considerably... so annoying. 😢 

Glad it's not NUnit. Thanks Charlie!

**Comment by OsirisTerje** [comment]
If your solution is not too big, you can try the new Live Unit Testing.  It supports NUnit, and then you get the testing in the editor when you edit. You don't even need to compile, nor save.

**Comment by grokky1** [comment]
I think that's only available for VS Enterprise...

**Comment by jnm2** [comment]
@grokky1 Vanilla VS + NUnit adapter builds before running, just like VS's Start Debugging and Start Without Debugging menu items. ReSharper and NCrunch also build before running, though with NCrunch it's a continuous thing. Live Unit Testing had ways to go last I tried it. ReSharper is also developing its Continuous Testing Session feature.

It never bothered me. One tip I've heard is to use Copy If Newer instead of Copy Always on files that you have copying to output destination.

**Comment by grokky1** [comment]
@jnm2 Thanks for confirming it's not just me.

I guess I'm just used to the old json build system, together with TestDriven.Net, which always felt like it was not building before running tests (unless something changed).

So slow nowadays 😠

**Comment by jnm2** [comment]
No, I almost never use anything but Any CPU. I suggest running rebuild from the command line with a higher verbosity so that you can determine what is causing it to be out of date and rebuild rather than letting incremental building skip everything. I'd look for tips with Google.

**Comment by dangernme** [comment]
Same problem here. It is very time consuming. Every time a test case shloud be executed the whole project is  built first. None of the suggested solutions worked.

**Comment by jnm2** [comment]
I'm not sure what to tell you since I haven't seen this myself.
This is pretty out there but I wonder if you could be affected by it: `https://github.com/dotnet/corefx/issues/12403#issuecomment-405648853`

I'd suggest using [msbuildlog.com](http://msbuildlog.com) using `/t:build` instead of `/t:rebuild` to figure out what the changed files are which are causing full builds to occur.
