### ISSUE TITLE
Nunit3 VS Adapter won't run AutoFixture AutoMoqDataAttribute

### ISSUE THREAD

**Issue by xlecoustillier** [nunit/nunit3-vs-adapter#342]
Pasting from [this SO post](https://stackoverflow.com/q/44564377/1679537) for reference :

I'm trying to use AutoFixture with NUnit and Moq, using the following AutoMoqDataAttribute :

```
public class AutoMoqDataAttribute : AutoDataAttribute
{
    public AutoMoqDataAttribute()
        : base(new Fixture().Customize(new AutoMoqCustomization()))
    {
    }
}

```
But when I run this test :

```
[Test, AutoMoqData]
public void Test(Mock<IUser> user)
{
    // do stuff with user
}

```
The test never runs. AutomMoqData is hit correctly, but the code inside the test is never executed and everything ends without any warning. The test also doesn't appear in the test runner list.

But if I remove the parameter :

```
[Test, AutoMoqData]
public void Test()
{
    // do stuff without user
}

```
Everything runs fine, but this is less useful without the parameters passed :)

Am I missing something here ?

Here is the list of the Nuget packages versions :

```
<package id="AutoFixture" version="3.50.2" targetFramework="net452" />
<package id="AutoFixture.AutoMoq" version="3.50.2" targetFramework="net452" />
<package id="AutoFixture.NUnit3" version="3.50.2" targetFramework="net452" />
<package id="Moq" version="4.5.3" targetFramework="net452" />
<package id="NUnit" version="3.7.1" targetFramework="net452" />

```
In [his answer](https://stackoverflow.com/a/44566285/1679537), Mark Seemann concludes that NUnitVSTestAdapter is responsible for that, and he seems to be right, as everything goes smoothly on other test runners (Nunit console or TestDriven).

Thanks in advance, let me know if you need any more information.

**Comment by CharliePoole** [comment]
It may take one of the developers of AutoMoq to chime in here and give us an answer. Alternatively, we would have to examine their source code to figure out why it works under the console runner but not under the adapter. My working theory is that they do random value generation without using NUnit's repeatable random number generation. That would lead to different values generated at discovery and execution time.

Because the architecture of the VS test window requires us to invoke NUnit twice, the AutoMoq attributes are also being invoked twice, once at discovery and once at execution. So, in addition to random number generation, any feature they have that does not produce the same result on a second invocation will cause a problem under the adapter.

@nunit/framework-team I suggest we wait to see if somebody from AutoMoq chimes in before diving into this too deep. This could end up being most easily solved by them or it could require us to change how we pass data from discovery to execution, which is kind of a big deal.

**Comment by OsirisTerje** [comment]
From what I can read on the SO post comments, it doesn't look like AutoMoq will fix this.  The point being that it works in XUnit adapter, and that more than AutoMoq may also generate such random numbers.  We can't work over all of those, so this issue might need to be fixed in the adapter. 
But I wonder if it is the fact we add the parameter value as part of the test name which is the fundamental issue here.  @charlie Do you know if XUnit do the same?

**Comment by jnm2** [comment]
[@OsirisTerje Edited to fix @ mention]

**Comment by CharliePoole** [comment]
@OsirisTerje That's only partly why it isn't a problem in xunit.net. They use properties of the VS test case to save all the info they need to re-run using the same arguments. I suspect they don't repeat discovery at all.

**Comment by UnderHeavyDevelopment** [comment]
Since last NCrunch update, I get AutoFixture warning when running tests. They explain this here: http://www.ncrunch.net/documentation/considerations-and-constraints_unique-test-names
However I don't believe this is unsolvable problem, there must be a workaround.

**Comment by CharliePoole** [comment]
Still hoping for somebody from AutoMoq to come into the discussion, since June 15.

The alternative is a completely different adapter design or a VS extension that bypasses the Test Explorer. I'm thinking of both of these as future projects but they don't really amount to an immediate decision.

**Comment by rprouse** [comment]
@UnderHeavyDevelopment the problem that NCrunch has is the same that the NUnit Adapter has. Visual Studio discovers tests in one process then passes those test names to a second process to run. If frameworks like AutoFixture generates different parameters each run, then the test names change with the parameters. When the test names change, NUnit can no longer find the tests to run.

NUnit gets around this by using the same seed for our random generator between runs, but AutoFixture is using it's own random number generators, so we have no control over that.

You state that this is a solvable problem and to an extent it is, but it is up to frameworks like AutoFixture and AutoMoq to provide ways to reinitialize them so that they create the same tests between discovery and running. The other solution would be for Visual Studio to allow discovery and running in the same process, but that is difficult because you want your test list to live between builds. NUnit is caught in the middle. We can help with our framework, but even then, we cannot prevent the user from creating different tests on each run in a `TestCaseSource`.

**Comment by xlecoustillier** [comment]
AutoFixture team [released a fix](https://github.com/AutoFixture/AutoFixture/wiki/Known-Issues#test-name-strategies-for-nunit3) for this problem in their 3.51 version and I missed it). I tested it successfully, so I guess this issue can be closed.
I didn't get the chance to test it on NCrunch, but I suppose it should work as well.

Thanks!

**Comment by OsirisTerje** [comment]
@xlecoustillier  Thanks fior the update.  Appreciated!
