### ISSUE TITLE
Add test name pattern to the adapter runsettings

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit3-vs-adapter#358]
See #326 for discussion 

Currently the test name pattern is hardcoded, including a limit of 40 chars, in the adapter.  
By adding the test name pattern, as documented here https://github.com/nunit/docs/wiki/Template-Based-Test-Naming :  , as a separate setting in the nunit section in runsettings, the user can change this as wanted.  
The default will remain as {m}{a:40} meaning test method name, max 40 chars.

**Comment by CharliePoole** [comment]
While I know you understand the meaning, since this is a public post I wanted to correct the meaning of `{m}{a:40}`. It means...

The full name of the method, without truncation, followed by all the arguments in parentheses, separated by commas, with string arguments truncated to 40 chars. The total length of the name is indeterminate.
