### ISSUE TITLE
Diagnostics info

### ISSUE THREAD

**Issue by ili** [nunit/nunit3-vs-adapter#378]
Some diagnostics needed for adapter.
You see, if we do implement `ITestBuilder` and exception occurs in `BuildFrom` adapter's behavior is unpredictable: you either will see no tests or not all tests.

In sample repo please see tests marked with `ThrowsBuilderAttribute` 
By default you will see no tests in Test Explorer, but if you will comment one of tests marked with `ThrowsBuilderAttribute`  Test Explorer will show some tests.

It would be great if we can see some exception info in  VS Tests Output or somewhere else.

* NUnit and NUnit3TestAdapter 3.8.0
* Visual Studio 2017 15.3.0 
* Sample repo: https://github.com/ili/NUnitTests
* What .net platform and version is being targeted: `net45` & `netcoreapp1.1`

**Comment by CharliePoole** [comment]
Your sample project is using version 3.7.1 of NUnit and 3.8.0 of the adapter. There is no 3.8 release of the NUnit framework yet.

Since the code that interprets your custom test case builder is in the framework, it's better to examine this error from some point that is closer to the framework. The VS adapter, because it attempts to adapt the NUnit model to the very different VS model of tests, is a poor choice for developing extensions. I recommend you test from time to time using the console runner.

I"m very suspicious of your changing the full name of the test. While NUnit doesn't care about the form of the full name, the VS Test Explorer very much does care. NUnit itself __only__ changes the method portion of the name when SetName is used. The prefixed portion of the full name never changes. At a minimum, I suggest removing that code to see if the behavior is different.

What you should see in the XML output - assuming you run with the console runner - is that only the test that throws is marked as non-runnable.

Question: do you see the same result under both targeted platforms?

**Comment by OsirisTerje** [comment]
Closing as this doesn't seem related to the adapter and thread has gone dark.
