### ISSUE TITLE
Parallel tests are not executing using nunit gui runner

### ISSUE THREAD

**Issue by MahendraChoudhary** [nunit/nunit3-vs-adapter#385]
NUnit v3.0
NUnit gui runner: v2.6.3
NUnit adapter v3.8

I want to run two test fixture parallely in two browser but using gui runner tests are running in sequence. But using nunit3 console and adapter it is running fine.
Is it possible to run in parallel using gui runner

**Comment by CharliePoole** [comment]
The NUnit 2.6.3 GUI Runner is capable of running tests written using the NUnit V2 framework. When used with the NUnit 3 framework, it gives the appearance of working for some simple tests, but doesn't actually work correctly. In fact, the main feature change we made when we released NUnit 2.6.4, the final V2 release, is that it refuses to run tests written with NUnit 3 in order to avoid confusion.

Further, the NUnit VS adapter has absolutely nothing to do with either the V2 or the V3 console runner or the V2 GUI.

In order to run NUnit 3 tests in a GUI, you would need to use the NUnit 3 GUI, which has not yet been released for production. It is under development at https://github.com/NUnitSoftware/nunit-gui.
