### ISSUE TITLE
Test classes derived from an abstract base class are not discovered

### ISSUE THREAD

**Issue by GibbOne** [nunit/nunit3-vs-adapter#39]
public abstract class BaseTests
    {
    }

    public class Tests: BaseTests
    {
    /// Some tests
    }

By making the base class not abstract, the adapter discovers the test class correctly.
I'm using the version 3.0.2.0.

**Comment by CharliePoole** [comment]
Can you fill in the example with at least one actual test using the syntax that caused the problem to arise? NUnit marks tests in many ways and discovering them involves different code paths.

**Comment by GibbOne** [comment]
```javascript
using System.Collections.Generic;

namespace AbstractClassIssue
{
    // by removing abstract it works
    public abstract class BaseAbstract
    {
        public static List<object> GetData()
        {
            List<object> data = new List<object>();
            for (int i = 0; i < 10; i++)
                data.Add(i);
            return data;
        }

        //...
    }

    public class ClassTest
    {
        [Test, TestCaseSource(typeof(BaseAbstract), "GetData")]
        public void TestTest(int d)
        {
            Assert.Less(d, 100);
        }
    }
}
```

Here it is. Thanks!

**Comment by CharliePoole** [comment]
In your example, ClassTest doesn't derive from BaseTest. Is that just a typo?

As listed it should work. However, if your "GetData" method were not static it would fail. That's because NUnit would try to create an intance of the abstract class.

You should revisit this using Beta 3 of NUnit, since TestCaseSOurceAttribute changed in the new release. We'll shortly release a version of the adapter (CTP-4) that uses NUnit Beta 3.

**Comment by GibbOne** [comment]
Yes I made a typo :-). Thanks a lot for feedbacks.
G.
