### ISSUE TITLE
Pass DisableAppDomain and DisableParallelization settings to the Engine

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit3-vs-adapter#390]
Info about these settings coming from VSTest can be found at https://github.com/Microsoft/vstest-docs/blob/22834acc1848ecd6e6d9355c589c471433abd72c/docs/configure.md

Should we also handle `MaxCpuCount`?

We should also apply the `TestRunParameters` to our test parameters.

**Comment by CharliePoole** [comment]
IIRC we already handle test run parameters. We should figure out exactly what MaxCpuCount does. It's a funny name, since it doesn't change the number of CPUs you have. 😄 There's already an NUnit setting that controls how many test workers to set. We could use MaxCpuCount for that purpose, but what if the user provides both?

**Comment by OsirisTerje** [comment]
The MaxCpuCount setting handles the parallelization in VSTest.  VSTest has the ability to run test assemblies in parallel.  We could use the same setting, but since this setting controls VSTest it will grab the number of cores set there anyway, if there are enough test assemblies.   What could make sense is to interpret the 0 and 1 setting, and in particular the latter which turns off parallelization. 

We already reads the testrunparameters and add them to the NUnit testparameters.

**Comment by pvlakshm** [comment]
MaxCpuCount is described in this blog post: [Parallel Test Execution](https://blogs.msdn.microsoft.com/devops/2016/10/10/parallel-test-execution/), and documented on MSDN here [Configure unit tests by using a .runsettings file](https://msdn.microsoft.com/en-us/library/jj635153.aspx).

**Comment by CharliePoole** [comment]
So, comparing this to NUnit...

NUnit has two levels of parallel execution

1. Framework Parallel Test Execution
    https://github.com/nunit/docs/wiki/Framework-Parallel-Test-Execution

2. Engine Parallel Test Execution
    https://github.com/nunit/docs/wiki/Engine-Parallel-Test-Execution

Parallel execution in vstest seems to equate to the second type.

Framework parallel execution is controlled by attributes in the test and is
off by default. Even if the test assembly turns it on, it can be disabled
by an NUnit setting, which is available in the `runsettings` file. In the
context of the adapter, this pertains to a single assembly, because we only
run one assembly at a time.

Engine parallel execution involves creation of multiple processes, usually
one per assembly. When using the console runner with multiple assemblies,
it's the default. In the context of the adapter, it's not relevant because
we don't create processes and only run in the process passed to us by VS.

In the past we have talked about extending engine parallel execution to the
adapter. But since this is supported by vstest, it no longer makes much
sense to me.

Charlie
