### ISSUE TITLE
[Test] Function right-click context menu options are gone

### ISSUE THREAD

**Issue by Kizmar** [nunit/nunit3-vs-adapter#412]
NUnit Version: 3.8.1
NUnit Test Adapter Version: 3.9.0.0
Visual Studio Version: 15.4.1 (Community Edition)
.NET Framework version: 4.6.2

I've been using the test adapter extensions so I can right-click on test functions and run them. This morning I noticed the context menu options (Run tests, Debug tests) are no longer showing. About the same time I got a VS notification that there was an available update to the test adapter extension. I updated that (close & re-open VS, clean & rebuild). Still no context menu options. I also updated the version of NUnit  in the test projects (close & re-open VS for good measure, clean & rebuild). That didn't fix it either.

Any suggestions? Am I dealing with version conflicts? I'm not sure when this problem started. It's been a week or more since I've used the right-click context menu options.

[Edit:]
When I noticed the issue I was on NUnit 3.5.0 and using which ever version preceded 3.9.0.0 of the test adapter extension (I'm assuming 3.8.1). Same version of VS & .NET Framework.

[Edit 2:]
I am able to use Test > Windows > Test Explorer to run tests still.

**Comment by rprouse** [comment]
The adapter doesn't create those menu options, they are created by Visual Studio once the tests are discovered, so it is odd that the tests show up in the Test Explorer, but not in the context menu. I just upgraded to the 3.9 adapter and it is working fine for me. Some things to check,

- Do you have the adapter installed as a NuGet package or a VSIX? I recommend the NuGet package.
- Can you still run tests with `Ctrl+R,T` when your cursor is inside the test method?

![image](https://user-images.githubusercontent.com/493828/32233926-f428cd8c-be31-11e7-968b-a7374a7a9146.png)

I am going to mark this as a question since it is a VS issue, not an adapter issue. Hopefully we can still help you figure it out though.

**Comment by Kizmar** [comment]
Did more testing on my laptop (vs. my desktop yesterday):
VS: 15.4.1, Framework: 4.7.02556
Context menu options showed up ONLY after opening the Test > Windows > Test Explorer. I don't recall if I checked after opening it yesterday.

Just updated to VS 15.4.2:
Context menu items are showing without having to open Test Explorer. I think they fixed it. :)

**Comment by OsirisTerje** [comment]
Cool!  Nice to hear!

**Comment by rprouse** [comment]
I've noticed that test exploration doesn't happen unless the test explorer window is open. That's likely the cause.
