### ISSUE TITLE
Test result is Skipped when an exception has been thrown and the only warning is in TearDown

### ISSUE THREAD

**Issue by nfink** [nunit/nunit3-vs-adapter#419]
The VS test adapter reports a test result as Skipped instead of Failed under the following circumstances:
 - An exception was thrown during the test (not an assertion failure, but an actual exception).
 - A warning has been asserted in the TearDown of the test.
 - No warnings have been asserted prior to the exception being thrown.

That means that for example, code with the following is reported as Failed:
(Setup): Assert.Warn("...")
(Test): throw new Exception()
(TearDown): Assert.Warn("...")

But the following is reported as Skipped:
(Test): throw new Exception()
(TearDown): Assert.Warn("...")

The attached screenshots show the discrepancy in results between the test adapter and the console runner. The gist linked below has the code that was run.

* NUnit and NUnit3TestAdapter versions: NUnit 3.9.0, NUnit3TestAdapter 3.9.0
* Visual Studio edition and full version number: VS Professional 2015 v14.0.25424.00 Update 3
* A short repro, preferably attached or pointing to a git repo or gist: https://gist.github.com/nfink/ed40e164ce8966bb40df59e6397b852e
* What .net platform and version is being targeted: .NET Framework 4.5.2

![nunittestadapter](https://user-images.githubusercontent.com/10527639/33089820-de932848-cebf-11e7-9d7f-771cc616d1cb.png)
![nunitconsole](https://user-images.githubusercontent.com/10527639/33089839-e90f3b4a-cebf-11e7-877d-2a3d60a47315.png)

**Comment by OsirisTerje** [comment]
Thanks @nfink , I'll have a look

**Comment by OsirisTerje** [comment]
It seems this bug comes from NUnit itself.  I haven't checked the console yet, but I would assume the adapter and the console interpret the results differently.

The adapter looks at the assertions reported.  
For the code given as:
(Setup): Assert.Warn("...")
(Test): throw new Exception()
(TearDown): Assert.Warn("...")
we get the following back from NUnit:
![image](https://user-images.githubusercontent.com/203432/33225881-8cdc14b0-d180-11e7-9aae-4e9b23b1cc47.png)
This seems to be as it should, but when we look at the other, that goes:
(Test): throw new Exception()
(TearDown): Assert.Warn("...")
we get only the teardown warning, the exception is now *not* reported as an assertion error.
![image](https://user-images.githubusercontent.com/203432/33225892-c28420d0-d180-11e7-949c-1d915c5319b3.png)

If we remove the teardown, the Test2 fails, it still has no assertion in the results, but it now looks at the test result instead (legacy xml interpretation) and that is failed. Comparing this with the Test4, aslo without the teardown, it has a sequence of a warning and an exception , and that also comes out with two assertions in that case, the latter an error. 


@rprouse , @CharliePoole Can one of you have a look and see if this is a NUnit bug ?
If the xml is as expected we need to interpret the results differently. 

I've enclosed the NUnit xml dumpfile from the adapter.  I've changed the method names to have TF1_ and TF2_ as suffixes to keep them better separated.

[E_ClassLibrary19.dll.zip](https://github.com/nunit/nunit3-vs-adapter/files/1502709/E_ClassLibrary19.dll.zip)

**Comment by CharliePoole** [comment]
@OsirisTerje The XML looks right to me. The test clearly shows up as Failed and all the assertions are correctly listed. You say "The adapter looks at the assertions reported...", which is surprising to me. Unfortunately, I can't look at the code today as I'm on a guided excursion in Salento, but I can check further tomorrow or the next day if you need me to. My impression - or memory from when I was working on it - is that the adapter only looks at the result reported from the framework to decide on the outcome of the TestCase. Is this changed in the current build?

**Comment by OsirisTerje** [comment]
This part of the code has been unchanged for a year.  

About the xml looking correct:  How can an exception in a test be reported as an assertion if there are  warnings both in the setup and teardown, and not when there is no setup and teardown?   It doesn't look consistent to me, but I might be missing something here. 

We report back based on the assertions first, if there are no assertions, we report on the test result, using the legacy xml method.  
The assertions are added to a list of outcomes, and the *first found* is reported back in the RecordEnd call, the rest are reported as RecordResult (not sure if this sequence really matters, it seems to come in to TE correct anyway)

The code in question here is:
![image](https://user-images.githubusercontent.com/203432/33229515-92fe4af2-d1d0-11e7-9ad1-3d61a47f89be.png)

If we have assertions, we retrieve the result of the testcase in (1).  Then  we overwrite that result with the assertion result in (2).  
If we don't have any assertions we get the testcase result in (2) and add that. 
To me it looks like this code assumes that the results are all in the assertions, and that (3) is a kind of catch if we don't find any for some reason. 
Since the framework doesn't report assertions in the case with only an exception, it takes the result from (3).  But when just a teardown is inserted, there is but one assertion, and that is a warning, which translates to skipped.  When both the setup and teardown are present, there are 3 assertions, and the exception is an error which translates to a failed. 

I have enclosed a new file with better names to make this more clear, and the code for the upload is here (note branch NUnit3 if you clone it):  https://github.com/OsirisTerje/NUnit.Issues/tree/NUnit3/issue-419/Issue-419   
[E_ClassLibrary19.dll.zip](https://github.com/nunit/nunit3-vs-adapter/files/1503068/E_ClassLibrary19.dll.zip)

So the questions then are:  
1) To me it looks like NUnit returns data for assertions differently for different cases.  This must be an NUnit error.  
2) The adapter should be able to handle different NUnit versions, so it should probably have a fallback mechanism to handle wrong results.

**Comment by CharliePoole** [comment]
@OsirisTerje I think you are right. The code - even though I wrote it - seems strange to me. Why do we give preference to the __first__ assertion found? Maybe it worked at one time or maybe we have a use case here we did not envision.

Note that we do not return an assertion result for an exception thrown in the user code, but we do if an exception or error occurs in an assertion.

The key seems to be that the result reported to VS in RecordEnd should be the __worst__ of all the results. The framework has already recorded this in the result of the test itself so we should probably use it rather than re-calculating it.

However, I see an unintended change that is messing us up in the framework. Historically, __any__ assertion failure in a teardown was treated as an unexpected exception. For example, `Assert.Fail` has always been an error because you are not supposed to put assertions in your TearDown! It's possible that we violated this in implementing Warnings or that it has been changed at some other point. I'm not sure how we want to treat this. In theory, a __successful__ test with a warning in TearDown should really be a failure in order to be consistent with past practice. I suspect people might not like that, however.

**Comment by OsirisTerje** [comment]
@CharliePoole Can it be related to the implementation of Multiple asserts?   I see also that  in the dumplog the asserts in the setup/teardowns comes down as multiple assert failures. 
![image](https://user-images.githubusercontent.com/203432/33233658-a9037248-d219-11e7-9ab6-be810359f94b.png)

Anyway, I'll set up some unit tests to cover the different cases we have and start fixing it up.

**Comment by CharliePoole** [comment]
A bit of history... I added support for warnings 11 months ago and for multiple asserts 10 months ago. I think the multiple assert change is what broke things because none of the tests took into account that you might have warnings __and__ assert failures nor did they allow for errors in `SetUp` or `TearDown`d. The latter is understandable, because we never supported assertions in `TearDown`.

I'm going to take a look at this in the framework itself, first to see whether this situation is thoroughly tested there and then to see if a change is needed.

**Comment by CharliePoole** [comment]
I verified that the framework is not testing:
* Warnings in SetUp
* Warnings in TearDown
* Mixed Warnings, Failures and Errors

☹️

**Comment by CharliePoole** [comment]
Created issue nunit/nunit#2577

**Comment by CharliePoole** [comment]
Even though there is an NUnit bug, I think that the adapter should still be providing VS with the test outcome as determined by the framework, not deciding for itself.

**Comment by OsirisTerje** [comment]
Yes, but as discussed above, it should honour the result of the test, as reported by the framework.  That means if the assertions are not failing, and the test is, we need to add the failing result.

**Comment by CharliePoole** [comment]
The issue I created focuses purely on Warning processing. Since we need a policy decision on it, I'd like to get it straight before working on how warnings interact with exceptions. I think the decision will influence what we do next. I hope you will weigh in on the choices.

**Comment by OsirisTerje** [comment]
@nfink  Can you confirm this is working for you now, using the latest adapter from here:  https://www.myget.org/feed/nunit/package/nuget/NUnit3TestAdapter

**Comment by Weiman74** [comment]
@OsirisTerje Tests are still reported as **skipped** when the only assert is a warning. See screenshot, this makes absolutely no sense to me!

![image](https://user-images.githubusercontent.com/45255192/79335795-e7098d80-7f22-11ea-9493-382d86e8d36d.png)

**Comment by CharliePoole** [comment]
That makes sense because the overall test result is supposed to be the "worst" of the individual results. If there is only one individual test and it's skipped, then the run is skipped.

For it to be otherwise, the adapter would have to be fixed to retain knowledge of the composition of the skipped tests, i.e. how many were actually skipped and how many were warnings. If all of them were warnings, you could make the run pass.

However, I can't imagine why you would want to do that. If there are warnings, then there are warnings. The Symbol used for skipped tests in VS is a very nice warning symbol. The adapter makes use of it for both Ignored tests (which is a subtype of warnings) and Warnings per se. Why use warnings at all if you don't want them reported?

Possibly, some future test framework could offer two types of warnings. One would mean "It passed, but there was a small problem" and the other would mean "It failed, but not too badly." NUnit comes from a tradition of unit testing that declares anything except perfect success is failure, which is why Ignore, for example, is treated as a "Bad Thing."

**Comment by CharliePoole** [comment]
@OsirisTerje Have you considered a setting that allows the adapter to treat warnings in various ways, as the user decides? Could be success, failure, skipped, not run, etc.

**Comment by Weiman74** [comment]
But the test is not skipped! It is executed albeit with a warning. Why it should be marked as skipped is beyond me. That is what Assert.Ignore() is for!

**Comment by OsirisTerje** [comment]
@CharliePoole Interesting idea!  And very easy to do.  But....  do many people really use Warnings?  And then how many would like to change the way it is mapped ?

@Weiman74 NUnit have more outcomes than Test Explorer, so we map them to the nearest - meaning "making sense" state.  

This is the possible Test Explorer outcomes:
 public enum TestOutcome
  {
    None,
    Passed,
    Failed,
    Skipped,
    NotFound,
  }
This is the NUnit outcomes
public enum ResultType
        {
            Failed,
            Success,
            Skipped,
            Warning,
            NoIdea
        }
And this is the current mapping:
switch (resultNode.Result())
            {
                case NUnitTestEvent.ResultType.Success:
                    return TestOutcome.Passed;
                case NUnitTestEvent.ResultType.Failed:
                    return TestOutcome.Failed;
                case NUnitTestEvent.ResultType.Skipped:
                    return resultNode.IsIgnored ? TestOutcome.Skipped : TestOutcome.None;
                case NUnitTestEvent.ResultType.Warning:
                    return TestOutcome.Skipped;
                default:
                    return TestOutcome.None;
            }

And you're correct that the test **is** run when it has a Warning.  That is correct NUnit behaviour. 
Note that if it fails, you will get a message saying there are:
 Message: 
    Multiple failures or warnings in test:
      1) warn
      2)   Expected: True
      But was:  False

But, then - what could we map it into?   Skipped looked like the one most close.  

The Test Explorer is missing a good match for Warnings.....  

Suggestions appreciated :-)

**Comment by CharliePoole** [comment]
@OsirisTerje We really expected that MS would add Warnings, but they never did! That being the case, I suspect that many people do not use warnings because TestExplorer doesn't support them.

In general the idea of a warning is that it's something bad but not bad enough for the test case to fail. However, we don't really specify whether it's bad enough for the fixture or the entire run to fail.

When I added warnings, I considered adding two types: `Failed:Warning` and `Passed:Warning`. Of course, that would be even move kinds of Outcomes but in this case it would be helpful because it would have told us how to map the warning.

@Weiman74 The fundamental problem is that NUnit Outcomes are extensible, at least in principle, so how do you map a possibly infinite set of outcomes to a fixed set? :smiley_cat:

**Comment by Weiman74** [comment]
I understand there is no 1:1 mapping but "warning" and "skipped" are not even close. Either failure _or_ success would be better!

We have started using Appium/WinAppDriver for UI tests and I added Assert.Warn() in the teardown for e.g. failure to take a screenshot or if our app logged a non-fatal error. No problem when I tested locally, but when some warning triggered in the Devops pipeline the test came up as "Not executed" and that was extremely confusing. There is no indication anywhere that the warning is the culprit. 
![image](https://user-images.githubusercontent.com/45255192/79449204-1aabec80-7fe3-11ea-81ec-40d569cca21d.png)

**Comment by CharliePoole** [comment]
Note that NUnit itself has never supported use of assertions in TearDown.

**Comment by OsirisTerje** [comment]
I  agree with a policy on asserts in Teardowns.  However, the issue that a Warning maps to Skipped, is actual for any place where a warning appears, also in normal tests.  
To me, given the options we have, mapping it to Success doesn't really make any sense, as it will not be visible at all.  Mapping it to failed make more sense, but again, then you could just use any ordinary asserts. So mapping it to Skipped or None are the two remaining options that make sense.  

However, we could allow the user the freedom of mapping it to anything he chooses, the default being Skipped (so we don't break anything backwards).

So, I'll add a new issue on just this thing, #740

**Comment by CharliePoole** [comment]
FYI, in the console runner, the only real difference between a run that has a warning and a run with a failure is the return code. In the GUI, you also have the color of the top node and the progress bar.
