### ISSUE TITLE
Option TargetFrameworkVersion does not work.

### ISSUE THREAD

**Issue by AndreyNNN** [nunit/nunit3-vs-adapter#427]
VisualStudio 2017 update 15.5.1. .NET 2.0 and 3.5 tests run on CLR 4.0 instead of CLR 2.0.

NUnit.3.8.1
NUnit3TestAdapter 3.9.0
VisualStudio Community Edition 2017 update 15.5.1.
Project targets .net 3.5 (it works as workaround for VisualStudio 2017 update 15.4.4)

 I think the requirement that .NET 2.0/3.5 tests should run on CLR 2.0 is very basic.

**Comment by rprouse** [comment]
Nothing has changed in the adapter between 15.4 and 15.5 and it is Visual Studio/VSTest that spawns the adapter under the 2.0/3.5 runtime, so that is not under our control. There have been a number of test related issues with the 15.5 release. We are meeting with the test team later today, so I will add this to the list of topics to discuss.

**Comment by AndreyNNN** [comment]
Thank you. I thought that TargetFrameworkVersion option from .runsettings will be taken in account upon tests running on your side.

**Comment by CharliePoole** [comment]
@AndreyNNN Other NUnit runners, such as the console runner, start a process in which to run the tests. Those runners are therefore capable of using a specified framework for the tests. The adapter, however, currently runs in the process created for it by VS.

**Comment by rprouse** [comment]
I talked with the Visual Studio team today and the latest versions of VSTest which runs the tests no longer ships a .NET 3.5 version of the runner. If your tests request to be run in older frameworks, they will run it those tests in the current CLR with compatibility mode set to the version of the framework you request.

I am going to close this because it is not an NUnit issue. We have no control over it. As @CharliePoole says, if you run your tests in the NUnit console, we will continue to respect the target framework, but we cannot change the way Visual Studio or their test runner works.

Out of curiosity, are there specific framework behaviors that you believe would change the outcome of your tests if they are run in the newer CLR using compatibility mode? I am asking because the other test frameworks have decided to no longer release runners for older frameworks and force you to compile your tests in a recent framework. Other than a few compatibility edge cases, I don't see a huge downside to that approach. You are clearly using older frameworks, so I would like to understand your perspective.
