### ISSUE TITLE
some tests are not discovered by Adapter3

### ISSUE THREAD

**Issue by tfeloy** [nunit/nunit3-vs-adapter#433]
Hello everyone, 
I have a test class that inherits another class that uses Spring.Testing.NUnit and Spring.Data.NHibernate to perform transactions from the database. 
The nunit 3 adapter does not show these tests and I can not run them.

The structure looks like this:
----------------------------------------------------------------------------
using NHibernate;
using Spring.Testing.NUnit;
//etc
namespace Dir.Test
{
    public class HibernateTestBase : AbstractTransactionalSpringContextTests
    {

	//code here (not test)
   }
}

--------------------------------------------------------------------------------------------
using NUnit.Framework;
// etc
namespace Dir.Test.DB
{
    [TestFixture]
    public class TestUserDB : HibernateTestBase
    {

	//tests code here
    }
}

I searched intensely for the solution and reviewed the configuration of the project, but I can not find the answer. Does anyone know what could be happening?

i'm working with nunit v3.9.0, NUnit3TestAdapter v3.9.0, nunit.framework v2.63.0 and Spring.Testing.NUnit v2.0.1.

Thanks!!

**Comment by CharliePoole** [comment]
Are you using nunit 3.9 or nunit  2.6.3? It's not possible to use both frameworks as you seem to be saying.

You must use the version supported by Spring.Testing.NUnit if course. If that's nunit 2, then you have to run using the nunit 2 adapter.

**Comment by CharliePoole** [comment]
From checking the source on github, I found that
 * The Spring.Testing.NUnit nuget package has a dependency on NUnit 2.5.7. 
 * OTOH, the commit comments indicate that NUnit 3.5 is supported.

This is a bit confusing, I suggest you get some clarification from the spring folks as to what version of NUnit you should use with 2.0.1. 

Note that nuget dependencies default to greater than or equal. However, it seems highly unlikely that anybody could be supporting 2.5.7 through 3.9.0 in one package, since 3.0 was a complete rewrite of the framework.

Note also that you can't be loading two different versions of nunit.framework.dll. So if the spring testing is referencing a particular version and that gets loaded, that's the one you will get.

To figure out what versions are actually being used, just examine the versions of the nunit assemblies that are copied to your output directory.

**Comment by OsirisTerje** [comment]
Not confirmed, so assume this is ok now.  Please reopen if still an issue
