### ISSUE TITLE
How to write line the passed unit tests name on output windows?

### ISSUE THREAD

**Issue by AudreyHui** [nunit/nunit3-vs-adapter#436]
now we have about 800 NUnit tests, I want to print all nunit tests full name, test results and execute the nunit test required time in output windows, I found we can print the [Ignore] and [Failed]
 unit test, but for passed unit test, we can't do it.
would you have any idea, please give me a help. thanks!
![capture](https://user-images.githubusercontent.com/34882203/35162271-c4de462a-fd7d-11e7-83e3-0f427a9646e0.PNG)

such as the below:
Passed    Nunit.TestName  0.002s.

**Comment by CharliePoole** [comment]
You filed this issue against the NUnit 3 Visual Studio adapter but the sample output is from the NUnit 2.5.9 console runner. In order for us to move this issue to the proper repository and team, please clarify exactly what NUnit software you are using, both in terms of the framework and the runner.

**Comment by AudreyHui** [comment]
Thanks for your reply, sorry for this, NUnit version is 2.5.9.10384, and also I didn't use the NUnit3 Visual Studio adapter, I want print the full name and test result in this version.

**Comment by CharliePoole** [comment]
@AudreyHui Since it's an old version we no longer work on, I'm going to treat this as a question and answer it right here rather than move it to the console runner repository, where it would go if we were actually going to fix it.

The NUnit V2 console runner doesn't provide any way to display the information you want. Using the --labels option, you can get a list of the names of all the tests run, but not the result of the test. However, it does leave behind the complete result report in the form of an XML file. You can use XSLT, C# or any other language to reformat that information in to the report you want. You would have to run the report generation program after the console runner, taking the XML result file as input.

There are various programs available for reformatting reports from the NUnit XML output and most of them work with the NUnit V2 format rather than NUnit 3, so you're in luck there. Google for "nunit report generator"

**Comment by CharliePoole** [comment]
Although I closed this issue, you can still post any follow-up questions you have. We'll see them and respond.
