### ISSUE TITLE
NUnit3TestAdapter 3.9.0 & NUnit 3.9.0 lead to discover test failed

### ISSUE THREAD

**Issue by rosergeev** [nunit/nunit3-vs-adapter#442]
NUnit version: v3.9.0
NUnit3TestAdapter: v3.9.0
VS Enterprise 2017 Version 15.5.4
.Net framework 4.6.1
![nunit3ta_issue_1](https://user-images.githubusercontent.com/12766193/35615430-29ee35d0-0683-11e8-913d-275496484c59.png)
![nunit3ta_issue_2](https://user-images.githubusercontent.com/12766193/35615431-2a09cbce-0683-11e8-8a3e-ad318b26708f.png)

[NUnit3TestAdapterIssue.zip](https://github.com/nunit/nunit3-vs-adapter/files/1681116/NUnit3TestAdapterIssue.zip)

NUnit3TestAdapter can't discover tests

**Comment by OsirisTerje** [comment]
Hi!  Did you send over the right repro?  Because your error message indicates .netcore, but your repro contains .net 461, and the repro works as it should:
![image](https://user-images.githubusercontent.com/203432/35618245-aa5ac386-067a-11e8-996f-a0809963956e.png)
![image](https://user-images.githubusercontent.com/203432/35618255-ae5c67be-067a-11e8-8725-98abaaed0823.png)


Also, please check the documentation we have on testing with .net core,  see https://github.com/nunit/docs/wiki/.NET-Core-and-.NET-Standard  and http://hermit.no/net-core-setup/.  

You might also have the cache issue mentioned at the bottom of this post http://hermit.no/how-to-resolve-cases-of-visual-studio-no-tests-appearing/,  which also contains info on other issues you might have.

**Comment by rosergeev** [comment]
Hi, I send repo which targets to .net framework 4.6.1, but yes error is about .net core. It's reproducible on my development virtual machine environment, but is not reproduced in my local environment. This helped to solve a problem: https://stackoverflow.com/questions/48526149/how-to-fix-could-not-load-file-or-assembly-nunit-engine-version-3-7-0-0

**Comment by OsirisTerje** [comment]
Cool!   Yes, that is correct, that fix is the same I referred to as the "cache issue".  
Then I'll close this one.

**Comment by rosergeev** [comment]
Thank you!

**Comment by rprouse** [comment]
@OsirisTerje have you brought this issue up with the VSTest team? It seems to be happening very frequently with the latest releases of VS.

**Comment by OsirisTerje** [comment]
Yes, I did a bit back, when we started to observe this.  I'll follow it up.
