### ISSUE TITLE
Proposal: Eliminate excess whitespace in test results area (if possible)

### ISSUE THREAD

**Issue by ericnewton76** [nunit/nunit3-vs-adapter#466]
Proposing elimination of the vertical whitespace from test results area in Test Explorer, if possible.  

I'm guessing this might not be possible because the Test Explorer window layout is governed by internal Visual Studio code?

* NUnit v3 and NUnit3TestAdapter 
* Visual Studio 2015, v14.0.25431.01 Update 3

(will upload explanation image when underlying Amazon S3 issues are resolved)
https://imgur.com/a/t87IA

**Comment by rprouse** [comment]
Good idea, but you will need to submit the issue to the Visual Studio team. As you say, the window is entirely controlled by Visual Studio. The NUnit adapter runs in a separate process and only handles the discovery, running and reporting of tests, Visual Studio handles all UI and the UI is the same for all test adapters.

The VS team is actively working in this area though, so the idea might get traction on UserVoice. The upcoming 15.6 release of Visual Studio 2017 has a revamped test explorer window with hierarchical tests. You can download it now in preview.

Since there is nothing we can do, I am going to close this.
