### ISSUE TITLE
Debugging parallel tests

### ISSUE THREAD

**Issue by Dispersia** [nunit/nunit3-vs-adapter#483]
When reporting a bug, please provide the following information to speed up triage:

* Nunit 3.9.0, NUnit3TestAdapter 3.10
* Visual Studio 2017 Enterprise
* .Net Framework

Repro: https://gist.github.com/Dispersia/7a1d5a8488efcca23c68957a668480ab

 ^ Obviously not a real test, assumed if breakpointing on the assert that Total would be all, or the next breakpoint would have them all set already.

 Attached a quick repro, and this might be solved already.
I see under:
https://groups.google.com/forum/#!topic/nunit-discuss/X3z2kMac04U

that this issue was created:
https://github.com/nunit/nunit3-vs-adapter/issues/92

which says fixed by:
https://github.com/nunit/nunit3-vs-adapter/issues/49

 But I don't see where you can specify how to debug tests in parallel. I get a throw that only happens when tests are run in parallel and not sequentially, and I see I can use the runner and just attach to that, was just seeing if the adapter had a better way to do it now.

**Comment by CharliePoole** [comment]
When you debug tests from the VS adapter, all parallelism is turned off automatically. Otherwise, it becomes very difficult to do normal debugging. Attaching to the console runner gives more ability in a case like yours.

**Comment by Dispersia** [comment]
How so? I saw the comment that users saw it skipping around everywhere, but doesn't it work the same as normalulti threading? Just open the thread window, stop all unit test threads besides one you want to debug, then continue as wanted. Is there more to it than that?

**Comment by CharliePoole** [comment]
Nope, no more to it than that, except that the user has to know which of our threads to stop. It was still complicated enough that we got a request to suppress parallel execution of tests when debugging and we did it. Note that this has nothing to do with __user__ initiated parallel threads. They continue as always. We just don't launch tests in parallel when you are debugging the tests.

**Comment by CharliePoole** [comment]
@Dispersia If you think it should work differently now, feel free to make your case to @OsirisTerje. 

Frankly, when I wrote the first adapter, I thought of it as something to be used by beginners, who wanted everything to show up in the single IDE. I still don't use it myself, unless I'm actually fixing it. So there's a good chance that I'm out of step with how it's currently used.

**Comment by wxdave** [comment]
@Dispersia you can hit breakpoints during parallel execution using NUnit console runner.

Just set the breakpoints in VS, build your assembly, then execute tests using the console runner with the debug option.

`>packages\NUnit.ConsoleRunner.3.9.0\tools\nunit3-console.exe <path-to-assembly> <options> --workers=10 --debug`

**Comment by CharliePoole** [comment]
Although this issue is closed, it's an interesting discussion point. What us it reasonable to expect a "typical" developer to do, where the definition of typical varies from team to team?

Debug a single test?

Realize that a certain test can't run in parallel with others?

Understand why a certain test can't run in parallel?

Fix tests so they may run in parallel?

I think it's a set of decisions each team has to make.

**Comment by itaibh** [comment]
I think that if developers don't want to debug tests in parallel they should just uncheck the "run tests in parallel" checkbox. I mean, that's the reason it is there, isn't it? To be able to toggle between running tests in parallel and running tests sequentially. Debugging test should not ignore that toggle, or at least there should be a way to select if it should disable parallelism or not.

The problem I'm having is trying to figure out the state of the threads after a while, or more precisely what data each object have when I pause execution. The class holds several lists that should be synchronized while tests run in parallel. When they run sequentially, the problem I'm trying to pinpoint just doesn't happen.

**Comment by CharliePoole** [comment]
In my own comments on this thread, I was thinking of the parallelism that is controlled by NUnit, based on attributes in the code, not that controlled by the Test Explorer. To be honest, I'm not entirely clear what Test Explorer does when you check that box! @OsirisTerje can you explain?

Situations like you describe are difficult to handle in any case, but to debug a case like yours, I would do two things: 1) Run in the console runner as already suggested 2) Do a lot of logging.

**Comment by OsirisTerje** [comment]
@CharliePoole @itaibh The checkbox in Test Explorer only controls the VSTest parallell execution, which as you point out, only runs assemblies in parallel.  This has nothing to do with the NUnit parallel mechanism, which needs to be controlled through [NumberOfTestWorkers](https://github.com/nunit/docs/wiki/Tips-And-Tricks#NumberOfTestWorkers) property in the runsettings file - if not done in code.

**Comment by CharliePoole** [comment]
@OsirisTerje @itaibh Clarifying (even though Terje knows this already)... NumberOfTestWorkers can't turn on parallelism if the attributes in the code don't call for it. The setting can only limit parallelism or turn it off. The reason for this is that the author of the tests, when using `ParallelizableAttribute` is promising that it is __safe__ to run them in parallel. Without that promise, we don't even want to try.

OTOH, we generally assume that it is safe to run tests in one assembly in parallel with (usually) unrelated tests in another assembly.

@OsirisTerje IIRC, the default of -1 is merely used in the code to indicate that __no__ setting was specified. The actual value we usually use in the framework is 0, although it's possible that <0 works as well. A value of 0 (rather than 1) causes the framework to use an entirely different legacy dispatcher, which is completely incapable of parallelism. That makes it the safest setting when one is not sure whether the tests can run in parallel.

If you use a setting of 1, you get the parallel dispatcher and all its overhead but only one queue. No parallelism occurs with one exception: a test in the MTA might run in parallel with a test in the STA.

Frankly, if I had it all to do over (as I may soon) I would simplify all this. The non-parallel dispatcher was intended as a fallback when I was developing the parallel dispatcher.

**Comment by OsirisTerje** [comment]
@CharliePoole  Thanks for that last clarification, I wa snot aware of those dispatchers.   I think what you write above (both sections) should be included in the docs for parallel running.
