### ISSUE TITLE
Running test dll in a different folder than the test project folder

### ISSUE THREAD

**Issue by Wain123** [nunit/nunit3-vs-adapter#575]
I have a project called `StandardTest` which contains tests and is located in some folder `Projects\StandardTest\StandardTest.csproj`. If I run one of those tests and call `Assembly.GetExecutingAssembly().Location`, it returns `Projects\StandardTest\bin\Debug\StandardTest.dll`.

My solution also contains a second project called `CustomTest`, which has a reference to `StandardTest` and is located in `Projects\CustomTest\CustomTest.csproj`. When I compile `CustomTest`, the folder `Projects\CustomTest\bin\Debug\` contains both `CustomTest.dll` and `StandardTest.dll`.

I would like to run the tests defined in `StandardTest` using the dll located in `Projects\CustomTest\bin\Debug\StandardTest.dll`. I can easily do this with the console runner, but not with the Visual Studio runner. I need VS in order to debug my tests, so I'm looking for a way to do this using VS. Is it possible?

**Comment by OsirisTerje** [comment]
Hi!  I am not quite sure why you would need to do that, since the dll's would be the same, but I assume you have your reasons :-)  What you can do is to use a runsettings file, see https://github.com/nunit/docs/wiki/Tips-And-Tricks for details, and use the WorkDirectory property.  That should do the trick.

**Comment by Wain123** [comment]
I need this because I search the contents of the folder at runtime.

WorkDirectory doesn't seem to help, I'm not sure if I'm using it wrong since https://github.com/nunit/docs/wiki/Tips-And-Tricks doesn't document it very precisely.
`<WorkDirectory>D:\Projects\CustomTest\bin\Debug</WorkDirectory>`

However, BasePath does exactly what I want, so thanks for pushing me to look in the right direction :)
`<BasePath>D:\Projects\CustomTest\bin\Debug</BasePath>`

**Comment by OsirisTerje** [comment]
Ok, cool, then you're unblock.  @CharliePoole You know these settings best,  we should add on the documentation here.  In the console, I see the basepath is said to be not supported anymore, but  it works for @Wain123.  The changes are here:   https://github.com/nunit/docs/wiki/Breaking-Changes

**Comment by CharliePoole** [comment]
First let's dispose of `TestContext.WorkDirectory`. In NUnit, unfortunately, this has a specific meaning: the directory where work files and reports are created by default. This is __not__ the current working directory and the name was probably a bad choice. User sets work directory to tell NUnit where to put stuff like the XML or any text output. User may also access it in the code and save other things there. Think of it as the directory for saving stuff. :smile: 

NUnit also supports `TestContext.TestDirectory`, which is the directory where the current test assembly is located. Note that if you have several test assemblies in different directories, the value will be different when each one of them accesses it. Note also that there is no way you can __set__ the `TestDirectory` because it's always where the assembly is located.

The BasePath is a .NET thing. It's the base directory where assemblies are searched for. You can also have subdirectories listed in the PrivateBinPath. NUnit take scare of all this automatically now, so the old console options are no longer supported. For finding things you want to read at runtime, the TestDirectory and the BasePath will usually be the same thing.

@Wain123 If I missed anything you need to know, please ask.

**Comment by OsirisTerje** [comment]
Thanks @CharliePoole .  I am adding your comments here to the relevant items in https://github.com/nunit/docs/wiki/Tips-And-Tricks, which lists the options for the adapter (Should probable be a different name on that page, but will do that later)

**Comment by Wain123** [comment]
Thanks!

I encountered a slight issue while using the BasePath in this way: If I use the ValuesAttribute to specify 2 possible parameter values for a test, the VS test explorer doesn't show me the parameter values after I build my solution. It only shows the name of the test and displays it as 1 test. After I run the test, it's displayed properly as 2 tests with different parameter values.

If I'm not using BasePath, the test is displayed as 2 tests with different parameter values as soon as I build the solution.

This is a very minor issue and I can live with it, but I thought I should say it in case that's not the intended behavior.
