### ISSUE TITLE
Modifications to test parameters are ignored when using BasePath

### ISSUE THREAD

**Issue by Wain123** [nunit/nunit3-vs-adapter#577]
I'm using BasePath as discussed in #575.

I have a project called `StandardTest` which is located in the folder `Projects\StandardTest\StandardTest.csproj`. My solution also contains a project called `CustomTest`, which has a reference to `StandardTest` and is located in `Projects\CustomTest\CustomTest.csproj`. When I compile `CustomTest`, the folder `Projects\CustomTest\bin\Debug\` contains both `CustomTest.dll` and `StandardTest.dll`.

I have a runsettings file with the contents:
```
<RunSettings>
  <NUnit>
    <BasePath>D:\Projects\CustomTest\bin\Debug</BasePath>
  </NUnit>
</RunSettings>
```

In the `StandardTest` project, I have a class `Demo`:
```C#
[TestFixture]
public class Demo {
	[Test]
	public void EmptyTest([Values(true, false)]bool b) {
	}
}
```
I click "Rebuild Solution", and the Test Explorer shows two tests: `EmptyTest(false)` and `EmptyTest(true)`. Afterwards, I modify the test and remove the parameter b:
```C#
[TestFixture]
public class Demo {
	[Test]
	public void EmptyTest() {
	}
}
```
I save the file, but I do *not* click "Rebuild Solution". I right-click on `EmptyTest(true)` and click "Run Selected Tests".

What I expect to happen: `EmptyTest(true)` disappears from the Test Explorer.

What actually happens: I see a green tick next to `EmptyTest(true)`.

If I do the same thing without using a runsettings file, I get the expected behavior.

NUnit 3.11.0
NUnit3TestAdapter 3.11.2
Visual Studio 2017 15.8.6
.NET Framework 4.7

**Comment by OsirisTerje** [comment]
Do you have source based discovery turned on ?

**Comment by Wain123** [comment]
Do you mean the "Discover tests in real time from source files" option? I have that turned on. I tried turning it off, and the behavior is still the same.

**Comment by OsirisTerje** [comment]
@jnm2  Can you have a look at this?

**Comment by jnm2** [comment]
I can repro with VS 15.9.7.

**Comment by jnm2** [comment]
I can tell by stepping through the adapter code (@OsirisTerje I really love that we ship the PDB!) that VSTest is telling the adapter to run the test for the correct assembly file, StandardTest.

![image](https://user-images.githubusercontent.com/8040367/53060096-3b33f180-3487-11e9-9851-225b528d17f1.png)

**Comment by jnm2** [comment]
@Wain123 Here's what's happening. `<BasePath>` causes the NUnit engine to set the AppDomain ApplicationBase to the CustomTest folder. ([Link 1](https://github.com/nunit/nunit-console/blob/02bca31aef55629a0c235791f9810cc6bf3d3666/src/NUnitEngine/nunit.engine/Services/DomainManager.cs#L107-L108), [link 2](https://github.com/nunit/nunit-console/blob/02bca31aef55629a0c235791f9810cc6bf3d3666/src/NUnitEngine/nunit.engine/Services/DomainManager.cs#L218))

Then, the NUnit framework always disregards the assembly path by doing `Assembly.Load(Path.GetFileName(...))`. ([Link 3](https://github.com/nunit/nunit/blob/70fb2913b744621749fcff0c8132064f314aac54/src/NUnitFramework/framework/Internal/AssemblyHelper.cs#L178))

Therefore, this is a bug that must be fixed in the https://github.com/nunit/nunit repository. We need to move this issue there.

GitHub's issue transfer beta is currently dumb. It requires me to be an admin in both repositories in order to move the issue. See https://help.github.com/articles/transferring-an-issue-to-another-repository/. I think the only person that's admin of both repositories is @CharliePoole. (Does anyone still have ZenHub these days?)
