### ISSUE TITLE
TestCase with enclosed double quotes error

### ISSUE THREAD

**Issue by eberzosa** [nunit/nunit3-vs-adapter#582]
A TestCase with a double quote generates the following error:
> An exception occurred while invoking executor 'executor://nunit3testexecutor/': Incorrect format for TestCaseFilter Error: Missing '('. Specify the correct format and try again. Note that the incorrect format can lead to no test getting executed.

Replacing the \" with any other char will make the error disappear.

* NUnit 3.11.0, NUnit3TestAdapter 3.12.0
* Visual Studio Enterprise 2017 15.9.4
* Net 4.6.1

```csharp
   public class Test
   {
      [TestCase("(c\\\\c)", "")]
      [TestCase("aaa(c\\\\c)bbb", "aaa bbb")]
      [TestCase("aaa (c\\\\c) bbb", "aaa bbb")]
      [TestCase("aaa  (c\\\\c)  bbb", "aaa bbb")]
      [TestCase("aaa\t(c\\\\c)\tbbb", "aaa\tbbb")]
      [TestCase("aaa\t\"(c\\\\c)\"\tbbb", "aaa\t\"(c\\\\c)\"\tbbb")]
      [TestCase("aaa\t\"(c\\\\c)\tbbb", "aaa\t\" bbb")]
      public void TestA(string s1, string s2)
      {

      }
   }
```

**Comment by OsirisTerje** [comment]
This is the same as other reported issues regarding handling "invalid" characters .

**Comment by ryanbowden** [comment]
We are having the same issue with having () in the test fixture. Is there a fix incoming for this?

**Comment by johnmwright** [comment]
This issue has the same underlying cause as #622 and is resolved by PR https://github.com/nunit/nunit3-vs-adapter/pull/668

**Comment by OsirisTerje** [comment]
I assumed this was the same as #622, but when trying now to repro it with the packages set here (NUnit 3.11.0, NUnit3TestAdapter 3.12.0
Visual Studio Enterprise 2017 15.9.4
Net 4.6.1). I can't repro it.  I've tried both old style csproj and new style. 
![image](https://user-images.githubusercontent.com/203432/68070085-b74a3d00-fd69-11e9-82f6-eb000f105826.png)

But since it *should* work now with 3.16.0-dev in any case, I'll close this.
