### ISSUE TITLE
Test adapter 3.0.2 fails to load DLL that worked fine under 2.0

### ISSUE THREAD

**Issue by kyace** [nunit/nunit3-vs-adapter#59]
Library that worked fine under 2.0 test adapter fails under 3.0.2.

Output: NUnit failed to load <dll>

How do you go about finding out WHY?

This is frustrating that things worked under 2.6.4 and not will not.

**Comment by rprouse** [comment]
Are your tests still referencing NUnit.Framework version 2.6.x? The version 3 adapter is for running NUnit 3.0 tests. You can install the original NUnit adapter along side the v3 adapter if you are testing older 2.6 tests and 3.0 tests. If you try to load 2.6 tests using this adapter, it will just tell you that no tests were found. NUnit 3 is an entirely new release of NUnit. While it shares most of the attribute names and looks very similar on the outside to make upgrading easy, the internals are completely rewritten and incompatible with NUnit 2.

Please be aware that NUnit 3.0 has not seen a final release and that this adapter is also considered pre-release. It does not work with the latest RC release of the framework and will be updated very soon.

**Comment by kyace** [comment]
I removed 2.x and referenced 3.x and rebuilt - The 2.x adapter in VS2015 throws out of memory - the 3.x adapter just reports that it fails to load the DLL, under VS 2013 - the 2.x adapter works and 3.x fails to load the DLL.  

Will do whatever I can to help understand this issue but need to be pointed to the right direction of understanding how to get the adapter to log more or something.

I understand I haven't provided good enough information  but don't have an idea on how to get better data for you.

**Comment by kyace** [comment]
There is an issue with the 2.0 adapter that after a number of bills on a larger test library it begins to fail to load any tests, that is why we tried going to 3.0, for now we went back to 2.0 and are using VS2013.

**Comment by CharliePoole** [comment]
@kyace There are several things you should be aware of in trying to fix or work around this issue.

1. As @rprouse indicated, NUnit 3.0 is not yet released. However, it is in the rc stage and very close to release. However, since 3.0 has a number of breaking chnages, you should thoroughly test the tests using nunit-console before relying on them ... and before even thinking about running them under the adapter. See the info on upgrading in the documentation.

2. The nunit adapter 2.0 will continue to be maintained for tests running under NUnit 2.6.4. However, if any issue goes back to NUnit 2.6.4 itself, you are out of luck, since we are not maintaining it.

3. The NUnit 3 adapter is not yet released - except as a preview - and has not been updated to work correctly past the 3.0 beta 4. A new release will come out soon.

4. You cannot run nunit 2 tests under the nunit 3 adapter or vice versa. 

You may have known all this stuff, but I wanted to  lay them out just in case.

**Comment by kyace** [comment]
Thank you - at this point this issue should be closed because it really isn't an issue if the software isn't released yet.
