### ISSUE TITLE
Allow use of FullName as the DisplayName for Converted Tests

### ISSUE THREAD

**Issue by jeffsugden** [nunit/nunit3-vs-adapter#640]
When reporting a bug, please provide the following information to speed up triage:

* NUnit and NUnit3TestAdapter versions
* Visual Studio edition and full version number (see Help About)
* A short repro, preferably attached or pointing to a git repo or gist
* What .net platform and version is being targeted
* If TFS/VSTS issue, what version, hosted, on-premises, and what build task you see this in

Referencing this issue:
https://github.com/nunit/nunit/issues/3015

We would like to include the TestFixture parameters value(s) in the TestName that gets created by the Test Adapter.  Currently the only way to change the TestName is by using the 
```
DefaultTestNamePattern
```

As noted in the referenced issue, there is not a way currently to specific the inclusion of the TestFixture parameters (when they exist).  The workaround suggested was to allow for the usage of FullName as an option in the Nunit Test Adapter.

--

**Comment by OsirisTerje** [comment]
I am not sure what the ask here really is.  I've read through the rather long discussion in nunit/nunit#3015 but are not quite sure what the ask is. 
@jnm2 Can you elaborate here?

PS:  Real FQNs are coming, once MS has their spec ready.

**Comment by CharliePoole** [comment]
@OsirisTerje I'm posting to suggest you re-open this issue, unless you believe that nothing can be done about the problem. I see it was closed due to lack of info from the OP so I'm going to try to provide that info based on issue nunit/nunit#3015.

Here's an extract from my last comment on that issue, where I try to summarize the problem

> 1. NUnit gives tests a `Name` and a `FullName`. The `FullName` incorporates the constructor arguments to the fixture.

> 2. Visual Studio has no knowledge of that part of the NUnit `FullName` so it does not distinguish individual fixture instances in it's display.

> 3. The NUnit 3 adapter doesn't display anything, of course. It just gives VS information to use in the  display. VS gives us a way to specify the display name of an individual test method or case, which is how we are able to show the arguments of a test __method__. It provides no way for us to give it a substitute display name for a fixture. In fact, we only provide it with information about test cases and VS deduces everything else from that.

> Consequently, I believe the adapter is at the center of the problem. It already has all the essential information from the framework but it has no useful way to pass it on to VS. @OsirisTerje  would need to work with the Microsoft guys to define some way to do that. They would need to agree to display a class name with arguments in place of the simple class name (or to display them in a hierarchy as the NUnit V2 GUI did and the TestCentric GUI now does). Only then would it be useful for the adapter to be modified.

Do you think there is any way to get VS to display something like...

- The.Namespace
  - TheFixtureName(SomeArgs)
    - AMethodName
  - TheFixtureName(DifferentArgs)
    - etc.

If it's out of the question, I think this is properly closed. If there's some chance of a change in VS to do it, I think that should be the goal and this should be re-opened with a dependenccy on that change.

**Comment by OsirisTerje** [comment]
Thanks @CharliePoole! Good points and summary!  I'll try to get another round on this :-)

**Comment by svengeance** [comment]
Running into this issue currently. We have a suite of tests for a factory-pattern-created object, where the construction of the object from the factory is expensive. In our case we don't want to test the creation of the object, but the usage of the created object. We use a parameterized TestFixture with a OneTimeSetup method to construct the object being tested from the factory (the factory uses the fixture parameter), and then have a suite of tests that call the object being created.

We would love to be able to see - in the test name - the parameters of the fixture that were consumed by the factory. I would have expected I could do something like `TestContext.CurrentContext.Test.Name = TestContext.CurrentContext.Test.Name + $"({MyFixtureParameter})";`, but it seems that's not possible.

Thank you for looking into this as you can!

**Comment by CharliePoole** [comment]
Test and Result info in the Current context is only a representation of the actual test or result. E in if you could change it, that would not affect the real test info, which is held internally by NUnit.

It's designed this way to protect the inner workings of NUnit, which makes use of the test name, id, etc.

**Comment by svengeance** [comment]
Interesting - good to know. Just to be clear @CharliePoole the scenario I described above would be covered by this Issue as the FullName actually has the parameterized fixture, correct?

**Comment by CharliePoole** [comment]
Yes, but I think it really has to be solved at the adapter level, hopefully with some support from Microsoft.It would be different if we had our own VS extension rather than just an adapter to the Test Explorer. In that case, we would actually be handling the display.

**Comment by svengeance** [comment]
If you don't mind explaining - I understand that we would like more display options from VS to help alleviate the fact that we only have one name to go on.

What's preventing the adapter from identifying test cases that belong to a parameterized Fixture, and changing the single name passed from the adapter to contain the fixture parameter?

**Comment by CharliePoole** [comment]
I guess the main problem would be that it would change behavior for everyone without some option to turn on the feature.

Beyond that, we don't know whether VS could deal with such a name, so we'd need to experiment. Test names ate arbitrary strings to NUnit, but I think VS expects them to follow a particular pattern. I'm out of date on that part, however.

@OsirisTerje Are those the main issues on your view?

**Comment by svengeance** [comment]
How much insight does the adapter have into the fixture? It could easily be nonbreaking if you do something like `[TestFixtureSource(TestNamingTemplate = {c}.{m})]`, etc, but I'm unsure how much flexibility there is there.

I'm completely guessing on this, of course. I'd be more than willing to take some time to test out what an implementation of this would look like, as well as provide a plethora of tests to ensure VS plays nicely.

**Comment by CharliePoole** [comment]
A fix that requires changing both the framework and the adapter feels a bit heavy-handed to me - more like an approach to try only if all else fails. First step might be to just hard-code the desired naming pattern by setting the named of a few tests and see how various VS versions deal with it.

**Comment by svengeance** [comment]
Fair enough. 

The best information I can find on TestCases is here - https://github.com/microsoft/vstest-docs/blob/master/RFCs/0017-Managed-TestCase-Properties.md

Of note in this document it specifically states there is no immediate attempt at standardization due to the drawbacks.
Unfortunately this seems wrong as the current `TestCase.cs` file [here](https://github.com/microsoft/vstest/blob/master/src/Microsoft.TestPlatform.ObjectModel/TestCase.cs) doesn't reference ManagedType or ManagedMethod at all..so that's interesting to say the least.

Looking at the adapter here there seems an obvious point to make changes [over here](https://github.com/nunit/nunit3-vs-adapter/blob/master/src/NUnitTestAdapter/TestConverter.cs#L168) along with an excellent comment detailing exactly what we're experiencing now. 

What's interesting to me is that the comment in that section of code clearly states `// It should _not_ include custom name or param values (just their types).`, whereas NUnit today **will** output the parameter values (using preview versions of both Adapter and Test)

![image](https://user-images.githubusercontent.com/6847381/82724563-f4920000-9ca4-11ea-90ce-659d1cdafacb.png)

Either I'm completely off base and barking up the wrong tree, or this is the sort of area we can get in and play around with various naming patterns, and see exactly if/how VS reacts to it.

**Comment by CharliePoole** [comment]
@OsirisTerje Will have to take that last one. That code was added after my time.

FWIW I created the adapter without any documentation from Microsoft, although I did get help from their devs after I signed an NDA. My approach back then was just to take a guess, try something and see what happened. It's a different world with the source code now being open!

**Comment by OsirisTerje** [comment]
Thanks @CharliePoole  and @svengeance  for bringing this one up again.  

FQN:  The FQN issue is still open, and we're discussing with the MS PG how to go about these things.  It is pretty clear now that the FQN (which @svengeance  is referring to above) is not working, and it has to change.  

About this issue in particular:
What you see in the Test Explorer is a mixture of two properties,  FullyQualifiedName (FQN) and DisplayName.  
The properties @svengeance points to above affects only the FQN from NUnit. 
Given a repro like this:
![image](https://user-images.githubusercontent.com/203432/82732298-a3b5f200-9d0c-11ea-973d-a9d4c3150d4d.png)
It will display the following:
![image](https://user-images.githubusercontent.com/203432/82732311-b7615880-9d0c-11ea-8bef-44a360a9bd59.png)
and this is what NUnit sends to the adapter:
![image](https://user-images.githubusercontent.com/203432/82732353-04ddc580-9d0d-11ea-8459-3ac96d7a842e.png)

Now, looking at what is being displayed for the different parts (putting the adapter into freak mode):
![image](https://user-images.githubusercontent.com/203432/82732390-3787be00-9d0d-11ea-9220-445d8c5e6c27.png)
As can be seen from this, the TestMethod in itself is display by the DisplayName property, which comes from the NUnit Name property, but all the overlying nodes are picked from the FQN, which each part, separated by the dots, are one level in the tree. 
If we now implement the DisplayName to be equal to the FQN, it should bring along the format wanted:
 
![image](https://user-images.githubusercontent.com/203432/82732459-a36a2680-9d0d-11ea-82de-952386340b0f.png)
So not quite there.  Notice that the lower test results box display the method with its full name, but the tree display still rips out everything ahead of the last dot. 
So, if we replace the dots to some other separator, like ':' (IIRC it is used in some language.....):

![image](https://user-images.githubusercontent.com/203432/82732503-ee843980-9d0d-11ea-8e9a-b387cdfd50f4.png)

This could also be resolved in NUnit itself, but the replacing of the dots are rather VS specific.  I am not sure if the Template Based Test Naming can be set up to provide the FQN here, @CharliePoole ?

If it is set in NUnit, it would apply to individual tests, but if set in the adapter, it would apply to all.

**Comment by CharliePoole** [comment]
Wow! @OsirisTerje That was a very complete exposition...

One question: What is "freak mode" and how do you get it?

**Comment by CharliePoole** [comment]
@OsirisTerje For the NUnit projects in which I'm no longer a participant, my rule of thumb is to give info where I have it and think it will help, including a perspective on where some feature came from in the first place or why it was done the way it was done. Also, frankly, if I think a ping to the team is needed. :smile_cat: That's how I ended up responding to this one.

In this case, WRT the framework, the major question isn't how it works or whether some change is possible to do. It's whether the framework team would be willing to make a change solely for the benefit of Visual Studio. My own view, when I was responsible, was that we didn't make changes like that unless they were likely to benefit other runners as well. But you would have to ask @rprouse and others on his team what the current view is.

From your explanation, it does seem that the adapter already receives all the necessary information from NUnit to do whatever transformation may be needed. Or am I missing something?

PS: Still willing to do some work on this for you when you let me know. It would take me a bit of initial setup and ramping up. I have a window of time although I'm also pretty busy on my new framework and on the GUI test application. It staves off boredom during this period of social distancing.

**Comment by OsirisTerje** [comment]
@CharliePoole  Thanks!   Yes, the adapter can do the transformation.  It will, as I mentioned, then apply to all tests, and under the RTD it might look a bit weird at first, but yes, it will be there.  
To add that in is a oneliner + an adapter setting.    
Agree to ping @rprouse , @jnm2 ,@mikkelbu about a change in the test naming templates for NUnit.  

About "freak mode":  As you mentioned above, you had to do experiments to figure out the VS/TE behaviour.  That has. and still is, a pain, and over the years I have been continiung doing that.  I have added more diagnostics to the adapter, among them the Dump file capability, which solves the issue of what we get back from NUnit itself.  The other end, to VS, is still weird and mystical, and I havent found a good way of improving that.  Source code helps, but I don't think we have all of that (I might be wrong there now, but at least I haven't found all of it, or the most relevant bits).  The interface chganges too, so it is a pain.    Recently I thought of another way of doing it, the "freak mode" (which will go into 3.17) (just started working on it)  The point is to let the adapter send something to VS/TE which we can more easily understand, from the perspective of the adapter.  So instead of sending the real test data, it sends kind of type information back, so that we can see what in the adapter (and framework) is causing what to happen in TE.  Completely useless in real test scenarios, but useful for figuring out how the TE uses the information from the adapter.  In order to trigger it, we still need tests, although the data from the test will not necessarily be used.   Next there is to have some self-triggering mechanism.

**Comment by svengeance** [comment]
Am I right in assuming that for the purposes of testing inside the IDE the adapter is able to send more information to VS? I'm curious which aspects discussed above affect not only the VS Test Explorer but also the test runner used via `dotnet test`

**Comment by OsirisTerje** [comment]
@svengeance 
![image](https://user-images.githubusercontent.com/203432/82737030-33b86380-9d2e-11ea-839c-5f5646d97783.png)

DisplayName is what is output here.  

And the trx file will also contain these:
```xml
 <Results>
    <UnitTestResult executionId="fb35df96-f7f0-489e-a3c5-22a6a46f0c0c" testId="fa391886-01ac-dfd4-157a-cb2b265dfc03" testName="FqnNameSpace:ParametrizedTestClass(&quot;Second&quot;,6):PTCMethod" computerName="DESKTOP-SIATMVB" duration="00:00:00.0000001" startTime="2020-05-23T19:48:36.0000000+02:00" endTime="2020-05-23T19:48:36.0000000+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="fb35df96-f7f0-489e-a3c5-22a6a46f0c0c" />
    <UnitTestResult executionId="50b45636-1a7e-479f-bffd-309d9275349c" testId="50d93ef0-dfec-610b-2c88-d242adb2e3e4" testName="FqnNameSpace:TestClassName:TestMethod" computerName="DESKTOP-SIATMVB" duration="00:00:00.1030000" startTime="2020-05-23T19:48:36.0000000+02:00" endTime="2020-05-23T19:48:36.0000000+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="50b45636-1a7e-479f-bffd-309d9275349c" />
    <UnitTestResult executionId="6332ab5b-f203-468c-bfe3-d195ca5add2e" testId="99312747-505c-fa3c-5a1e-36d62ae1e7bd" testName="FqnNameSpace:TestClassName:ParametrizedTestMethod(42)" computerName="DESKTOP-SIATMVB" duration="00:00:00.0000001" startTime="2020-05-23T19:48:36.0000000+02:00" endTime="2020-05-23T19:48:36.0000000+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="6332ab5b-f203-468c-bfe3-d195ca5add2e" />
    <UnitTestResult executionId="c13dc0ad-d77f-4e7e-b5a3-3d18dbb42352" testId="541cf5ec-4555-cbff-ba3a-ba31dc1742ba" testName="FqnNameSpace:TestClassName+NestedTestClass:NestedTestMethod" computerName="DESKTOP-SIATMVB" duration="00:00:00.0010000" startTime="2020-05-23T19:48:36.0000000+02:00" endTime="2020-05-23T19:48:36.0000000+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="c13dc0ad-d77f-4e7e-b5a3-3d18dbb42352" />
    <UnitTestResult executionId="e2f7dce0-5468-41d6-805c-0e5395e8dab1" testId="3f092c88-5727-216f-5d8a-7548c873e88d" testName="FqnNameSpace:ParametrizedTestClass(&quot;First&quot;,5):PTCMethod" computerName="DESKTOP-SIATMVB" duration="00:00:00.0160000" startTime="2020-05-23T19:48:36.0000000+02:00" endTime="2020-05-23T19:48:36.0000000+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="e2f7dce0-5468-41d6-805c-0e5395e8dab1" />
  </Results>
```

**Comment by OsirisTerje** [comment]
The adapter is configured through the runsettings.  

There are multiple ways to set this up, see the discussion in https://github.com/microsoft/vstest/issues/2229,  docs in https://aka.ms/vs-runsettings, and the PR here: https://github.com/microsoft/vstest/pull/2272 .  You don't describe your scenario, but if it is CI build these should cover it, as you can manage with one runsettings file, and use that automatically

**Comment by pepone** [comment]
@OsirisTerje how do I enable this feature, running tests with `dotnet test` but the class parameters are not included

I using 
```
   <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.16.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0"/>
```

do I need to add anything to runsettings?
