### ISSUE TITLE
Build NUnit3TestAdapter against nunit.engine 3.10

### ISSUE THREAD

**Issue by tdworshak** [nunit/nunit3-vs-adapter#641]
NUnit3TestAdapter 3.13 currently depends on nunit.engine.dll 3.9.0.  We have a few projects where this causes problems, since those projects also consume nunit.engine.dll 3.10.0.  This confuses Visual Studio, which reports conflicts.  Would it be possible to get an updated version of NUnit3TestAdapter that is built against nunit.engine.dll 3.10.0? Thank you for your consideration.

**Comment by mikkelbu** [comment]
@tdworshak I've moved the issue to nunit/nunit3-vs-adapter, but I think that perhaps this issue is already solved. As far as I can tell from https://github.com/nunit/nunit3-vs-adapter/blob/d1258294399a66f045dd85685d1867984bea95f3/src/NUnitTestAdapter/NUnit.TestAdapter.csproj#L37 this should already be the case from version 3.14 that is just released today.

**Comment by tdworshak** [comment]
Yes, I just grabbed 3.14 and it fixed the problem.  You can close this issue.  Thanks for your help!
