### ISSUE TITLE
Tests with multiple TestCaseAttribute break alphabetical order

### ISSUE THREAD

**Issue by Deni35** [nunit/nunit3-vs-adapter#659]
I know that NUnit does not guarantee any order. But usually `Test Explorer` shows tests in alphabetical order. This allows me to set my sensible order.
But when one test has or hasn't multiple `TestCaseAttribute` then it breaks order. 
Then tests with no multiple `TestCaseAttribute` are at the beginning (or in the end, in other project).

I really want tests to be in my desired order. 
Is there a way to set order?

![Test Explorer](https://user-images.githubusercontent.com/7755015/62621368-5bb41300-b924-11e9-909f-71eaa8fc79c7.png)

**Comment by mikkelbu** [comment]
Movibg this to the adapter project, but I'm unsure whether we can do anything about it.

**Comment by Deni35** [comment]
Now it hasn't any order at all.

**Comment by Deni35** [comment]
Sorry, I clicked on order by duration))

**Comment by OsirisTerje** [comment]
The addition of the UnitTest name in from of Test_3 is a bug, that is fixed in 3.15.1.

The ordering of the tests are determined by the Test Explorer.  You can change that based on what columns you use, but I don't think any of them will give you the order you expect.  
I changed to FQN, but it becomes the same order.....
![4](https://user-images.githubusercontent.com/203432/72222452-1ba52c00-3565-11ea-88a9-a3024562d708.jpg)
