### ISSUE TITLE
Dependency on Mono.Cecil 0.9.6 is not declared

### ISSUE THREAD

**Issue by KirillOsenkov** [nunit/nunit3-vs-adapter#662]
We have a custom test runner (not Visual Studio) to run NUnit tests. The unit-test project in system-under-test is targeting `net472` and has the following package references:

```
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.13.0" />
```

We end up with nunit.engine.dll 3.9.0.0 in the test output directory. nunit.engine.dll references Mono.Cecil.dll 0.9.6, but the NuGet package https://www.nuget.org/packages/NUnit3TestAdapter/3.15.1 neither declares a dependency on Cecil nor packs its own copy, nor ILRepacks to embed Cecil into nunit.engine.dll.

As a result if our test runner attempts to run tests from that directory the process crashes with Unable to load Mono.Cecil.dll 0.9.6.

If I understand this correctly, it would be better to use ILRepack to inline Cecil into nunit.engine.dll. It is better to inline Cecil because Cecil has changed the public key token between 0.9 and 0.10 and so binding redirects won't work. Updating to the latest Cecil and declaring that dependency (or including Mono.Cecil.dll in the NuGet package) would work too.

How does this normally work? Does VS bring its own Cecil? Thanks!

@jnm2

**Comment by jnm2** [comment]
@KirillOsenkov We are embedding Mono.Cecil as an embedded resource in NUnit3.TestAdapter.dll. 

The problem is that we don't have a module initializer, so we only hook up the AssemblyResolve handler in the entry points from VS. Original PR: https://github.com/nunit/nunit3-vs-adapter/pull/541

We'd like to get there. We also want to embed nunit.engine.dll too, but that would force us to figure out how to inject a module initializer because VSTest reflects over too many types before calling the adapter entry points which triggers the same error with nunit.engine.dll that you're seeing with Mono.Cecil.dll.

**Comment by jnm2** [comment]
ILRepack might be safe, though my preference would still be embedded resources due to the subtleties I've dealt with in the past when changing assembly boundaries like that.

**Comment by KirillOsenkov** [comment]
I got it, the runner should be calling `EmbeddedAssemblyResolution.EnsureInitialized();`. Good job on embedding Cecil as a resource! I didn't think to look inside NUnit3.TestAdapter.dll.

I guess it's not a bug then so I'll go ahead and close the issue. Thanks for the explanation!

**Comment by jcansdale** [comment]
BTW, it's also possible to embed Cecil as a single source file this:
https://gist.github.com/jcansdale/9eff65dda0eaaa6196f5ef737a569803

**Comment by jnm2** [comment]
@KirillOsenkov If I finish the project I'm working on which embeds assemblies and inserts a module initializer if you reference a NuGet package, we would have then removed `EmbeddedAssemblyResolution.EnsureInitialized();` since we considered it an internal implementation detail. Would doing that now break your runner, since you're calling it from the runner?

I forget whether it's public. Even if it is, I think the premise of this library is that only VSTest (or runners that behave precisely the same) is expected to consume the types in this library.

**Comment by KirillOsenkov** [comment]
It's not public and I'm using reflection to call it, but don't worry about breaking us. We'll adapt.
