### ISSUE TITLE
NUnit3TestAdapter3.16. dotnet filter argument is not applied 

### ISSUE THREAD

**Issue by pantosha** [nunit/nunit3-vs-adapter#686]
* NUnit: 3.12.0
* NUnit3TestAdapter: 3.16.0
* Visual Studio edition and full version number: Professional, 16.4.2
* A short repro: https://github.com/pantosha/nunit3adapterfilterissue
* What .net platform and version: dotnet core 3.1

The filter argument does not reduce the number of executed tests.

Command:
`dotnet test .\nuni3testadapterfilter.sln --filter:"FullyQualifiedName=abc"`

Expected result:
No one test is run

Actual result:
* No one test is run in the project that references NUnit3TestAdapter 3.15.1
* Test is run in the project that references NUnit3TestAdapter 3.16

![image](https://user-images.githubusercontent.com/1799798/71835736-502b6a80-30c3-11ea-98cb-5c39cea92ead.png)

**Comment by OsirisTerje** [comment]
@pantosha Thanks for reporting this!
I can confirm it.  It is a bug caused by the changes in the new NUnit filter code.  I've found the bug, and have a fix, so will push that up soon.

**Comment by OsirisTerje** [comment]
@pantosha Please verify if this beta version works in your case https://www.myget.org/feed/nunit/package/nuget/NUnit3TestAdapter/3.16.1-dev-01246

**Comment by pantosha** [comment]
It works! Thanks

**Comment by OsirisTerje** [comment]
This issue is resolved by Version 3.16.1 which is released now on [nuget.org](https://www.nuget.org/packages/NUnit3TestAdapter/3.16.1) and VSIX on [Visual Studio marketplace](https://marketplace.visualstudio.com/items?itemName=NUnitDevelopers.NUnit3TestAdapter).  See [all issues resolved](https://github.com/nunit/nunit3-vs-adapter/issues?q=is%3Aissue+milestone%3A3.16.1+is%3Aclosed) and  [Release notes](https://github.com/nunit/docs/wiki/Adapter-Release-Notes) for details.
