### ISSUE TITLE
Nunit 3.0.0-rc-2 : System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by BlueLemming** [nunit/nunit3-vs-adapter#69]
Hello,
Apologies if this is a duplicate, but I have been seeing this error message since upgrading Nunit passed 3.0.0-beta-4 (downgrading to beta-4 "fixes" the problem) .Without piling useless information on this case:
I've removed all Boolean Asserts from my code (if that matters at all?)
I've updated the TestAdaptor to 3.0.4-ctp-5 
And updated Nunit to 3.0.0-rc-2

And in an attempt to trace the problem, i've inserted:
 System.Runtime.CompilerServices.ExtensionAttribute x = null; 
into my code to generate the following error

Error	1	The type 'System.Runtime.CompilerServices.ExtensionAttribute' exists in both 'c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll' and 'c:\Users\Dan\Documents\Visual Studio 2012\Projects\AutomationBase\packages\NUnit3TestAdapter.3.0.5-ctp-5\lib\nunit.engine.dll'	C:\Users\Dan\Documents\Visual Studio 2012\Projects\AutomationBase\AutomationBase\TestMain.cs	30	49	AutomationBase

If you need more reproduction info, or anything else, i'll happily provide it. 
Cheers,
Dan

**Comment by CharliePoole** [comment]
Because the engine has to run under .NET 2.0, it includes its own definition of that attribute. This is a common hack when wanting to use C# 3.0 extension methods while targeting .NET 2.0. If your tests target a higher version of .NET, you may see a compiler warning notice, which can be ignored.

The error you generated occurs, of course, because of the ambiguous reference you made in the test. Normally, you would not refer to this attribute in your code.

You have not actually told us about the original error you are trying to fix. What was happening before you created error 1 in an attempt to figure out the source? If you can provide more info quickly, it's possible that a fix will get into today's release of CTP 6.

**Comment by BlueLemming** [comment]
The issue is with running tests (either All or individually) and getting the error System.Reflection.TargetInvocationException in the test output window and the tests not running.

**Comment by CharliePoole** [comment]
Unfortunately, TargetInvocationException wraps another exception, so the true cause. We should probably be displaying the inner exception. I'll be fixing this today in CTP-6. 

You might take a look at the two bugs in the CTP-6 milestone: https://github.com/nunit/nunit3-vs-adapter/milestones/3.0-CTP-6 Do either of these match your tests?

**Comment by CharliePoole** [comment]
If we don't fix the bug in today's release, we'll at least give you a better exception message.

**Comment by BlueLemming** [comment]
Pretty sure the above two mentioned don't match,  I'll post the exception I get after today's release

**Comment by BlueLemming** [comment]
Updating the package through VS and not through the package manager console seemed to do the trick, as its now running tests. I think we can assume the latest build (properly installed) has resolved this one.
