### ISSUE TITLE
Can't run only one test case from combinatorial test

### ISSUE THREAD

**Issue by stryczekk** [nunit/nunit3-vs-adapter#690]
Hi, I have updated Visual Studio to the newest version, and i have some problems with executing test cases in vs.
I have combinatorial test and if i want to run only one test case, but nunit executing all cases for selected test
![run selected test case](https://user-images.githubusercontent.com/9864259/71956643-f7a3bc80-31eb-11ea-8d06-7f7fb992f374.png)
In the output window i can see that all 6 cases are executed
[output.txt](https://github.com/nunit/nunit3-vs-adapter/files/4033934/output.txt)

How can I execute only few test cases? Is there any workaround?
It's very urgent for me

 * NUnit v3.12.0
 * NUnit3TestAdapter v3.16.0

* Visual Studio edition and full version number (see Help About): v16.4.2
* A short repro, preferably attached or pointing to a git repo or gist
[nunitadapterbug.zip](https://github.com/nunit/nunit3-vs-adapter/files/4033910/nunitadapterbug.zip)

* What .net platform and version is being targeted: .NET Framework 4.7

**Comment by OsirisTerje** [comment]
This is part of the behavior change in 3.16, done to fix data driven tests, but has this unfortunate side effect.  We need to look into this.
I suggest you downgrade the adapter to use version 3.15.1, which will do what you want.

**Comment by stryczekk** [comment]
Thanks for your reply.
With extension v3.15.1 and without nuget package in project is working as I expected.

**Comment by coleburg** [comment]
I have noticed the same behaviour with my automated tests, I use the browser in the TestFixture, with 3.16.0 when you build, its removes the (chrome) for example from the tests and separates all tests with parameters and non parametised, which means its breaks all automated tests linked to Azure Dev Ops.  

If you need more info to help fix the bug, please let me know.

Thanks

**Comment by OsirisTerje** [comment]
@coleburg It would be nice to have some more info on how your tests are being used.  Also, for builds in ADO I assume you then have some filters, can you describe them (as examples).  
The change in 3.16 **will** change the way tests are named, since we have changed from Names to FQN.  The behavior described by @stryczekk is unwanted, and since the tests he shows are simpler than the ones the change in 3.16 is meant to fix, we need to change the default behavior here.

**Comment by OsirisTerje** [comment]
In 3.16.1  the default will be to use the FQN of the test itself, not the parent.  There will be a switch in the runsettings that can be used to opt in the parent FQN behaviour.

**Comment by srinirao59** [comment]
> I have noticed the same behaviour with my automated tests, I use the browser in the TestFixture, with 3.16.0 when you build, its removes the (chrome) for example from the tests and separates all tests with parameters and non parametised, which means its breaks all automated tests linked to Azure Dev Ops.
> 
> If you need more info to help fix the bug, please let me know.
> 
> Thanks

Hi  I am facing the same issue too.

**Comment by OsirisTerje** [comment]
@srinirao59  @stryczekk   Please verify if this beta version works in your case https://www.myget.org/feed/nunit/package/nuget/NUnit3TestAdapter/3.16.1-dev-01246

**Comment by stryczekk** [comment]
Yes, works as expected. Thanks!

**Comment by srinirao59** [comment]
@OsirisTerje : It working now thank you, when we can expect this release in nuget?

**Comment by OsirisTerje** [comment]
@srinirao59 Awesome!. Eta is saturday.

**Comment by OsirisTerje** [comment]
This issue is resolved by Version 3.16.1 which is released now on [nuget.org](https://www.nuget.org/packages/NUnit3TestAdapter/3.16.1) and VSIX on [Visual Studio marketplace](https://marketplace.visualstudio.com/items?itemName=NUnitDevelopers.NUnit3TestAdapter).  See [all issues resolved](https://github.com/nunit/nunit3-vs-adapter/issues?q=is%3Aissue+milestone%3A3.16.1+is%3Aclosed) and  [Release notes](https://github.com/nunit/docs/wiki/Adapter-Release-Notes) for details.

**Comment by ngvtien** [comment]
Problem still exist in current and previous version
