### ISSUE TITLE
NUnit3TestExecutor.MakeTestFilter creates element not handled by NUnit.Framework.Internal.TestFilter

### ISSUE THREAD

**Issue by appel1** [nunit/nunit3-vs-adapter#70]
Maybe I'm missing something here or looking at the wrong code. 

NUnit3TestExecutor.MakeTestFilter creates a filter on the form:
```
<filter>
  <tests>
    <test/>
  </tests>
</tests>
```

TestFilter.FromXml doesn't seem to handle elements called tests but throws an ArgumentException in that case. 

Perhaps the tests element should be an or element instead?

**Comment by CharliePoole** [comment]
You're right! The format of the filters changed and, in fact the adapter should not be creating them at all because we exposed an engine service so they would be created correctly. Maybe we should expose a simple Type that wraps them so errors like this are caught in compilation.

This means that no test selection will work correctly, because they all result in a filter based on the test name. We'll put out a new CTP today.
