### ISSUE TITLE
v3.16.0 VS Community 2019 Stops run tests, no error, just no results from test....

### ISSUE THREAD

**Issue by LadislavSopko** [nunit/nunit3-vs-adapter#700]
I've updated to new nuget version,
And it stops Run tests in VS Test Explorer. 
If I debug it, it goes in debug, but it does not show results.

* NUnit 3.12 and NUnit3TestAdapter 3.16 versions
* Visual Studio Community edition 16.4.2 
* Have no idea how to reproduce, I have big project, It works perfectly under Resharper, But normal VS test explorer no
* What .net Framework 4.7.2

Thx

**Comment by mikkelbu** [comment]
Usually you can get some information about the problems by looking in the Output window in VS (by selecting "Show output from: Tests").

But I'm guessing that you are having the same problem as the other people that have reported issues against 3.16 -  see e.g. https://github.com/nunit/nunit3-vs-adapter/milestone/35?closed=1.

**Comment by MpStyle** [comment]
:+1:

Me and my team have downgraded to the 3.15.1 version: https://github.com/nunit/nunit3-vs-adapter/releases/tag/V3.15.1

**Comment by jcurl** [comment]
I've run in a similar problem (I was using multitargetting), perhaps follow the guidelines there (as it fixed my problem)? https://github.com/nunit/nunit3-vs-adapter/issues/704

From @OsirisTerje:
> Can you try the same with the latest 3.16.1 dev version on myget?

**Comment by OsirisTerje** [comment]
This issue is resolved by Version 3.16.1 which is released now on [nuget.org](https://www.nuget.org/packages/NUnit3TestAdapter/3.16.1) and VSIX on [Visual Studio marketplace](https://marketplace.visualstudio.com/items?itemName=NUnitDevelopers.NUnit3TestAdapter).  See [all issues resolved](https://github.com/nunit/nunit3-vs-adapter/issues?q=is%3Aissue+milestone%3A3.16.1+is%3Aclosed) and  [Release notes](https://github.com/nunit/docs/wiki/Adapter-Release-Notes) for details.
