### ISSUE TITLE
VS IDE not showing test cases run

### ISSUE THREAD

**Issue by jcurl** [nunit/nunit3-vs-adapter#704]
When reporting a bug, please provide the following information to speed up triage:

* NUnit and NUnit3TestAdapter versions
NUnit 3.12.0 for .NET 4.5 (net45 in nuget package)
NUnit3 Test Adapter 3.16.0

* Visual Studio edition and full version number (see Help About)
VS Enterprise 2019 v16.4.2

* A short repro, preferably attached or pointing to a git repo or gist
I've built my project to support multitargetting and have modified the csproj files that when building, intermediate paths and bin paths point to locations that included the runtime version (instead of just obj/debug and bin/debug, it's now obj/debug/net45 and bin/debug/net45). This helps with packaging.

The sources are attached: [crashreporter.zip](https://github.com/nunit/nunit3-vs-adapter/files/4067881/crashreporter.zip). I've attached the packages, just because it's using some analyzer not default in NuGet [packages.zip](https://github.com/nunit/nunit3-vs-adapter/files/4067952/packages.zip)

Problem observed, when loading the solution (RJCP.CrashReporter-net45.sln) and compiling for RELEASE, some weird display issues:
* Restore the NuGet packages
* Build from a clean folder. You'll see 
![image](https://user-images.githubusercontent.com/1563519/72478010-3d1a4800-37f1-11ea-9dc6-d12ccaadefcf.png)
* Right click on RJCP.CrashReporterTest-net45 and run them. They'll run, but there's no results (even though they did run!). Notice, they're now slightly greyed out.
![image](https://user-images.githubusercontent.com/1563519/72478133-8cf90f00-37f1-11ea-95b2-0b2faf8b7303.png)
* Go to DEBUG configuration, Rebuild and repeat running the tests. The same results. However, when I first cleaned then run it worked. But then trying to repeat it doesn't work and it's just darkened.
* Build -net40. 

So it somehow appears the discovery of the test libraries isn't finding the results of the build, and looking somewhere else.

I had it in a state that it showed me <Unknown Project>, so when I run the tests, they were grey, but the results in the <Unknown Project> turned green.

Note, when running from the console with the runner, it works perfectly. But I need debugging capabilities within VS.

I believe that it worked before changing the output paths. But I can't revert that, because then compilation fails when switching solutions due to incremental builds not rebuilding all images. So I really need to have VS IDE find the right test cases from the build in their own directories.

* What .net platform and version is being targeted
.NET 4.5 and .NET 4.0 is targeted.

**Comment by chebastian** [comment]
Possible Workaround: Selecting "Run Not Run Tests" will correctly report status to the TestExplorer, worked for me and another dev who experienced this issue just now

**Comment by OsirisTerje** [comment]
Can you try the same with the latest 3.16.1 dev version on myget?

**Comment by jcurl** [comment]
@OsirisTerje certainly much better when I installed 3.16.1-dev-01248 via the PM console in both my solutions (net40 and net45). There is still a slight hiccup that when I built for -net40 first, then closed and opened for -net45, it first shows an "<Unknown project>". Test cases now run (where before they were reported to "<Unknown project>".

![image](https://user-images.githubusercontent.com/1563519/72525956-9ae87780-3865-11ea-9ec9-f3b3bbf22f7f.png)

But in principle this unblocks the problem.

**Comment by OsirisTerje** [comment]
@jcurl  Thanks a ton!  
MS is aware of the Unknown project issue, and it is a mismatch issue between the Ids they assume we have and the real discovered ids of the tests.  Further, there seems to be a cache issue here, since deleting the .vs folder seems to fix the problem.  You're probably hitting that issue when you switch the frameworks.

**Comment by jcurl** [comment]
@OsirisTerje that's really good to hear (and it seems the problem I have is solved already but not released, and the other problem isn't to do with NUnit). What's the difference between installing the VSIX (which I normally do) and the NuGet package?

I prefer the VSIX solution (it's obvious it applies to all solutions), but I read somewhere on NUnit that MS wants to deprecate this.

So if I move over to the NuGet solution, do *all* projects against NUnit3 need to have the package installed? Any conflicts if the VSIX remains installed (which I did for my tests)?

**Comment by OsirisTerje** [comment]
@jcurl   VSIX/Nuget:  We really need to write up better on this topic :-)  
Yes, VSIX is in the process of being deprecated, and you should move to the nuget based adapter.  One of the big reasons for this is that the adapter will then follow into the build system, so your CI/CD builds will still work with no need to install adapters onto every build server.  This is particularly important when you're running on hosted builds, like Azure Devops or Github actions.  It also ensures that there is no need for some company policy to have the adapter installed on all developers machines.  
Another benefit is that different projects (and solutions) can use different versions of the adapter, ensuring that if you're hit by one of these issues we've had, then you isolate the projects that triggers this issue and keep them on a lower version until the issue have been fixed, but still move on projects that don't have it. 

With VS2017 and 2019 you need to have the adapter installed into every project.  This does not mean any duplication really, since they are stored either in your global package "repository" (%userprofile%/.nuget/packages if you use the new SDK csproj format or using packagereferences, or in your solution's packages folder if you're using the old csprojformat.  

About coexiting with VSIX; that is not a very good thing.  Earlier (and I am not sure if it still is so, the test system have been largely updated by MS in the latest versions) the VSIX took preference over the Nuget, meaning it would be run regardless if you had a newer nuget version.  I would really recommend removing the VSIX version fully.  If you have many solutions and many developers that can be a pain, but if the tests are running ok, it does no harm if someone have the VSIX installed. Just know that the VSIX will be run (and probably auto-updated too), so you might see issues from some developers, like what we have had now. 

Hope this helps :-)

**Comment by jcurl** [comment]
Thank you very much for the explanation, especially the last paragraph. I've rerun the test on my local machine with the NuGet package test runner, removed the VSIX (the previous test was with the VSIX). it appears to still work.

One interesting thing I've noted in VS2019 is that only *one* project needs the reference to the NUnit3TestAdapter. I was able to run NUnit3 tests for a different project that didn't include the adapter. Seems to indicate that only one version is needed (then it would be interesting to know which adapter is really run).

I'll close this as i believe it is resolved when there's an update to the test runner, and I can move over to the NuGet version. Any estimates on the next release?

**Comment by OsirisTerje** [comment]
@jcurl  ETA for the 3.16.1 is Saturday.

I am surprised it still works with one adapter.  That was the former behavior.  I Don't think that will last though.

**Comment by jcurl** [comment]
@OsirisTerje you're right, tried it at home and it didn't work, I have to install the adapter for all projects that require NUnit3. I really appreciate your feedback and wisdom. Cheers!
