### ISSUE TITLE
v3.16 duplicate tests in test explorer

### ISSUE THREAD

**Issue by GeorgeAlexandria** [nunit/nunit3-vs-adapter#705]
Hello,

I try to use a new version of **nunit adapter 3.16** with **visual studio 15.9.19** and **nunit 3.10.1**, but this adapter's version duplicates tests in the test explorer while run them. Visual Studio option that discovers tests on runtime is disabled. 

I can reproduce it when project references another one and when invoke rebuilding of solution before run all tests. However, such examples work fine on **nunit adapter 3.15.1**

How it looks like on adapter 3.16:
![image](https://user-images.githubusercontent.com/13402478/72643116-ff4b2a00-397e-11ea-9ebe-13a53566049c.png)

Here a small sources example where this behavior is reproduced:
[TestRepo.zip](https://github.com/nunit/nunit3-vs-adapter/files/4078900/TestRepo.zip)

If I miss something, please let me know about it.

**Comment by OsirisTerje** [comment]
@GeorgeAlexandria Can you try this with the 3.16.1 pre release, from myget.  See readme at front for the link

**Comment by GeorgeAlexandria** [comment]
@OsirisTerje seems that the 3.16.1-01248 works well (as nuget package at least)

**Comment by OsirisTerje** [comment]
@GeorgeAlexandria  Thanks for confirming !

**Comment by OsirisTerje** [comment]
This issue is resolved by Version 3.16.1 which is released now on [nuget.org](https://www.nuget.org/packages/NUnit3TestAdapter/3.16.1) and VSIX on [Visual Studio marketplace](https://marketplace.visualstudio.com/items?itemName=NUnitDevelopers.NUnit3TestAdapter).  See [all issues resolved](https://github.com/nunit/nunit3-vs-adapter/issues?q=is%3Aissue+milestone%3A3.16.1+is%3Aclosed) and  [Release notes](https://github.com/nunit/docs/wiki/Adapter-Release-Notes) for details.
