### ISSUE TITLE
CodeFilePath like in nunit2

### ISSUE THREAD

**Issue by bernd5** [nunit/nunit3-vs-adapter#723]
Hello,

currently I'm using NUnit 3 with a "TestCaseSource". I would like to set a "CodeFilePath" like in Nunit 2, but I don't see how.
In the code I found the "NavigationDataProvider" - but it works only via reflection. How can I implement a custom NavigationDataProvider?

Kind regards,

Bernd

**Comment by bernd5** [comment]
What I really want is that a custom file opens when I do a double click on a test case produced by a TestCaseSource.

**Comment by OsirisTerje** [comment]
This was very special.  I am not quite sure how this could be done.  
Since you already have looked at the code, you could give it a try, and create your own variation, a special adapter for just this purpose. 
If you added the "codeline" into your test, so that it goes with the testdata, you could add it into the testoutput in the MakeTestCaseFromXmlNode method in the TestConverter.

**Comment by bernd5** [comment]
I would say using a "TestCaseSource" is special. But if you need it, it would be great to use this "goto code / goto test definition" feature.
It would be fine if I could just use a simple string property value (no API change required).
VS TestCase has a property "TestCase.CodeFilePath" which is mapped to the CodeFilePath property. These properties values should be transfered / copied in the TestConverter.

See: [VS TestCase ProtectedGetPropertyValue](https://github.com/microsoft/vstest/blob/master/src/Microsoft.TestPlatform.ObjectModel/TestCase.cs)

**Comment by OsirisTerje** [comment]
The TestCase from MS is the output, no problem putting this in there, that is what we do normally.  The issue is how this could be coming up from NUnit, which it currently doesn't.   Using Properties could do it, but then the purpose of those are different.  They would also be exposed in the Test Explorer as properties, and that could be very confusing.  But, doing it for your own is an option.  Have you considered that?

**Comment by bernd5** [comment]
Solved with #735

**Comment by OsirisTerje** [comment]
@bernd5  Beta released on Nuget, see https://www.nuget.org/packages/NUnit3TestAdapter/3.17.0-beta.1  .  Please check that it works :-)

**Comment by bernd5** [comment]
Thank you very much!!!
It works great.
