### ISSUE TITLE
Setting `UseParentFQNForParametrizedTests` via `nunit.runsettings` does not work

### ISSUE THREAD

**Issue by johnmwright** [nunit/nunit3-vs-adapter#730]
I'm running Microsoft Visual Studio Enterprise 2019 (Version 16.5.0) with NUnit3TestAdapter v3.16.1.

In order to take advantage for the fixes from v3.16.0 from PR #668 , I've created a `nunit.runsettings` file [as noted here](https://github.com/nunit/nunit3-vs-adapter/issues/676#issuecomment-573433308) that looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
   <NUnit>
     <UseParentFQNForParametrizedTests>True</UseParentFQNForParametrizedTests>
     <UseNUnitIdforTestCaseId>True</UseNUnitIdforTestCaseId>
   </NUnit>  
</RunSettings>
```
I've attempted placing the file in the following locations:

* The solution folder
* The test project folder
* The test project bin (output) folder

However, in none of those cases does the applicable configuration option get set, thus the bug fixed by #668 continues to haunt me.

Can you provide guidance on how to properly override those two settings?

**Comment by OsirisTerje** [comment]
It doesn't matter where the file is placed.  You need to add the file location (path+name) to whatever test runner you're using.   Which one is that ?

**Comment by OsirisTerje** [comment]
Sorry, read your post too fast.   
Do you have VS set to find the runsettings automatically?
Have you tried to set it manually?  Then you set the direct path/location and it **will** find it.
You can add one more NUnit setting, e.g. verbosity, so that you can verify it is being used. 

Also be aware that your case can be one of them not fixed.
