### ISSUE TITLE
Hiding TestCaseSource Test Method in Test-Explorer

### ISSUE THREAD

**Issue by bernd5** [nunit/nunit3-vs-adapter#736]
For a TestCaseSource -Test you can see the test provider function in the test cases (logically the parent of the provided test).

Is there a way to hide them? I see no way to configure them. They make only sense in a tree view.

**Comment by OsirisTerje** [comment]
The display of the tests is handled by the Test Explorer.  The adapter only sends the information it has, and we have no information on how the Test explorer want to display this.  

That said, I do **assume** the  reason for the non-flat list of dynamic test data is due to the nature of this.  The real time tests can only display what it see, and it doesn't see the dynamic tests until they have run.   You can raise an issue on the DeveloperCommunity site and suggest a change there for the Test Explorere wrt to this behaviour.

**Comment by bernd5** [comment]
Thank you for your feedback. I hope the picture below shows better what is my concern.

![grafik](https://user-images.githubusercontent.com/26689688/79901971-fd2ab880-8410-11ea-81e8-2e3e2e347367.png)

When ever you use  TestCaseSource like:

```CSharp
[TestCaseSource(nameof(GetTestFiles))]
public void TestHeader(FileInfo file)
{
    Assert.Pass();
}
```

You will see this "Meta-Test" in the Test-Explorer. I just don't want to see this Test. Any "hack" is welome.

**Comment by OsirisTerje** [comment]
Yes, that is a very annoying "feature" in VS.  We're talking with the MS PG about this, but there is still no real solution to it.  It comes up as a discrepancy between the FQN standard of the Real Time Discovery in Test Explorer.  
In my VS it looks like this:
![image](https://user-images.githubusercontent.com/203432/79914403-877d1780-8425-11ea-8aa6-a55d16c8d95a.png)

If I turn off the Real Time Discovery:
![image](https://user-images.githubusercontent.com/203432/79914436-949a0680-8425-11ea-93d4-d2848a054cf7.png)

I will get rid of those :
![image](https://user-images.githubusercontent.com/203432/79914474-a67ba980-8425-11ea-83a9-698895846339.png)

**Comment by bernd5** [comment]
Thank you for that quickfix.
