### ISSUE TITLE
Syntax for auto-removable test suffix

### ISSUE THREAD

**Issue by Denis535** [nunit/nunit3-vs-adapter#760]
Sometimes I'm forced to write new method with a little new name, but I want Test Explorer to show those methods as one method.
For example:
```
[Test]
public void Test_Serialize() {
}
[Test]
public void Test_Serialize__ArgumentNullException() {
}
```
Here I'd like NUnit to remove everything starting with `__` (double underscore). And Test Explorer to show those methods as one method.

**Comment by OsirisTerje** [comment]
One can change the Displayname, as explained [here](#640), but it will not change the grouping, or collection of nodes in Test Explorer.  If you changed the name to be the same, it would be two nodes in the tree with identical names.  The structure is controlled by the FQN, and changing that is sort of not the thing to do.  Then things will not match up.  

I don't see anything that can be done on the adapter side to change this.

**Comment by OsirisTerje** [comment]
@Denis535  Ok, the following show how it will look: 
![image](https://user-images.githubusercontent.com/203432/84057197-9f99fd80-a9b7-11ea-8869-942ccd38fff3.png)

Notice that the node is still visible.  That comes from the RTD, and we have no control over that (except you as a user can turn it off, but you probably would not like that)

The issue here is that if you use the TestName property on the TestCase, RTD is aware of that, and will remove the extra node. 
![image](https://user-images.githubusercontent.com/203432/84057393-e4be2f80-a9b7-11ea-8332-1c3ae282e0a1.png)

Adding the functionality is trivial (it turned out), but I am not sure if this is a good approach.  

Regardless how it is done though, Going to the code using the tree node, will always take you to the first test (that is named the same way).  If one of the underlying tests are failing, the link there will take you to the correct place though.  

So, there are some considerations here.
