### ISSUE TITLE
TestCaseSource + NSubstitute + Async = Skipped Tests in VS 2019

### ISSUE THREAD

**Issue by akalnay** [nunit/nunit3-vs-adapter#765]
Given this interface:

```C#
    public interface IThing
    {
        Task<string> GetNumberAsTextAsync(int number);
    }
```
and this class that implements the interface:

```C#
    public class Thing : IThing
    {
        public async Task<string> GetNumberAsTextAsync(int number)
        {
            await Task.Delay(1);
            return number.ToString();
        }
    }
```
Running the following tests in VS 2017 works as expected:  four tests run and they all pass.  However running the same tests in VS 2019 causes one of the tests to get skipped (TestB2Async).
```C#
    public abstract class TestsBase
    {
        protected static class Data
        {
            public static int Number { get; }          = 5;
            public static string NumberAsText { get; } = "5";
        }

        protected static IThing GetInstance(bool mock)
        {
            IThing GetMockedInstance()
            {
                IThing thing = Substitute.For<IThing>();
                thing.GetNumberAsTextAsync(Data.Number).Returns(Task.FromResult(Data.NumberAsText));
                return thing;
            }

            return mock ? GetMockedInstance() : new Thing();
        }
    }

    #region TestsA

    public class TestsA : TestsBase
    {
        [Test]
        public async Task TestA1Async()
        {
            IThing thing = GetInstance(false);
            string result = await thing.GetNumberAsTextAsync(Data.Number);
            Assert.AreEqual(Data.NumberAsText, result);
        }

        [Test]
        public async Task TestA2Async()
        {
            IThing thing = GetInstance(true);
            string result = await thing.GetNumberAsTextAsync(Data.Number);
            Assert.AreEqual(Data.NumberAsText, result);
        }
    }

    #endregion TestsA

    #region TestsB

    public abstract class TestsBBase : TestsBase
    {
        public static IEnumerable<IThing> GetThingInstance(bool mock)
        {
            yield return GetInstance(mock);
        }
    }

    public class TestsB : TestsBBase
    {
        [TestCaseSource(nameof(GetThingInstance), new object[] { false })]
        public static async Task TestB1Async(IThing thing)
        {
            string result = await thing.GetNumberAsTextAsync(Data.Number);
            Assert.AreEqual(Data.NumberAsText, result);
        }

        [TestCaseSource(nameof(GetThingInstance), new object[] { true })]
        public static async Task TestB2Async(IThing thing)
        {
            string result = await thing.GetNumberAsTextAsync(Data.Number);
            Assert.AreEqual(Data.NumberAsText, result);
        }
    }

    #endregion TestsB
```
The main difference between the tests in TestsA and TestsB is that the tests in TestsA directly create the IThing instances, while the tests in TestsB use IThing instances provided via the TestCaseSource attribute.

The project's target framework is .NET Core 2.2, and it uses the packages NUnit 3.12.0, NUnit3TestAdapter 3.16.1, Microsoft.NET.Test.Sdk 16.6.1, and NSubstitute 4.2.2.

I wasn't sure where to report this (Microsoft, NUnit, or NSubstitute) but given that the distinguishing factor is the use of the TestCaseSource attribute, it seemed proper to report it here.

A solution file is attached, plus screenshots of what I see on the Test Explorer for VS 2017 and VS 2019.

Visual Studio 2017:
![VS2017](https://user-images.githubusercontent.com/54271378/86541977-fc2e0100-bf00-11ea-85e8-dd61696eeffa.jpg)

Visual Studio 2019:
![VS2019](https://user-images.githubusercontent.com/54271378/86541978-fe905b00-bf00-11ea-953b-8e3550a701ee.jpg)
[NSubstituteSkippedTestDemo.zip](https://github.com/nunit/nunit/files/4875606/NSubstituteSkippedTestDemo.zip)

**Comment by ChrisMaddock** [comment]
Hi @akalnay - as your issue is relating to running in VS, I’ve moved your issue over to this repo instead. I expect the team here will have some ideas. 😊

**Comment by mikkelbu** [comment]
@akalnay I'm quite sure that the problem is that you get a fresh name for the IThing from NSubstitute every time in the case of `TestB2Async`. So when we discover the tests the name of the instance passed to `TestB2Async` is `Substitute.IThing|01a6dda4` (I think we just use `ToString()` to get the name of the instance). But when we execute the test we get a new name - say `Substitute.IThing|99999999` - so we cannot match the test to run with the test name we discovered.

One way to solve this is to also override the ToString() of the IThing to something fixed. Another way is to return a `TestCaseData` from `GetInstance` and then call `SetName` to fix the test name.

**Comment by OsirisTerje** [comment]
@akalnay @ChrisMaddock  This comes from the naming of the last test.  The argument there is the name of the concrete type, and that is stable for the real interface, which then becomes "Thing".  For the substitute we get the name of the underlying Castle ObjectProxy, which is a combination of the Substitute.IThing and the HashCode for the class, which is the 8 digit hex number that follows. 

Now, the hash code of an object is not a stable value to rely on across processes.  And what happens is that we get different values for the different parts of these, and they don't match up.

There are however something strange about all of this.  First, turning off RTD means the NUnit Discovery process should give us this number, and it does.  For net core 2.2 it doesnt match up with what you see in the Test Explorer.  I have no clue why that is so, as for .net core 3.1 it **does** match up.  However, it still doesn't work, probably because during execution in the nunit framework we get still another value.    What is really happening here is a bit mysterious, but in any case one should not rely on these values.   
I have seen similar issues earlier with NSubstitute (and really any mock system that is built on Castle.DynamicProxy) in other cases (need to dig more to find that that was).

Example:
![image](https://user-images.githubusercontent.com/203432/86639803-d6285f80-bfd9-11ea-9d17-c3cf63f211db.png)

# There are two simple ways to solve this: 

## Option 1  

You can make the adapter unaware of the testcasesource names.  The tests will still be displayed the same way, but you then can't execute single testcasesource tests, only the complete set.  If this is ok with you, you can fix this by using the [UseParentFQNForParametrizedTests](https://github.com/nunit/docs/wiki/Tips-And-Tricks#useparentfqnforparametrizedtests) , and set this to true in a runsettings file. 
![image](https://user-images.githubusercontent.com/203432/86639908-05d76780-bfda-11ea-8a90-e08e9a3e86ed.png)

## Option 2

Instead of returning the interface, return an instance of TestCaseData, and set an appropriate name inside your method.
In your code, you can add the method in red, and just do the small red marked changes in the `GetThingInstance` method
![image](https://user-images.githubusercontent.com/203432/86640438-98780680-bfda-11ea-93f1-7a1f834c756e.png)

**Comment by OsirisTerje** [comment]
@mikkelbu Thanks!  I didn't see your post before I posted mine :-)   You clear up the execution mismatch, thanks!  I am still confounded why the values doesn't get back to Test Explorer from the discovery process, because there is no processing of this in the adapter. Whatever name comes from the Discovery process should pass through to the Test Explorer, and it doesn't for .net core 2.2, but it does for .net core 3.1.  Further, this works for VS 2017.  The only change I can see there is the RTD, but it doesn't work with VS 2019 with RTD off, so it might be a bug in VS 2019 not completely shutting down RTD... 

In any case, one should not rely on these values.  

You mention overriding the ToString, but I don't think that would work, since we get the interface out, from the `For` method, and not a concrete type.  Or did you mean something else ?

**Comment by mikkelbu** [comment]
You are probably right, I was just wondering if we could something similar to
```diff
            IThing GetMockedInstance()
            {
                IThing thing = Substitute.For<IThing>();
                thing.GetNumberAsTextAsync(Data.Number).Returns(Task.FromResult(Data.NumberAsText));
+               thing.ToString().Returns("Just testing");
                return thing;
            }
```
But this probably require us to add `string ToString()` to the interface.

**Comment by OsirisTerje** [comment]
Yeah, that might also work.  But I assume IThing is a sort of business interface, and should probably not be changed because of a test flaw.  But absolutely, it is an option. 

... Just tried it... it didn't work.... 

I assume it doesn't affect the actual call in the framework....

**Comment by akalnay** [comment]
@ChrisMaddock Thank you for moving the issue to this repo.
@OsirisTerje and @mikkelbu thank you for the in depth analysis of this issue.  I realize that the issue has been closed, but I'd like to add an additional comment regarding what I discovered while doing some additional testing.  I have had other issues with Visual Studio 2019 and as I've been pondering on alternatives I decided to give Rider a try.  Using Rider 2020.1.3 I got results similar to those of Visual Studio 2019, although instead of showing TestB2Async as skipped, Rider shows it as "Inconclusive".

Also, the Rider log indicates that that _"Element NSubstituteSkippedTestDemo.TestsB.TestB2Async.TestB2Async(Substitute.IThing|018ac423) was left pending after its run completion."_.  I am wondering if that has any significance.

Rider 2020.1.3
![Rider Test Results](https://user-images.githubusercontent.com/54271378/86823006-d9742780-c07b-11ea-9ad3-f145b401e85e.jpg)

**Comment by OsirisTerje** [comment]
@akalnay We're just closing this, because there is very little, if anything, we can do with this.  When I say "very little", it means one could in the future think about having another kind of id that would survive across processes, but there is nothing like that materializing anywhere soon.

About Rider, it works more or less the same way, but with a different "Test Explorer".  I also calls the adapter and then the same chain.  They do handle the result differently, but that is on their Test Explorer level.  The adapter never receives anything back from the engine/framework (we can see that using the DumpTestResults property.  :-)

**Comment by akalnay** [comment]
@OsirisTerje Yes, the first option works, thank you for mentioning it, I wouldn't have known about it otherwise.

Thank you.
