### ISSUE TITLE
3.16.1 -> 3.17.0:  Increased console output

### ISSUE THREAD

**Issue by rkm** [nunit/nunit3-vs-adapter#773]
Hi. Not actually sure if this is a bug or an intentional change. When upgrading from 3.16.1 to 3.1.7.0, every NLog call started appearing in our TravisCI build output, when previously this would only show up for failing tests. This dramatically increases the output for us, and we've reverted the upgrade for now. Is this intended?

* NUnit and NUnit3TestAdapter versions
NUnit `3.12.0`, NUnit3TestAdapter `3.17.0`

* Visual Studio edition and full version number (see Help About)
N/A 

* A short repro, preferably attached or pointing to a git repo or gist
  - First build after upgrading: https://travis-ci.com/github/SMI/SmiServices/builds/175300312
  - Build after reverting: https://travis-ci.com/github/SMI/SmiServices/builds/177045330

* What .net platform and version is being targeted
.NET Core 3.1

* If TFS/VSTS issue, what version, hosted, on-premises, and what build task you see this in
N/A

**Comment by OsirisTerje** [comment]
These two issues were fixed in 3.17,   [301](https://github.com/nunit/nunit3-vs-adapter/issues/301) and [343](https://github.com/nunit/nunit3-vs-adapter/issues/343).

There is a feature toggle you can use to remove this, see  [ConsoleOut](https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html#consoleout), which you can set in a runsettings file.

**Comment by rkm** [comment]
That worked for us, thanks!
