### ISSUE TITLE
Proprietary licensed files 

### ISSUE THREAD

**Issue by OliverFendt** [nunit/nunit3-vs-adapter#797]
The following files carry a Microsoft proprietary license header:

- src/NUnitTestAdapter/Internal/Stacktrace.cs
- src/NUnitTestAdapter/Internal/StackframeParser.cs
- src/NUnitTestAdapter/Internal/Stackframe.cs

The header reads:
`Copyright` (c) Microsoft Corporation. All Rights Reserved.
`Information` Contained Herein is Proprietary and Confidential.

Affected version - the current version and some former versions

Due to this those files cannot be used by anybody. Is there a possibility that, you obtain the MIT license for those files from Mircosoft?

**Comment by OsirisTerje** [comment]
@OliverFendt  Tanks for spotting that!
/@CharliePoole These files have been here since day 1, but I can't see they have ever been used.   It looks to me we can just delete these files.

**Comment by OliverFendt** [comment]
@OsirisTerje thank you for taking care. It would be great if these files can be deleted

**Comment by CharliePoole** [comment]
As a note of explanation. I started out with a sample adapter that had been developed by a Micsrosoft PM, which I used primarily to understand how an adapter had to work and rewrote a piece at a time. Those files were simply never deleted.

Fun fact... this was long before Microsoft got involved in Open Source as a company. In fact, back then, groups at Microsoft wanting to simply __use__ NUnit had to get permission and were not allowed to access our source code. Since we were distributing source with each release back then, I maintained a separate distribution without it just for those folks.
