### ISSUE TITLE
Incorrect test result message when test timed out

### ISSUE THREAD

**Issue by MaceWindu** [nunit/nunit3-vs-adapter#83]
https://github.com/nunit/nunit/wiki/Timeout-Attribute

> The TimeoutAttribute is used to specify a timeout value in milliseconds for a test case. If the test case runs longer than the time specified it is immediately cancelled and reported as a failure, with a message indicating that the timeout was exceeded.

Reported as:

> Result Message:   Test cancelled by user

I've checked console runner - it reports timeout failure, but also generates several "Test cancelled by user" messages before timeout message and it looks like adapter displays first message which is "Test cancelled by user". Do we even need those messages?

MaxTime attribute doesn't have that issue (because it doesn't abort test?)

**Comment by CharliePoole** [comment]
NUnit stops the test by cancelling it. Then, if it cancelled due to a MaxTime, it changes the failure message to indicate the timeout error. Only the final message should get through to the adapter.

When you say the console runner displays several messages, where do you see them? Are they part of the test XML output?

MaxTime has little in common with Timeout except for "Time" in the name. It doesn't abort a test, but merely applies a criterion as to how long it should take to run. It does change the result from success to failure as max time changes it from cancelled to timeout. The key difference is that there is a potential race condition with Timeout. That's probably why we are generating extra messges, but they aren't needed except perhaps in debug.

**Comment by MaceWindu** [comment]
console runner displays it like that on screen:
```
Errors and Failures

  1) Cancelled : TestsInitialization
  Cancelled by user

  2) Cancelled : ns1
  Cancelled by user

  3) Cancelled : ns1.ns2
  Cancelled by user

  4) Cancelled : ns1.ns2.ns3
  Cancelled by user

  5) Cancelled : ns1.ns2.ns3.ns4
  Cancelled by user

  6) Cancelled : : ns1.ns2.ns3.ns4.testclass
  Cancelled by user

  7) Failed : ns1.ns2.ns3.ns4.testclass.testmethod
  Test exceeded Timeout value of 10ms
```

Also results xml have all 7 messages as 6 nested into each other test-suite nodes  and 1 test-case node

**Comment by CharliePoole** [comment]
It appears that the cancellation is being promoted to the suite level before the cancellation is changed to a timeout. That could be a race condition.

**Comment by CharliePoole** [comment]
A further error is that a suite failure that is the result of a child failure is not supposed to appear in the error list because the info is redundant and confusing.

**Comment by viris8** [comment]
I am using version 3.5 and facing the same issue. 
The problem gets complicated when more tests are running: I have an Eventlistener extension and I am using progress-output in my tests to get real-time logging. When a test times out the framework generates two <test-case> events for the same test, the first has the [Test cancelled by user] message, the second one has the (correct) [Test exceeded Timeout value of x ms]. I am guessing that there should be only one <test-case> event for a test, with the timeout message. Am I right?
(Interesting, that this only happens if there are multiple tests in a suite, if this is the only test, only one <test-case> event is generated. If test fails for other reasons, also only one <test-case> event)

I attached a part of the console-output.
[TestExceededTimeoutValue.txt](https://github.com/nunit/nunit3-vs-adapter/files/827594/TestExceededTimeoutValue.txt)

**Comment by ChrisMaddock** [comment]
This issue is related to this: https://github.com/nunit/nunit/issues/2020

I'll leave open, as we're not sure if this is a framework or adapter issue yet - but wanted to make the link while it was in my mind!

**Comment by OsirisTerje** [comment]
Seems this is fixed, repro can't show any error.  So I will close this.
