### ISSUE TITLE
Explicit tests executed when running with dotnet test and a filter

### ISSUE THREAD

**Issue by Socolin** [nunit/nunit3-vs-adapter#874]
Hello

The tests marked with `[Explicit]` seems to be executed since 4.0.0 when trying to run test from the command line using `--filter`

`dotnet test TestProject1.sln   --filter TestProject1`

```
<TargetFramework>net5.0</TargetFramework>
```

```
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.10.0" />
<PackageReference Include="NUnit" Version="3.13.2" />
<PackageReference Include="NUnit3TestAdapter" Version="4.0.0" />
```

Repro: 
[TestProject1.zip](https://github.com/nunit/nunit3-vs-adapter/files/6925709/TestProject1.zip)

**Comment by OsirisTerje** [comment]
@Socolin The reason for this is that you have added a filter, which means the adapter assumes you want to execute explicit tests.  If you run without a filter, it will work as intended.  This is by design, to create a way for explicit tests to be executed using a filter.  However, this behaviour differs from the behaviour in the IDE, which require all tests to be explicit in order to be run.  This was a change that happened in VS2019, version 16.8 or 16.9, where they changed how the adapter was called.  That required that change to handle explicit cases but actually made it differ from the command line.  It would probably be better if the behaviour were equal in both cases.  One could also consider two different modes, a strict explicit which require all selected tests to be explicit in order to be run, and a relaxed mode, which accepted the selection of a parent now (except that can't fully work in the IDE, only one level up perhaps.).

**Comment by Socolin** [comment]
In that cas could a assembly level attribute to configure how the runner should work could be added ?

**Comment by OsirisTerje** [comment]
The normal way is to add that to the runsettings file.  There is a NUnit section there that is being used.  See https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html for other settings.  These settings can also be added directly on the command line.
Using attributes is of course also a way to do that, but I would guess this is more dependent upon what kind of run/build you're doing.  There could be multiple different builds, and then the runsettings are easier to change

**Comment by OsirisTerje** [comment]
I've looked a bit more into this issue, and it turns out it works as it should.

The command you run is:
```
dotnet test TestProject1.sln --filter TestProject1 -v:n --logger="Console;verbosity=detailed"
```
You can then see that when you run the repro you have enclosed, with only one explicit test within the project, the filter will be regarded as an Explicit filter:
![image](https://user-images.githubusercontent.com/203432/140627549-79703880-7159-434a-a2cb-6d1b2f2893bd.png)

I've updated the repro with more tests, see [code here](https://github.com/nunit/nunit3-vs-adapter.issues/blob/master/Issue874/TestProject1/UnitTest1.cs )

When this is run in the same way, then the run is reported as a Non-Explicit run, and the Explicit test is not run. 
![image](https://user-images.githubusercontent.com/203432/140627611-426c41f0-4ac5-4191-98a1-3297d8fc4e30.png)

If you try to filter on Category="A", you will see that again only the non-explicit test is run, and the run itself is a non-explicit run. 

If you see anything else in your actual project, please turn on the logger as described here, and see what it says.  You might have a real issue in your project, but then you need to update your repro accordingly.

**Comment by runehalfdan** [comment]
I have a similar issue, but I use NUnit-filters 'cat!=FOO'

Using the enclosed test-project here, and adding some categorized filters, Explicit tests are executed
Running `dotnet test TestProject1.sln  -v:n --logger="Console;verbosity=detailed" -- NUnit.Where="cat!=FOO"`
products 

```
Running selected tests in C:\source\rune\NUnitTestProject1\TestProject1\bin\Debug\net5.0\TestProject1.dll
   NUnit3TestExecutor discovered 2 of 2 NUnit test cases using Current Discovery mode, Non-Explicit run
NUnit Adapter 4.1.0.0: Test execution complete
  Failed Test1 [30 ms]
  Stack Trace:
     at TestProject1.Tests.Test1() in C:\source\rune\NUnitTestProject1\TestProject1\UnitTest1.cs:line 12

  Passed TestBar [1 ms]
```
Adding 'cat!=Explicit' does not help

(btw, using legacy discovery does help, and we will use that for now)

All tests:
```
[Test]
[Explicit]
public void Test1()
{
	Assert.Fail();
}

[Test]
[Category("FOO")]
public void TestFoo()
{
    Assert.Pass();
}

[Test]
[Category("BAR")]
public void TestBar()
{
    Assert.Pass();
}
```

**Comment by OsirisTerje** [comment]
@runehalfdan  Thanks!  It seems you're right in your case. 
The case is different from the one reported here, so I'll move this into a new issue.
