### ISSUE TITLE
AddTestAttachment does not work anymore in VS2022

### ISSUE THREAD

**Issue by bernd5** [nunit/nunit3-vs-adapter#914]
## Description

If the following code is executed:

```csharp
using NUnit.Framework;

namespace NUnitTest
{
    public class Tests
    {
        [Test]
        public void TestNunitAttachment()
        {
            TestContext.AddTestAttachment(@"C:\Windows\WindowsUpdate.log");
        }
    }
}
```

The attached file is not clickable (it works with MSTest). I assume the file-scheme is causing the issue.

See the following image:
![grafik](https://user-images.githubusercontent.com/26689688/141206765-9c4e4e4e-5b55-498b-acf2-a17b03986249.png)

## Versions

NUnit: 3.13.2
NUnit-Test-Adapter: 4.1.0
.net platform: 5 / 6
Visual Studio edition: VS2022 Enterprise Version 17.1.0 Preview 1.0

**Comment by OsirisTerje** [comment]
@bernd5 You mention "file-scheme". Can you elaborate on what you found there?

**Comment by bernd5** [comment]
It looks like the file scheme is not support anymore for attached test files in VS2022. But this just a guess because of the strange highlighting in test explorer.

**Comment by bernd5** [comment]
Have a look at the tooltip. VS2022 seems to support just a single colon:
![grafik](https://user-images.githubusercontent.com/26689688/141817195-868b3101-9381-4c5c-b595-8af85902388f.png)

I assume it works simply without the `file://`-prefix.

**Comment by OsirisTerje** [comment]
Current situation:
VS2022
![image](https://user-images.githubusercontent.com/203432/143777157-01fc98be-09a1-474a-bbfa-9716cb67eabc.png)
As reported

VS2019
![image](https://user-images.githubusercontent.com/203432/143777186-69d0c57a-750c-4b6f-b667-5b83655d0692.png)

Fixed by removing the ```file:// ``` prefix

VS2022
![image](https://user-images.githubusercontent.com/203432/143777218-48aa9579-cbac-4b8e-9fbf-b2e4d44147d0.png)

And it still works in VS2019
![image](https://user-images.githubusercontent.com/203432/143777234-a3a218cc-e502-4e6f-9f46-167c862a1e18.png)

**Comment by bernd5** [comment]
Thank you very much for fixing this issue 👍
When is next release published? I would like to update ...

**Comment by OsirisTerje** [comment]
Working on getting it out asap.  If all go well, by the end of this week.

**Comment by vpenades** [comment]
@OsirisTerje A while ago [I opened an issue related to this in VS feedback](https://developercommunity.visualstudio.com/t/Test-results-window-is-broken-in-16100/1437973#T-N1575684-N1603949).

They never fixed it in VS2019 but they claimed it was fixed in VS2022.

Now I've got the opportunity to test in in VS2022 and found the issue remains, and it's related to the "file://" prefix.

I've reopened the VS issue since I believe it needs to be fixed on both sides for maximum compatibility.

**Comment by OsirisTerje** [comment]
@vpenades Have you checked the latest version if it works there?  <PackageReference Include="NUnit3TestAdapter" Version="4.2.0-dev-01909" />  (From https://www.myget.org/feed/nunit/package/nuget/NUnit3TestAdapter) .   It does seem the file prefix is actually still there, just not being shown in the test explorer, so would be interesting to see if it works or not elsewhere.

**Comment by vpenades** [comment]
@OsirisTerje not sure if I will be able to do that because it would require us to push the nuget into our production pipeline so it can reach our CI environment. I'll give it a look, though.

**Comment by OsirisTerje** [comment]
@vpenades You should be able to run it locally just using the same commandline. That would be enough to verify it.   Also, alternatively, you don't need to push the package up, you can just refer to the myget source feed. That feed only contains the latest dev packages, and not any releases, they will anyway be picked off nuget.org, so it should not crash with anything else.

**Comment by OsirisTerje** [comment]
@bernd5 @vpenades   Version 4.2.0-beta.1 released now on nuget.org  https://www.nuget.org/packages/NUnit3TestAdapter/4.2.0-beta.1 .  It also contains an engine upgrade, which is the reason for the beta.  Would appreciate confirmation that it still works for you.

**Comment by vpenades** [comment]
@OsirisTerje Sorry for the late reply, I am in crunch time right now, but I'll give the beta a try as soon as I can.

Thanks for the effort!

**Comment by bernd5** [comment]
For me the new beta works perfectly 👍.
Thank you very much.

**Comment by vpenades** [comment]
@OsirisTerje I was able to test the beta1 both within VS2022 test explorer and within TeamCity tests system, and both are able to display the test attachments correctly.

I still believe that Visual Studio should be more forgiving regarding paths, since a "file:///c:xxx" should be valid, but that falls into MS side.
