### ISSUE TITLE
Working directory is set to VS TestWindow extension directory

### ISSUE THREAD

**Issue by jlewin** [nunit/nunit3-vs-adapter#96]
**Example**
![](http://i.imgur.com/POI7wCI.png)

This issue seems easy to punt on because of the dependency on the external NUnit.ApplicationDomain component but the v3 console-runner works as expected in this configuration (suggesting the quirk is in the new vs-adapter) and this is a breaking change when upgrading from v2 that affects a number of our tests when run from the IDE.

**Repro**
1. Create a new library project in VS2015
2. Install NUnit v3 NuGet package
3. Install NUnit3TestAdapter v3.0.8-ctp-8 NuGet package
4. Install NUnit.ApplicationDomain v6 package
5. Create a new Test
6. Add a statement to break on
7. Add a breakpoint for the statement
8. Debug the test

**Expected**
The WorkDirectory and TestDirectory properties should be the same and Directory.GetCurrentDirectory should resolve to the current test directory

**Actual**
The WorkDirectory property and the current directory both point to the location of the VS2015 TestWindow extension location

**Expected**
![](http://i.imgur.com/DPmelgp.png)

**Comment by CharliePoole** [comment]
There is definitely an issue here but I'm afraid that what you say should be the expected behavior does not match NUnit's specifications. From the NUnit docs:

**TestDirectory**

Gets the full path of the directory containing the current test assembly. Not available in Silverlight or Portable builds.

**WorkDirectory**

Gets the full Path to the directory to be used for output from this test run. The XML result file and any redirected output files are located under this directory. This is normally the directory that was current when execution of NUnit began but may be changed by use of the --work option of nunit-console.

TestDirectory and WorkDirectory cannot always be the same for several reasons:

* There is one WorkDirectory for a run while the TestDirectory changes for each assembly.
* WorkDirectory must be writeable, since stuff gets written there.
* WorkDirectory is set by the runner whereas TestDirectory is always set by the framework to the location of the test assembly.

Current Directory is never changed by NUnit or the adapter. It's value is whatever it was when the program was called.

That said, it's definitely a bug that WorkDirectory is set to a subdirectory of Program Files, which is bound to be non-writable at least by non-admin users. The value it has comes from the current directory, which is apparently set by Visual Studio.

The problem of writability doesn't normally arise, because the adapter does not actually write anything to a file. However, the intent of WorkDirectory is that you will use it as the location for any files you create yourself.

Until such  time as we have a way to pass settings to the adapter (issue #49) what do you  think would be a reasonable default to use for WorkDirectory?

**Comment by jlewin** [comment]
The 'Expected' heading was based on the behavior of the v2 vs-adapter, where the file system's working directory and the .WorkDirectory property were set to the directory containing the testfixture assembly on test startup (as depicted in the second attached image in the original post). After the upgrade to v3, my tests break when write operations to relative paths fail, as you noted, because of the privileged location in Program Files. So to me it looked like a breaking change that I wanted to bring attention to.

>WorkDirectory: ... This is normally the directory that was current when execution of NUnit began but may be changed by use of the --work option of nunit-console.

When run via command line, I can see how making any changes to the current directory or the WorkDirectory property would be inappropriate. However, when run from inside of VS via the TestAdapter, leaving the path unchanged seems invalid and inconsistent with the old behavior

>Current Directory is never changed by NUnit or the adapter. It's value is whatever it was when the program was called.

Based on the fact that tests run under the old adapter had the file system working directory and the test .WorkDirectory property set to my applications output directory, I decided to look into this a bit more. It seems the old implementation did change the current directory before every test via the `DirectorySwapper` class when the constructor set `Environment.CurrentDirectory` and later restored it to its pre-modified value when disposed.

**Call Stack leading to Environment.CurrentDirectory assignment**
![Imgur](http://i.imgur.com/TBIo459.png)

>what do you think would be a reasonable default to use for WorkDirectory?

In my opinion, the original behavior makes the most sense and seemed consistent with how I'd expect it to work. Possibly with more exposure to the project I'd realize there's a bunch of cases where this behavior might not stand up but for the scenario I'm working on, it seems like the best outcome.

**Comment by jlewin** [comment]
As a proof of concept I threw together a quick update that restores the original behavior and confirmed that my initial v3 example from the screencaps now behaves as it did on v2:

https://github.com/jlewin/nunit3-vs-adapter/commit/e0b5d00e0b502ff83a4e724330aa40d140c01ef3

I doubt this is pull worthy but figured it might advance the discussion in some way

**Comment by CharliePoole** [comment]
I want to point out that while it sounds reasonable to talk about "changes" from the older version, this is a new program, written with goals that relate to the features of the NUnit 3.0 framework and engine - which are themselves new programs and not "upgrades."

Everything you write about DirectorySwapper, etc. is quite true. It's a breaking change. We had a lot of discussion on the forums and basically decided that this changing of the current directory was a bad idea. It has been changed in NUnit 3.0 for several years now and is documented on the breaking changes page: https://github.com/nunit/nunit/wiki/Breaking-Changes

Having an application that changes the current directory at various times is really quite a bad practice, particularly where parallel execution is possible. This is not something we plan to reverse and TestDirectory is intended to give you what you need to access that directory.

It might be possible to replicate the 2.0 behavior for the WorkDirectory but I hesitate to do it. It would work for the time being but it would break as soon as we are running assemblies in parallel. I'd rather find some good default location for you to write reports and allow the equivalent of the --work option to change it in the future. If we can't come up with anything in the short term, I guess setting it to the location of the TestDirectory might be a temporary fix. It would be an improvement on the current behavior.

**Comment by jlewin** [comment]
That all makes perfect sense. Thanks for bearing with me and talking through the problem. It seems the root of the issue is that unlike the console-runner, where the user controls the startup location, when running from the VS IDE via the adapter the working directory isn't set and starts in a context that's invalid. If the vs-adapter simply set the working directory to the VS output directory, it seems like everything would fall into place. No changes would be needed anywhere other than in the vs-adapter during startup and the question of where you started executing from would be answered in with a pattern that is consistent with how most things work in VS.

Do you see any issues with this approach?

Here's a commit that sort of works as discussed although I couldn't figure out how to get the output directory and as a workaround probe the first test for its source location. For a quick proof of concept it seems to work
https://github.com/jlewin/nunit3-vs-adapter/commit/cf6e8382ff36254c253413bbfc92221e3e495de5

And the results depicted in the IDE
![Imgur](http://i.imgur.com/eAsuJSX.png)

**Comment by CharliePoole** [comment]
While I don't like changing the current directory - and it breaks our policy not to do it - this is a tempting, apparently easy solution. OTOH, it has to be tested under all three adapter environments: Test Window, vsconsole and TFS, and it could be that some of them need a different solution.

@OsirisTerje what do you think?

**Comment by mwadams** [comment]
Just a +1 from me on the need to do this. We are using the NUnit3 Adapter with SpecFlow 2.0, and we don't wish to have explicit references to NUnit in our SpecFlow tests. This has broken a number of our tests that depend on external files, or output to the file system.

In case it is of interest, we run in Visual Studio 2015 and TeamCity.

**Comment by OsirisTerje** [comment]
It could be set like @jlewin  suggest, and we could have an override switch if it causes issues in other situations, but I can't really see how it could, as it is now it is worse - 
On a sidenote: we really need to get these switches into the runsettings btw.

**Comment by CharliePoole** [comment]
@OsirisTerje Thanks, I've been waiting for your feedback. I'll get a fix in for this.

**Comment by CharliePoole** [comment]
@mwadams Please keep in mind that this issue relates to the **WorkDirectory**, which is intended as a place to put output. While the fix suggested would set it to the **TestDirectory** if not otherwise set, you should really not be using the WorkDirectory as a place to read files. Essentially, the WorkDirectory is where NUnit saves its results and where you may save other things if desired. Perhaps the name is misleading, since it might lead you to think it means current directory.

**Comment by mwadams** [comment]
Yup - I appreciate that. The TestDirectory is (in VS2015) pointing to the correct place (and that's what I'm using in a SpecFlow Feature Hook).

I'm now going to work with the JetBrains TeamCity folks to see if we can get the working directory set up to point at the binary files being executed, rather than the root of the checkout directory (which would then reflect the behaviour of the previous TC NUnitRunner)

**Comment by CharliePoole** [comment]
The JetBrains  folks will have to give you the last word, but I suspect that they can't do that simply because the binaries may be in different locations. They generate a .nunit project file, which indicates where the assemblies are located, and they leave it up to NUnit to run the multiple assemblies.

**Comment by mwadams** [comment]
While that is true, everything works fine in the VS2015 test runner because theAppDomain.CurrentDomain.BaseDirectory is correctly set to the context of each test assembly, whereas this seems to be set incorrectly in the TeamCity runner. I'm hoping to get some consistency of approach between the various runners.

**Comment by CharliePoole** [comment]
The NUnit adapter gets a list of assemblies from VS. It then runs each of them, sequentially, in separate NUnit runs. Each assembly gets it's own AppBase, because it's the default and the adapter doesn't override it.

TeamCity has made the decision to run all assemblies together as an NUnit project. That decision limits their flexibility. They have to choose the same appbase for all the assemblies. I have already commented to the TC devs that I think they made a poor implementation choice. I doubt they are going to change it now.

You can, of course, run under TeamCity using your own script. In that case, you can make your own choices. :-)

**Comment by mwadams** [comment]
It turns out that there is an as-yet-undocumented TC configuration parameter nunit_use_project_file which, if you set it to 'false' passes the assemblies in a similar way to the VS test adapter, and it all works correctly!

**Comment by CharliePoole** [comment]
Well cool! I think you will find this works much better for different appbases. In general, NUnit 3 works best using it's defaults. In fact we changed the defaults in many cases so that simply putting a list of assemblies on the command line will work without need to override:

* Each assembly is run in a separate process
* Each assembly gets an appbase where it is located
* Each assembly runs under it's target runtime framework, if available

We expect that this will work for most people most of the time.

**Comment by niemyjski** [comment]
I'm also running into this after upgrading from nunit2 to nunit3 all my msbuild tests (command line and resharper tests are failing). Was there a solution for htis?

**Comment by CharliePoole** [comment]
Sorry, this issue is still open.

**Comment by CharliePoole** [comment]
@jlewin What do you think of a solution that sets TestDirectory and WorkDirectory properties as you requested but does __not__ change the current directory. Would that work for you?

As a fallback, we could change current directory in the adapter (not in nunit) but I'd as soon avoid doing that.

**Comment by CharliePoole** [comment]
PR #139 is the fix for this if everyone agrees. Or remains silent. :-)

**Comment by rprouse** [comment]
:+1:

**Comment by glen-nicol** [comment]
So to be clear, the current directory is not changed in the adapter. Users have to use the NUnit.Framework.TestContext.CurrentContext.WorkDirectory property to combine paths or manually move there?

**Comment by CharliePoole** [comment]
Yes, but...

You should use WorkDirectory for output, TestDirectory for reading input files in the same directory as the assembly. In that way, your tests will work under all runners, not just the adapter.

**Comment by glen-nicol** [comment]
Understood. Thanks!
