### ISSUE TITLE
Nunit won't discover working non explicit tests Visual studio 2022

### ISSUE THREAD

**Issue by StijnOttenVMT** [nunit/nunit3-vs-adapter#972]
NUnit 3.13.3
Nunit3TestAdapter 4.2.1

VS 2022 17.1.4
VS 2022 17.2.0 Preview 3.0

.NET 6.0

I have 3 normal and 1 explicit test but when I run my test using the Test Explorer window I get this output under "Tests" in the Output window

    ========== Starting test run ==========
    NUnit Adapter 4.2.0.0: Test execution started
    Running all tests in xyz.dll
       NUnit3TestExecutor discovered 1 of 1 NUnit test cases using Current Discovery mode, Explicit run
    ExplicitMethod(03/10/2022 08:00:00,03/10/2022 16:00:00): OneTimeSetUp: 
    NUnit Adapter 4.2.0.0: Test execution complete
    ========== Test run finished: 1 Tests (0 Passed, 0 Failed, 0 Skipped) run in 462 ms ==========

*Note I'm using NUnit Adapter 4.2.1 instead of 4.2.0 so that's already weird

And this is how the Test Explorere looks
![image](https://user-images.githubusercontent.com/96051113/163153506-f0991050-8a83-4e61-af5e-14b2c49b55b2.png)
*Note the full blue icon is the explicit test that gets skipped like it should

This is a problem because it does seem to only discover tests which are explicit.

The tests I want to run are of course not explicit, here is an example

    [Test]
    [TestCaseSource(nameof(TestNameData))]
    public async Task<float> TestName(DateTime start, DateTime end, List<CalculateHoursObj>? list = default)
    {
        if (list == null) list = new List<CalculateHoursObj>();
        return await EmployeeService.CalculateOverTimeHours(start, end, list);
    }
    public static IEnumerable TestNameData
    {
        get
        {
            yield return new TestCaseData(TenthMarch8_2022, TenthMarch16_2022).Returns(8.0f);
        }
    }

It fails to discover and/or run this test.

But curiously if I break all my non explicit tests by making the data non-static like this

    public IEnumerable TestNameData
    {
        get
        {
            yield return new TestCaseData(TenthMarch8_2022, TenthMarch16_2022).Returns(8.0f);
        }
    }

It of course breaks the test and when I run all tests it does actually discover all tests

    ========== Starting test run ==========
    NUnit Adapter 4.2.0.0: Test execution started
    Running selected tests in xyz.dll
       NUnit3TestExecutor discovered 2 of 4 NUnit test cases using Current Discovery mode, Non-Explicit run
    NUnit Adapter 4.2.0.0: Test execution complete
    ========== Test run finished: 2 Tests (0 Passed, 2 Failed, 0 Skipped) run in 394 ms ==========

But even now it only runs 2 of the 3 broken non explicit tests and of course they all fail

This seems to be a problem with NUnit, if not advise/help is very much appreciated

**Comment by StijnOttenVMT** [comment]
>  b) Add it as a zipped attachment here 
[Issue_972.zip](https://github.com/nunit/nunit3-vs-adapter/files/8487827/Issue_972.zip)

Hope this works

**Comment by OsirisTerje** [comment]
Thanks for the code.  
This is not related to using the explicit attribute or not.
This is an issue with the DateTime you're using.  Between execution discovery and execution run there will be a time difference and using a testcasesource means that the data actually becomes part of the name of the test.  When these doesn't match it will fail to discover anything.  

I added a couple of simplified tests to see how this works, and get the same results.  Using a Datetime as a parameter makes the test undiscoverable, but using e.g. a DateOnly will do.  I understand you can't use the same, but you need to create your own similar struct to represent HOurs and possibly minutes.  It is the milliseconds parts that probably causes this issue. 

My tests came out as this:
![image](https://user-images.githubusercontent.com/203432/163456004-f0dfffe5-b1de-4e2f-869d-c3fc823ce46d.png)

Looking at the test results otherwise, I do see it complain on not finding the test.

However, if I add the following two runsettings properties:

```
	    <UseParentFQNForParametrizedTests>true</UseParentFQNForParametrizedTests>
	   <UseNUnitIdforTestCaseId>true</UseNUnitIdforTestCaseId>
```
it should use the parents instead, and ignore child names, and further also use NUNit Ids instead of FQNs, and it works for my repro but not for your tests:
![image](https://user-images.githubusercontent.com/203432/163457019-f6e106b9-ef4b-41a8-91f2-916bd5a721ab.png)

This indicates that the error is deeper, but it is in the same alley so to speak.  
I've added the Dump properties, and if I look at the execution dump, I do see the following error message:
```
 <test-suite type='TestFixture' id='0-1019' name='EmployeeServiceTest' fullname='Issue_972.Tests.API.Services.EmployeeServiceTest' classname='Issue_972.Tests.API.Services.EmployeeServiceTest' runstate='NotRunnable' testcasecount='0'>
                     <properties>
                        <property name='_SKIPREASON' value='An exception was thrown while loading the test.&#xD;&#xA;System.ArgumentException: Supplied arguments do not match required method parameters (Parameter &apos;argList&apos;)&#xD;&#xA;   at NUnit.Framework.Guard.ArgumentValid(Boolean condition, String message, String paramName)&#xD;&#xA;   at NUnit.Framework.Internal.GenericMethodHelper.TryGetTypeArguments(Object[] argList, Type[]&amp; typeArguments)&#xD;&#xA;   at NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.CheckTestMethodSignature(TestMethod testMethod, TestMethodMetadata metadata, TestCaseParameters parms)&#xD;&#xA;   at NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.BuildTestMethod(IMethodInfo method, Test parentSuite, TestCaseParameters parms)&#xD;&#xA;   at NUnit.Framework.TestCaseSourceAttribute.BuildFrom(IMethodInfo method, Test suite)+MoveNext()&#xD;&#xA;   at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom(IMethodInfo method, Test parentSuite)&#xD;&#xA;   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildTestCase(IMethodInfo method, TestSuite suite)&#xD;&#xA;   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCasesToFixture(TestFixture fixture, IPreFilter filter)&#xD;&#xA;   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(ITypeInfo typeInfo, IPreFilter filter, ITestFixtureData testFixtureData)&#xD;&#xA;   at NUnit.Framework.TestFixtureAttribute.BuildFrom(ITypeInfo typeInfo, IPreFilter filter)+MoveNext()&#xD;&#xA;   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfo typeInfo, IPreFilter filter)' />
                     </properties>
                  </test-suite>
```
So you do have a parameter mismatch, which causes your test to be not runnable.  But once that is cleared out, you should have a look if you want to keep using the DateTime or not.  If you do, you need to add the two properties I have shown above.

I've pushed the repro code up to the [Issues repo](https://github.com/nunit/nunit3-vs-adapter.issues), it is under folder Issue972, so you can check it out there.
The dumps are in a Dump folder under the bin\debug\net6 folder.   
The information on the runsettings can be found here:  https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html

**Comment by OsirisTerje** [comment]
Please confirm when you have fixed the code.

I then assume this issue can be closed, but it could be an idea to add another issue for making this more discoverable.  When a test is not runnable, that should have been displayed.

**Comment by OsirisTerje** [comment]
I just looked closer at the code, and in your test case sources, you must ensure they do match up with respect to arguments.  I added the missing ones, and the tests now appears as they should, some are red and some are green.
See the latest code under Issue972 https://github.com/nunit/nunit3-vs-adapter.issues

**Comment by StijnOttenVMT** [comment]
Hey thanks I've followed your advice and the tests are running properly again.

The solution seems so trivial but there was really no feedback indicating that it was a problem.
Maybe there should be a clear error message shown in the Test Output.

**Comment by OsirisTerje** [comment]
Good to hear it works for you!

And yes, I do agree about the error messaging.   We do have a few of these, so I'll create a separate issue for that.
